- src/services/index.js
Problem: When I started with npm install, the following error occured:
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN localhost:27017]
This is the same error as in http://stackoverflow.com/questions/41318354/mongodb-failed-to-connect-to-server-on-first-connect
Cause: The name 'localhost' can not be resolved to 127.0.0.1.
Solution: As pointed out in https://github.com/Automattic/mongoose/issues/3049#issuecomment-108620496
the solution is to set the host of mongodb to 127.0.0.1
Implementation: This is implemented by allowing a environment variable to set the mongodb host.
The variable is optional and is named DB_URL as it also includes the data base.
> Added command line option for mongo db

- src/services/account/hooks/index.js
- src/services/lesson/hooks/index.js
- src/services/passwordRecovery/hooks/index.js
can't restrict the access further without an api key or any other security...
tried stripping the password or any other information, but those are needed by the feathers-authentication-local for verification purposes.
A proper solution could be to write an own verifier, which does not rely on the account service, but uses mongoosejs to directly talk to the db.
> restrict access to accounts

- src/hooks/index.js
- src/services/helpdesk/hooks/index.js
- src/services/news/hooks/index.js
checks in a remove request whether the schoolId of object and requesting user are equal.
Can also be used for any other hook type that supports `/@id` and has a schoolId or just use restrictToCurrentSchool.
Can also be used for any service that has a schoolId in it, just tested it with news and helpdesk service.
> added generic hook for school check

- src/services/account/hooks/index.js
- test/services/account/index.test.js
As https://github.com/schul-cloud/schulcloud-server/pull/297 is currently stuck in bureaucracy, I wanted to at least address the problem with the possibility to create multiple accounts with one userId.
Deals to a limited extend with SC-149
> no double account creation

- src/services/authentication/index.js
Anfragen mit Postman und jwt token funktionierten nicht, da im header for dem token "Bearer " angefügt wird. Soweit nicht so kritisch, jedoch produzieren manche Bibliotheken die wir einsetzen ebenfalls solche header mit "Bearer" vor dem token (bspw. Vue.js Einbindung von Jonas, Content Editor aus Seminar). Ich habe das jetzt so implementiert, dass es sowohl mit als auch ohne "Bearer " im Header funktioniert.
> aj/Authorization Header Fix

- src/services/fileStorage/proxy-service.js
- src/services/wopi/index.js
Reverted back to using the file encoding for the files as utf8 can not be used in an url, the reason why it failed is that wopi is all handled in the backend and didn't care about the encoding as the binary stream is just provided to the request.
Uploading a file with utf8 (spaces/special characters) worked before as the encoding was handled in the client.
Creating a new file from the client did not work, as the server nor the client encoded the file names and was thereby inconsistent with the rest of the file system.
To verify that it works use the following scenario:
following requests on the server:
add Header `X-WOPI-Override` with value `PUT` and change the Body to raw and write something random in it:
to verify: 
Other scenarios to test:
Upload a docx with spaces and special …
> Change File Creation for WOPI

- backup/setup/accounts.json
- backup/setup/users.json
Für den Einstieg in die Schul-Cloud hat sich bei der Einrichtung im BP herausgestellt, dass die verschiedenen Passwörter in den Backup Daten etwas verwirrend sind. Da die Daten sowieso nur lokal bei der Entwicklung verwendet werden würde ich vorschlagen das Standard Passwort in den Demodaten wie hier auf `schulcloud` zu ändern.
Zusätzlich habe ich einen weiteren Benutzer `Super` `Hero` (`superhero@schul-cloud.org`) eingeführt, welcher Zugang zum Superhero dashboard hat und somit für dieses als Testnutzer genutzt werden kann.
Feedback? und habe ich kritische Stellen vergessen, wo die neuen Passwörter noch eingetragen werden müssen?
> Simplify Seed Data

- src/services/consent/hooks/consents.js
https://ticketsystem.schul-cloud.org/browse/NC-92
Rebuild from old registration to new registration without redirectdic got a bug where every user got a firstlogin flag patched in which results in skipping firstlogin process even if needed.
Rebuilt status as before: 
1) Only demo users and staff will get patched with firstlogin
2) If access is valid (consents as needed) but no firstlogin is set, revoke access which results in redirect to firstlogin process of login controller
> NC-92: Fix Firstlogin that was not triggered on any user anymore

- src/services/consent/hooks/consents.js
2 issues existed within user (student/teacher) management:
1) crash if there are no users (school without students or teachers) - client-side, fixed in client #965 (NBC) and #918 (HSC)
2) crash if consent exists with an unknown userId (eg deleted user, consents dont get deleted), crashed within decorateConsents() - server-side, this here is NBC fix
Test: Create user, do registration (consent is created), delete user with user management UI (user is deleted, consent is not), open user management, which is displayed
@Metauriel Can this catch be problematic in any other way/logic? Please check that after your vacation.
> N21: Fix broken user management

- package.json
Maybe we should use something like https://www.npmjs.com/package/cross-env to consolidate our build scripts (to remove all the "...-windows" scripts). I'd be happy to provide this in a separate PR.
> Fix npm scripts on windows

- package-lock.json
- package.json
CC: @schul-cloud/coredevs @schul-cloud/hiwis @schul-cloud/masterstudis 
I've added cross-env to de-clutter our build-scripts (no more *-windows scripts!). In the process I removed scripts that I thought are unnecessary. If you need them, please report here.
One thing is still annoying on Windows: We're still depending on Git Bash (due to backup.sh). You can use `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"` (update for your system!) to use git bash for all npm build scripts. This is most likely required on Windows with this PR. However, implicitly, it was already a requirement. In the future, we could migrate to platform-independent (node-based) scripts.
> Update build scripts

- src/services/fileStorage/proxy-service.js
- src/services/fileStorage/strategies/awsS3.js
and renamed files now initiate this filename at
download instead S3 real filename
https://ticketsystem.schul-cloud.org/browse/SC-963
> Fix 2 problems at once: no more timestamp prefix

- .pullapprove.yml
- PULL_REQUEST_TEMPLATE.md
change number of requested reviewers
- Begründung:
- Code
- Swagger
> change identifier for travis and stickler

- src/services/rocketChat/index.js
- src/services/teams/hooks/helpers.js
Beim erstellen eines neuen Teams wird das flag für RocketChat jetzt richtig mit übernommen und nicht beim team create überschrieben.
> Naming and allow additional feature flags in team create.

- .pullapprove.yml
- PULL_REQUEST_TEMPLATE.md
- codecov.yml
- Begründung:
- Code
- Swagger
> Disable travis check in pullapprove until they fix the issue

- src/services/index.js
- src/services/news/events/index.js
- src/services/news/hooks/index.js
- src/services/news/index.js
- test/services/news/index.test.js
Event-Listener im News-Service, der auf `team:removed` hört und dann betreffende News löscht.
- ~~https://github.com/schul-cloud/schulcloud-client/pulls/????~~
- ~~Im Ticket (oder PR, wenn kein Ticket): Beschreibung und Begründung der Änderung/Neuerungen~~
- ~~Alle DB-Anpassungen müssen in den Seed-Daten reflektiert werden~~
- Code
- Swagger
> SC-759 delete team news after deleting the team

- src/services/homework/hooks/index.js
Zu diesem Bug gibt es bisher kein Ticket. In homework/hooks/index.js wurde beim Fixen der Linter-Errors == durch === ersetzt. Durch die fehlende Umwandlung der userId in einen String in hasViewPermissionAfter() wurden private Aufgaben daraufhin auch ihren Erstellern nicht mehr angezeigt.
- Begründung:
- Code
- Swagger
Weitere …
> fix-permission-check-for-private-tasks

- src/swagger.js
Enable use of the Swagger UI to actually access/test the API.
- Begründung:
- Code
- Swagger
> Fix Swagger configuration

- src/services/user/index.js
- src/services/user/registration.js
Client-PR: https://github.com/schul-cloud/schulcloud-client/pull/1195
Formularfelder wurden beim Ausfüllen durch Eltern (Registration unter 16) nicht korrekt erkannt und der Consent mit falses abgespeichert. Dadurch wurde im Firstlogin nochmal nach Elternconsents gefragt.
- https://github.com/schul-cloud/schulcloud-client/pull/1195
> Hotfix/SC-1306 Fix too long firstlogin

- .travis.yml
- package.json
- test/services/news/index.test.js
- Begründung: Enable coverage in codacy
- Code
- Swagger
> Switch from codecov to codacy

- src/services/fileStorage/proxy-service.js
Es wird nun auch die Ordner-Berechtigung geprüft, wenn man versucht Dateien darunter zu finden.
- keine Änderungen erforderlich
- Begründung:
- Code
- Swagger
- nicht nötig
> [SC-1538] Check read permissions of parent directory before searching for files

- src/services/sync/strategies/CSVSyncer.js
- test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
- test/services/sync/strategies/CSVSyncer/CSVSyncer.unit.test.js
Quick-win fix for CSV files with users that are put in one class multiple times (e.g. `1a+1a+1a`) and hardening of tests.
> Improve CSV-Importer handling of duplicate classes

- src/services/account/hooks/index.js
- src/services/ldap/strategies/general.js
- Begründung:
- Code
- Swagger
> LDAP fix no specific user folder

- src/services/fileStorage/SecurityCheckService.js
- src/services/fileStorage/hooks/SecurityCheckService.hooks.js
- src/services/fileStorage/index.js
**Base is main feature branch, not develop**
- https://ticketsystem.schul-cloud.org/browse/SC-2317
- https://ticketsystem.schul-cloud.org/browse/SC-1155
- https://github.com/schul-cloud/schulcloud-server/pull/836
Adds a file security check callback service.
- workflow: On file upload, the proxy-service sends a request to the external service (https://github.com/schul-cloud/antivirus_check_service), parking a temporary signed URL and a response URL in a virus scan queue (see #836). Once the external service scans the file, it calls the response URL, which updates the file's status
> [SC-2317] Implement security check callback service

- .travis.yml
- added an option to skip the test stage for really urgant changes that need to be deployed fast. Just **add `skip-test-stage` to your commit message**
- only works if the pull targets the master branch
- it's not possible to change the order of the stages using this approach, because I am only allowed to define each stage name once (in line 19-22) and travis will ignore the second definition + conditions. So in order to execute the tests afterwards you need another commit (where you **add `skip-deploy-stage` to the commit message** )
- client PR: https://github.com/schul-cloud/schulcloud-client/pull/1508
> allow to skip travis stages

- package-lock.json
- package.json
- test/app.hooks.test.js
- test/services/datasources/datasourceRuns.test.js
Mocha behaves differently on every platform when using the `--extension` parameter or globs to include only `.test.js` files. This PR hopefully makes it work on every platform.
Works on:
> Fix mocha on Windows

- backup.sh
- config/default.json
- config/lokal.json
- config/test.json
Changes the mongo connection string to use IPv4 to avoid DNS lookups (the MongoDB driver assumes IPv6 and tries to look up `localhost`, which takes a few seconds on Windows for some reason...). This way, the tests and `npm run seed` perform much better on Windows.
> Fix tests on Windows v2

- src/services/ldap/strategies/general.js
- src/services/ldap/strategies/iserv.js
Some schools prefer not to use first names in their iServ, so their LDAP won't give us any `givenName` for these users, which is a problem, because `user.firstName` is a required field. This PR sets some sensible defaults.
> [SC-2706] Use generic first names if synced users don't have a givenName

- src/services/authentication/hooks/index.js
- test/services/authentication/authentication.test.js
- Begründung:
- Code
- Swagger
> SC-2767-trim-credentials

- src/services/messengerSync/consumer.js
Failed messages have to be removed from the queue to avoid endless loops.
> Fix: Messenger discard failed message after one retry

- src/services/videoconference/logic/server.js
While trying to activate the big blue button integration, we noticed that the error message speaks of a different value than what needs to be [set in the environment](https://github.com/schul-cloud/schulcloud-server/compare/develop...bitcrowd:fix-error-message?expand=1#diff-c0b437d8676620274b8f1c805f65b172L6).
- Begründung:
- Code
- Swagger
Weitere Informationen zur DoD [hier im …
> Match the error message with the env variable name

- CHANGELOG.md
- backup.js
fixes a bug, that all exports haven't containes `,` as delimiters
> fix backup.js export

- .mergify.yml
Use mergifys smart merge strategy to save some CI execution time.
The smart merge mode will queue all prs to be merged and will only update one by on, so there will never be two PRs that compete against each other which would get merged first.
Documentation:
https://doc.mergify.io/actions.html#merge
> use mergify smart merge strategy

- package.json
As far as I can see we only use [Chai](https://www.chaijs.com/) for testing.
> Please do not put test harnesses or transpilers in your dependencies object. See devDependencies, below.
— https://docs.npmjs.com/files/package.json#dependencies
> Move "chai" packages to "devDependencies"

- CHANGELOG.md
- test/services/user/services/userService.test.js
- Begründung:
- Code
- Swagger
> fix user tests

- src/services/videoconference/logic/index.js
just log the error for debugging reasons. this allows to get error messages like checksum error (for wrong salt) into the log
> gitflow-feature-stash: enhance-bbb-errors

- src/services/fileStorage/proxy-service.js
- test/services/fileStorage/index.test.js
When generating a signed URL for downloading a file, accept the `name` query argument so that the client can name download files.
This allows us to rename files that students handed in as homework submission so that they can be downloaded by the teacher, graded, and then re-uploaded in bulk, with an automatic assignment to the proper student/team.
[Story](https://ticketsystem.schul-cloud.org/browse/SC-4064) (Part 3, in preparation for 4)
Allow the client to change the file names of requested files
- Prioritize query names over saved names when setting the download file name in signed fetch URLs.
- Add what seems to be the first test using `sinon`.
No change in permissions, or models.
More …
> [#SC-4064-3] Change download file names (3/4)

- migrate_etherpad.js
- package-lock.json
- package.json
a new script to migrate old etherpad instances into new locations (same server).
- https://ticketsystem.schul-cloud.org/browse/SC-4197
- https://github.com/schul-cloud/schulcloud-server/pull/1392
No Changes, just a new script to migrate old etherpad instances into new locations (same server).
No ENV, only one argument: OldPadDomain, eg.
`node ./migrate-etherpads.js etherpad.schul-cloud.org`
No Repos, no dependencies.
> etherpad migration

- CHANGELOG.md
- src/services/school/model.js
- test/services/school/index.test.js
Adds isExternal attribute to school schema if ldapSchoolIdentifier or source are present.
Origin ticket:
https://ticketsystem.schul-cloud.org/browse/SC-5754
Subtask of:
https://ticketsystem.schul-cloud.org/browse/SC-5541
> Feature/sc-5754 - is external school attribute

- .eslintrc.js
- CHANGELOG.md
As decided by the architecture chapter in https://docs.hpi-schul-cloud.org/display/CARCH/2020-08-26+Architecture+Meeting the selected rule `no-await-in-loop` will be removed from eslint exceptions.
> SC-6774 Remove no-await-in-loop from eslint exceptions in server

- CHANGELOG.md
- package-lock.json
- package.json
- src/services/authentication/hooks/index.js
- src/services/authentication/index.js
- src/services/authentication/strategies/TSPStrategy.js
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/SC-6942
- fixes logging in with TSP
- fixes jwt payload being overwritten by random params from malfunctioning hook
- adds the `parse` method to the TSP login strategy to prevent other login strategies to be considered during TSP login
> SC-6942: fix TSC login

- CHANGELOG.md
- src/services/edusharing/logic/MerlinTokenGenerator.js
This fixes an export issue.
Changed from:
`module.exports = {myClass}` 
to:
`module.exports = {new myClass()}`
> Fix module export of new instance of merlin class

- CHANGELOG.md
- config/default.json
- config/default.schema.json
- config/development.json
- config/globals.js
- src/helper/externalApiRequest.js
- src/services/calendar/index.js
- src/services/content/index.js
- src/services/edusharing/logic/connector.js
- src/services/helpers/service.js
- src/services/notification/index.js
- src/services/rocketChat/helpers.js
This PR moves REQUEST_TIMEOUT into Configuration without any renaming.
The development timeout overrides the default which is not touched.
> SC-6080 - move REQUEST_TIMEOUT from globals to Configuration

- CHANGELOG.md
- migrations/1602693850245-search_index.js
- src/services/user/model/user.schema.js
- src/utils/search.js
- test/utils/search.test.js
MongoDB use dash to exclude the following word from search. To prevent this it should not be included in the search string. Names with a dash will be handled as two names.
> Quickfix - split search at dash

- CHANGELOG.md
- src/services/ldap/strategies/iserv-idm.js
Adds an optional rootPath attribute to iserv-idm strategy for local LDAP test container to simulate a Central IServ. See https://github.com/hpi-schul-cloud/ldap-test-tools#creating-an-ldap-configuration.
This will not interfere with production if no explicit rootPath is set.
Follow-up of https://ticketsystem.hpi-schul-cloud.org/browse/SC-7370
- iserv-idm strategy will search for schools at the configured rootPath (system.ldapConfig.rootPath) and default to '' (empty string) if no rootPath is configured.
not applicable
Doesn't change deployment. For local configuration, see https://github.com/hpi-schul-cloud/ldap-test-tools#creating-an-ldap-configuration.
not applicable
More and detailed information on the *definition of done* can be found [on …
> SC-7370 Add optional rootPath attribute to iserv-idm strategy

- CHANGELOG.md
- src/services/edusharing/services/EduSharingConnector.js
- test/services/edusharing/services/EduSharingConnector.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8390
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1640
in Lern-Store, the search now does not return collections anymore when the FEATURE_ES_COLLECTIONS_ENABLED=false
> SC-8390 - prevents Lern-Store collections search when flag is false

- CHANGELOG.md
- package-lock.json
- package.json
- startup.sh
Remove of the Auto Sync of the migrations.
The auto-sync of the migations trigger to much trubel if running massiv pods from Server.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8934
Remove of the Auto Sync of the migrations.
> SC-8934 - no more autosync for the migrations for the mongodb

- src/logger/syncLogger.js
- src/services/sync/repo/class.repo.js
- src/services/sync/repo/user.repo.js
- src/services/sync/strategies/LDAPSyncerConsumer.js
- src/services/sync/strategies/consumerActions/ClassAction.js
- test/services/sync/repo/class.repo.integration.test.js
- test/services/sync/repo/user.repo.integration.test.js
- test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
- test/services/sync/strategies/LDAPSyncerConsumer.test.js
- test/services/sync/strategies/consumerActions/ClassAction.test.js
- test/services/sync/strategies/consumerActions/SchoolAction.test.js
- test/services/sync/strategies/consumerActions/UserAction.test.js
The sync of Students and Teachers where forgotten, re add it.
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/2460
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8898
- Re add missing Studetns and Teahcer snc to a classes
> SC-8898 add missing function for sncy of students and teachers for a class.

- .travis.yml
- CHANGELOG.md
- build.sh
Change buildpipelines (Server, Client, Nuxt) to execute E2E tests according QF decision
- https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2418
- https://docs.hpi-schul-cloud.org/display/TSC/Deployment+to+test%2C+staging+and+hotfix?src=jira
enable the execution of E2E tests according to the confluence table
update the table with implementation status
NOT in Fix
the evaluation of suppressing E2E tests in PRs based on label presence (OPS-2419)
the implementation of a GitHub workflow to manually execute E2E tests (OPS-2420)
none
none
> [OPS-2418] add E2E tests only for PRs on feature branch

- CHANGELOG.md
- TODO.md
- apps/server/doc/testing.md
- test/app.hooks.redis.test.js
- test/jobs/rss-news/index.integration.test.js
- test/services/account/iserv/iserv.test.js
- test/services/authentication/authentication.integration.test.js
- test/services/authentication/hooks/index.test.js
- test/services/calendar/index.test.js
- test/services/courses/services/courseMembers.test.js
- test/services/datasources/datasourceRuns.test.js
This PR removes this.timeout(number) from mocha tests which is not required, when async functions are called/awaited correctly. 
Most of the time now, the timeout or other bad styled tests just succeed without being correctly executed.
With Node 14.17 tests might log unhandled rejections, like   `message: 'unhandledRejection: jwt malformed\n' +` to alert wrong promise handling.
Further information: https://docs.hpi-schul-cloud.org/pages/viewpage.action?pageId=154188581
> remove unneccesary timeout rules replaced by correct promise handling

- CHANGELOG.md
- ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2
- ansible/roles/schulcloud-server/templates/deployment.yml.j2
Reduce resource consumption for deployed server.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-54
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 150mb and 1gb.
Set the default pod count to 1 pod
> BC-37 - BC-54 - reduce resource consumption for deployed server

- CHANGELOG.md
- ansible/roles/schulcloud-server/tasks/main.yml
- ansible/roles/schulcloud-server/templates/onepassword.yml.j2
Rename ansible variables for OnePassword
https://ticketsystem.hpi-schul-cloud.org/browse/BC-331
https://ticketsystem.hpi-schul-cloud.org/browse/BC-352
Rename ansible variables for OnePassword
https://github.com/hpi-schul-cloud/dof_app_deploy/actions/runs/1283239384
> BC-331 - BC-352 - rename ansible variables for OnePassword

- apps/server/src/shared/repo/task/task.repo.integration.spec.ts
- apps/server/src/shared/repo/task/task.repo.ts
When a user creates a task in a course, and then is removed from that
course (for example when the course is deleted), the task will no longer
be visible.
This fixes an error caused by such tasks.
> BC-909 hide tasks a user created in courses he left

- ansible/roles/schulcloud-server-core/tasks/main.yml
Change the mode for the configmaps at the ansible roles to apply for configmaps and secrets
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1230
hpi-schul-cloud/dof_app_deploy#111
hpi-schul-cloud/antivirus_check_service#20
hpi-schul-cloud/superhero-dashboard#157
hpi-schul-cloud/schulcloud-client#2759
hpi-schul-cloud/schulcloud-calendar#109
hpi-schul-cloud/nuxt-client#2040
> BC-1230 - change mode for configmaps to apply

- ansible/roles/schulcloud-server-init/tasks/main.yml
Updated the schulcloud-server-init role to be togglable with the WITH_SCHULCLOUD_INIT variable
Needs  the WITH_SCHULCLOUD_INIT variable from https://github.com/hpi-schul-cloud/dof_app_deploy/pull/176
> OPS-3191 Updated schulcloud-server-init role to be togglable

- package-lock.json
- package.json
Bumps [winston](https://github.com/winstonjs/winston) from 3.5.1 to 3.7.2.
- [Release notes](https://github.com/winstonjs/winston/releases)
- [Changelog](https://github.com/winstonjs/winston/blob/master/CHANGELOG.md)
- [Commits](https://github.com/winstonjs/winston/commits)
---
updated-dependencies:
- dependency-name: winston
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
#3415 
> Bump winston from 3.5.1 to 3.7.2

- src/services/sync/strategies/LDAPSyncer.js
Make the LDAP Sync more robust by adding logging to users and classes.
If for one school of an LDAP System with many schools in it, the user don't sync, then only the users from this one school are partially synced.
The same is for classes.
https://ticketsystem.dbildungscloud.de/browse/BC-1436
> BC-1436 - add logging for Users and Classes errors for the ldap sync

- apps/server/src/shared/domain/entity/system.entity.ts
- apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.spec.ts
- apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.ts
Ensures that `npm run setup:idm:configure` is idempotent and removed database constraint on `System.alias`.
- https://ticketsystem.dbildungscloud.de/browse/EW-288
See description and Jira ticket.
Does not apply.
Does not apply.
Does not apply.
> Ew 288 Full idempotence for "setup:idm:configure"

- .github/workflows/test.yml
Increasing the timeout for the nest_tests_cov to 15 minutes to prevent the canceling of the job.
- <https://ticketsystem.dbildungscloud.de/browse/BC-2630>
- <https://docs.dbildungscloud.de/x/8wCvDQ>
See description and Jira ticket.
Does not apply.
Does not apply.
Does not apply.
> BC-2630 Increasing nest_tests_cov timeout from 12 to 15 minutes

- apps/server/src/core/logger/logger.module.ts
https://ticketsystem.dbildungscloud.de/browse/BC-2793
> BC-2793 add ms to the timestamp of log messages

- apps/server/src/modules/tool/controller/dto/response/oauth2-tool-config.response.ts
- apps/server/src/modules/tool/controller/mapper/external-tool-response.mapper.spec.ts
This extended mapping fixes the missing endpoint auth method in shd for ctl tools.
https://ticketsystem.dbildungscloud.de/browse/N21-481
> N21-481 Fix missing endpoint auth method

- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
This release will add multi line logging for ldap sync jobs to prevent logs to be cut off.
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3775
- https://ticketsystem.dbildungscloud.de/browse/BC-2776
- use infra-tools image instead of curl for sync cron jobs
- use jq to format the output
> BC 2776 Add multi line logging for ldap sync jobs

- apps/server/src/modules/tool/controller/dto/request/custom-parameter.params.ts
- apps/server/src/modules/tool/controller/dto/response/custom-parameter.response.ts
- apps/server/src/modules/tool/controller/mapper/external-tool-request.mapper.spec.ts
- apps/server/src/modules/tool/controller/mapper/external-tool-request.mapper.ts
- apps/server/src/modules/tool/controller/mapper/external-tool-response.mapper.spec.ts
- apps/server/src/modules/tool/controller/mapper/external-tool-response.mapper.ts
- apps/server/src/modules/tool/controller/tool.controller.spec.ts
- apps/server/src/modules/tool/controller/tool.controller.ts
N21-241 Changed property default name to defaultValue because openapi generator makes this property private as _default
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/199
https://ticketsystem.dbildungscloud.de/browse/N21-241
https://github.com/hpi-schul-cloud/nuxt-client/pull/2382
> N21-241 Changed property default name to defaultValue

- ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
- apps/server/src/modules/oauth/service/hydra.service.spec.ts
- apps/server/src/modules/oauth/service/hydra.service.ts
- apps/server/src/modules/oauth/service/oauth.service.spec.ts
- apps/server/src/modules/oauth/service/oauth.service.ts
- apps/server/src/modules/oauth/uc/hydra-oauth.uc.spec.ts
- apps/server/src/modules/oauth/uc/oauth.uc.spec.ts
- apps/server/src/modules/oauth/uc/oauth.uc.ts
- apps/server/src/modules/system/controller/dto/oauth-config.response.ts
- apps/server/src/modules/system/controller/mapper/system-oauth-response.mapper.spec.ts
- apps/server/src/modules/system/controller/mapper/system-response.mapper.ts
- apps/server/src/modules/system/mapper/system-oidc.mapper.spec.ts
- apps/server/src/modules/system/mapper/system-oidc.mapper.ts
- apps/server/src/modules/system/mapper/system.mapper.ts
- apps/server/src/modules/system/service/dto/oauth-config.dto.ts
- apps/server/src/modules/system/service/dto/oidc-config.dto.ts
- apps/server/src/modules/system/service/system.service.spec.ts
- apps/server/src/modules/system/service/system.service.ts
- apps/server/src/modules/user-login-migration/service/user-migration.service.spec.ts
- apps/server/src/shared/domain/entity/system.entity.spec.ts
- apps/server/src/shared/domain/entity/system.entity.ts
- apps/server/src/shared/infra/identity-management/keycloak-configuration/mapper/identity-provider.mapper.spec.ts
- apps/server/src/shared/infra/identity-management/keycloak-configuration/mapper/identity-provider.mapper.ts
- apps/server/src/shared/infra/identity-management/keycloak-configuration/service/keycloak-configuration.service.spec.ts
- apps/server/src/shared/infra/identity-management/keycloak-configuration/service/keycloak-configuration.service.ts
- apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-identity-management-oauth.service.ts
- apps/server/src/shared/testing/factory/system.factory.ts
- backup/setup/migrations.json
- backup/setup/systems.json
- migrations/1678889088654-RefactorSystemSubConfig.js
Remove or reword 'alias' propertie in systems's oidc and oauth configs to 'idpHint'. The property is used to indicate 3rd party IDP to the ErWIn IDM during the oauth authentification process.
- https://ticketsystem.dbildungscloud.de/browse/EW-481
See description
NA
The migration '1678889088654-RefactorSystemSubConfig.js' needs to be executed (rename of 2 properties).
NA
> EW-481 Re-work IDP hint handling

- ansible/roles/schulcloud-server-core/tasks/main.yml
- ansible/roles/schulcloud-server-core/templates/erwin-account-migration-job.yml.j2
Added a kubernetes job to migrate (copy) the accounts from the MongoDB accounts collection to erwin-idm (keycloak) when `ERWINIDM_ACCOUNT_MIGRATION` is set to true in dof_app_deploy.
Ticket: EW-129
Other PR: https://github.com/hpi-schul-cloud/dof_app_deploy/pull/525
Added a `erwin-account-migration-job` and two ansible tasks, one which removes any old job and one which creates the job if `ERWINIDM_ACCOUNT_MIGRATION` is set to true.
`ERWINIDM_ACCOUNT_MIGRATION` is set to true for production in the other PR which causes the job to be created for all four production instances on the next rollout after merge.
> EW-129 Migrate existing accounts from MongoDB to ErWin-IDM/Keycloak

- apps/server/src/modules/tool/common/service/common-tool-validation.service.ts
- apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.spec.ts
- apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.ts
Fixes duplications between context external tool display name and the external tool name
https://ticketsystem.dbildungscloud.de/browse/N21-1194
> N21-1194 Fix toolName duplication

- apps/server/src/modules/board/repo/board-node.repo.spec.ts
- apps/server/src/modules/board/repo/board-node.repo.ts
This reverts commit 476f79c0a624534727ad9528f8e5ec103d426209.
> Revert "BC-5162 - drag and drop race condition (#4420)"

- apps/server/src/modules/board/controller/api-test/submission-item-lookup.api.spec.ts
- apps/server/src/modules/board/controller/dto/submission-item/index.ts
- apps/server/src/modules/board/controller/mapper/submission-item-response.mapper.ts
api generator was confused somehow, and could not read correctly some types
this is a quick fix and a followup should clean it it
BC-4375
> BC-4375 - fix api generator

- apps/server/src/modules/group/domain/group.spec.ts
- apps/server/src/modules/group/domain/group.ts
- apps/server/src/modules/group/repo/group.repo.spec.ts
- apps/server/src/modules/group/repo/group.repo.ts
- apps/server/src/modules/group/service/group.service.spec.ts
- apps/server/src/modules/group/service/group.service.ts
- apps/server/src/modules/provisioning/strategy/oidc/oidc.strategy.spec.ts
- apps/server/src/modules/provisioning/strategy/oidc/oidc.strategy.ts
- apps/server/src/modules/provisioning/strategy/oidc/service/oidc-provisioning.service.spec.ts
- apps/server/src/modules/provisioning/strategy/oidc/service/oidc-provisioning.service.ts
- apps/server/src/shared/common/loggable-exception/not-found.loggable-exception.ts
completes the group provisioning from moin.schule by adding the removal of users from group and deltion of empty groups.
> N21 1212 remove user from group

- src/services/fileStorage/proxy-service.js
- src/services/fileStorage/utils/filePermissionHelper.js
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3324
- https://ticketsystem.dbildungscloud.de/browse/BC-5461
> BC-5461 - fix personal file page error

- src/middleware/errorHandler.js
- src/services/edusharing/services/EduSharingConnectorV6.js
prevent password logging of failed edusharing requests
BC-5044
> BC-5044 - prevent password logging of failed edusharing requests

- apps/server/src/modules/learnroom/service/common-cartridge-export.service.ts
Add the description of an etherpad content as the title of a weblink during export.
https://ticketsystem.dbildungscloud.de/browse/EW-553
> EW-553: Export description of etherpad content as title of weblink.

- .github/workflows/test.yml
- apps/server/src/modules/account/mapper/account-idm-to-dto.mapper.db.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-security.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-copy-files.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-delete-files.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-download-upload.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-list-files.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-preview.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-rename-file.api.spec.ts
- apps/server/src/modules/files-storage/controller/api-test/files-storage-restore-files.api.spec.ts
- apps/server/src/modules/legacy-school/service/school-year.service.spec.ts
- apps/server/src/modules/task/controller/api-test/task-copy-timeout.api.spec.ts
> BC-5597 - Fix unstable tests

- ansible/roles/schulcloud-server-core/tasks/main.yml
- ansible/roles/schulcloud-server-core/templates/api-files-ingress.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-fwu-ingress.yml.j2
- ansible/roles/schulcloud-server-core/templates/ingress.yml.j2
- ansible/roles/schulcloud-server-h5p/tasks/main.yml
- ansible/roles/schulcloud-server-h5p/templates/api-h5p-ingress.yml.j2
Separate the Server Ingress to the Server Repo and for each service in own.
With the current version of nginx ingress is it possible to have more igresses with different resources for one domain.
hpi-schul-cloud/dof_app_deploy#678
https://ticketsystem.dbildungscloud.de/browse/BC-5546
> BC-5546 - Split ingress for Domains 

- apps/server/src/modules/account/repo/account.repo.ts
https://ticketsystem.dbildungscloud.de/browse/BC-4887
> BC-4887 fix sorting by _id

- apps/server/src/modules/tool/common/service/common-tool-validation.service.spec.ts
- apps/server/src/modules/tool/common/service/common-tool-validation.service.ts
- apps/server/src/modules/tool/external-tool/service/external-tool-validation.service.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1187
> N21-1187 Fix optional External Tool parameter with regex

- apps/server/src/modules/board/repo/recursive-delete.visitor.spec.ts
- apps/server/src/modules/board/repo/recursive-delete.vistor.ts
- apps/server/src/modules/board/service/board-do-copy-service/recursive-copy.visitor.spec.ts
- apps/server/src/modules/board/service/board-do-copy-service/recursive-copy.visitor.ts
When ... a LinkElement
- copying: an existing preview-image needs to be copied, too and the internal imageUrl needs to get updated
- deleting: the file-storage needs to get informed, that associated files get deleted, too
- updating: nothing needs to be done regarding this bugfix.
- https://ticketsystem.dbildungscloud.de/browse/BC-5758
> BC-5758 - link element copy preview image

- ansible/roles/schulcloud-server-core/tasks/main.yml
- https://ticketsystem.dbildungscloud.de/browse/BC-4710
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4352
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/716
https://github.com/hpi-schul-cloud/tldraw-client/pull/25
> BC-4710 deployment Add when WITH_TLDRAW rule

- apps/server/src/modules/board/controller/card.controller.ts
- apps/server/src/modules/board/controller/dto/card/card.response.ts
- apps/server/src/modules/board/controller/dto/element/update-element-content.body.params.ts
- apps/server/src/modules/board/controller/element.controller.ts
- apps/server/src/modules/files-storage/service/files-storage.service.ts
Adding drawing missing types to course board controllers
https://github.com/hpi-schul-cloud/nuxt-client/pull/2934
> BC-4710 Add drawing element types

- apps/server/src/modules/h5p-library-management/service/h5p-library-management.service.spec.ts
https://ticketsystem.dbildungscloud.de/browse/BC-6072
> BC-6072 fixup h5p unit tests

- .github/workflows/clean.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-to-jira.yml
- .github/workflows/dependency-review.yml
- .github/workflows/migrations.yml
- .github/workflows/publish_pages.yml
- .github/workflows/push.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
- .github/workflows/test_unstable_e2e.yml
https://ticketsystem.dbildungscloud.de/browse/BC-5855
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4655
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3374
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/8
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/240
https://github.com/hpi-schul-cloud/nuxt-client/pull/2964
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/49
https://github.com/hpi-schul-cloud/version-aggregator/pull/16
> BC-5658 update gh-actions remove dof_bingo

- ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
change the call to the namespace activator to an internal one so we don't have the dependency on the domain here
https://ticketsystem.dbildungscloud.de/browse/BC-6088
> BC-6088 devcluster split preparation

- apps/server/src/modules/deletion/controller/api-test/deletion-request-create.api.spec.ts
> BC-6087 - fix unstable API tests

- backup/setup/migrations.json
- migrations/1703253259864-school-default-props.js
> BC-6111 -  default system and federal state

- ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-6136
> BC-6136 adapted if conditions accoding to BC-6088

- apps/server/src/modules/group/controller/api-test/group.api.spec.ts
- apps/server/src/modules/group/controller/dto/request/class-filter-params.ts
- apps/server/src/modules/group/controller/group.controller.ts
- apps/server/src/modules/group/uc/group.uc.spec.ts
- apps/server/src/modules/group/uc/group.uc.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1655
> N21-1655 Fix group timeout

- apps/server/src/modules/account/domain/account.ts
- apps/server/src/modules/account/repo/account.repo.integration.spec.ts
- apps/server/src/modules/account/repo/account.repo.ts
- apps/server/src/modules/account/repo/mapper/account-do-to-entity.mapper.spec.ts
- apps/server/src/modules/account/repo/mapper/account-do-to-entity.mapper.ts
- apps/server/src/modules/account/repo/mapper/account-entity-to-do.mapper.spec.ts
- apps/server/src/modules/account/repo/mapper/account-entity-to-do.mapper.ts
- apps/server/src/modules/account/services/account-db.service.spec.ts
- apps/server/src/modules/account/services/account-db.service.ts
- apps/server/src/modules/account/services/account.service.spec.ts
- apps/server/src/modules/account/services/account.service.ts
- apps/server/src/modules/account/services/account.validation.service.spec.ts
- apps/server/src/modules/account/services/account.validation.service.ts
- apps/server/src/modules/account/uc/account.uc.spec.ts
- apps/server/src/modules/authentication/strategy/local.strategy.spec.ts
- AccountRepo now uses Account DO instead AccountEntity for parameters and return values
- https://ticketsystem.dbildungscloud.de/browse/EW-742
> EW-742: AccountRepo refactoring

- apps/server/src/modules/server/server.config.ts
- config/default.schema.json
- config/test.json
https://ticketsystem.dbildungscloud.de/browse/BC-7028
> BC-7028 add description to allowed api keys

- apps/server/src/modules/learnroom/mapper/common-cartridge.mapper.spec.ts
- apps/server/src/modules/learnroom/mapper/common-cartridge.mapper.ts
- apps/server/src/modules/learnroom/service/common-cartridge-export.service.spec.ts
- apps/server/src/modules/learnroom/service/common-cartridge-export.service.ts
- apps/server/src/shared/testing/factory/domainobject/board/card.do.factory.ts
The common cartridge export was expanded to include rich text elements of the column board.
https://ticketsystem.dbildungscloud.de/browse/EW-798
> EW-798 expanded cc export of rich text elements of column board

- apps/server/src/infra/rabbitmq/exchange/files-preview.ts
- apps/server/src/infra/rabbitmq/exchange/files-storage.ts
- apps/server/src/infra/rabbitmq/index.ts
- apps/server/src/infra/rabbitmq/rabbitmq.config.ts
- apps/server/src/infra/rabbitmq/rabbitmq.module.ts
> BC-5661 - refactor RabbitMQ configuration

- apps/server/src/modules/provisioning/loggable/email-already-exists.loggable.spec.ts
- apps/server/src/modules/provisioning/loggable/email-already-exists.loggable.ts
- apps/server/src/modules/provisioning/loggable/index.ts
- apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-user-provisioning.service.spec.ts
- apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-user-provisioning.service.ts
- apps/server/src/modules/user/service/user.service.spec.ts
- apps/server/src/modules/user/service/user.service.ts
Refactors the provisioning of a user by checking if provided email is unique in SVS. If not throws a loggable and the login fails.
- https://ticketsystem.dbildungscloud.de/browse/N21-1888
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3444
> N21-1888- check email in provisioning

- ansible/roles/schulcloud-server-core/templates/board-collaboration-deployment.yml.j2
The Label app.kubernetes.io/component form the pod template form board-collaboration-deployment was set to the wrong value 
- https://ticketsystem.dbildungscloud.de/browse/BC-7337
> BC-7337 - fix label from pod template from board-collaboration-deployment

- apps/server/src/modules/account/domain/services/account.service.spec.ts
- apps/server/src/modules/account/domain/services/account.service.ts
Show an error notification to the user when the keycloak account could not be updated.
https://ticketsystem.dbildungscloud.de/browse/EW-863
> EW-863: Show error notification when account is not updated in keycloak

- apps/server/src/modules/board/gateway/api-test/board-collaboration.gateway.spec.ts
- apps/server/src/modules/board/gateway/board-collaboration.gateway.ts
Simplify all Failure-Action payloads to no longer carry ErrorType and BoardNodeType in order simplify failure-structure and to remove redundancy between action-name and carried data. This way refactorings on the backend-side are enabled
https://ticketsystem.dbildungscloud.de/browse/BC-7298
https://github.com/hpi-schul-cloud/nuxt-client/pull/3273
> BC-7298 - refactor failure actions

- apps/server/src/modules/board/gateway/board-collaboration.gateway.ts
- apps/server/src/modules/board/gateway/dto/create-card.message.param.ts
Fixing two bugs that were introduced with the implementation of websocket-communication for boards:
Problem 1:
When a new card gets created by clicking on the corresponding button, it gets created without an empty text field element.
Problem 2:
When the user hits enter key while being in a card title, a new text field element should be created at the beginning of the card and the cursor should jumo into it.
[BC-7583](https://ticketsystem.dbildungscloud.de/browse/BC-7583)
https://github.com/hpi-schul-cloud/nuxt-client/pull/3306
> BC-7583 - fix bugs in socket implementation

- ansible/roles/schulcloud-server-core/tasks/main.yml
Remove an double Ansible Job to apply the FileStorageDeployment 
- https://ticketsystem.dbildungscloud.de/browse/BC-7592
> BC-7592 - remove double FileStorageDeployment Ansible job

- apps/server/src/modules/board/gateway/board-collaboration.gateway.ts
- apps/server/src/modules/board/gateway/dto/index.ts
- apps/server/src/modules/board/uc/board.uc.ts
- apps/server/src/modules/board/uc/card.uc.spec.ts
- apps/server/src/modules/board/uc/card.uc.ts
- apps/server/src/modules/board/uc/column.uc.spec.ts
- apps/server/src/modules/board/uc/column.uc.ts
- apps/server/src/modules/board/uc/element.uc.spec.ts
- apps/server/src/modules/board/uc/element.uc.ts
- config/default.schema.json
Refactoring on the WebSocket-communication on the board:
Until now the BoardAuthorisableService was used to determine the root board of any action on the board.
Now, that the BoardDo contains its AncestorIds, this can be simplyfied by simply getting the rootId from the DO directly - reducing the amount of queries needed.
BC-7236
> BC-7236 - refactor how to get rootid in socket gateway

- backup/setup/classes.json
- backup/setup/schools.json
- test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
Adjusting new school year 24/25 to seed data and test
BC-6918
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/456
> BC-6918 - Adjusting new school year 24/25 to seed data and test

- ansible/roles/h5p-library-management/templates/api-h5p-library-management-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-delete-s3-files-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2
- ansible/roles/schulcloud-server-core/templates/tldraw-delete-files-cronjob.yml.j2
- ansible/roles/schulcloud-server-init/templates/job_init.yml.j2
- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
> BC-7676 Updated k8s jobs to run as non-root users where easily possible

- ansible/roles/moin-schule-sync/templates/moin-schule-users-deletion-queueing-cronjob-configmap.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-users-sync-cronjob-configmap.yml.j2
Fix missing ETHERPAD__PAD_URI in the configmaps from the moin.schule cronjobs
- https://ticketsystem.dbildungscloud.de/browse/BC-7696
> BC-7696 - fix configmaps for moin.schule CronJobs

- apps/server/src/modules/group/uc/class-group.uc.spec.ts
- apps/server/src/modules/group/uc/class-group.uc.ts
- apps/server/src/modules/school/domain/do/school-year.ts
- apps/server/src/modules/school/domain/do/school.ts
- apps/server/src/modules/school/domain/service/school.service.ts
- apps/server/src/modules/school/testing/school.factory.ts
https://ticketsystem.dbildungscloud.de/browse/N21-2095
> N21-2095-bugfix-class-creation-schoolyear

- ansible/roles/h5p-library-management/templates/api-h5p-library-management-cronjob.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-users-deletion-queueing-cronjob.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-users-sync-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-delete-s3-files-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/tldraw-delete-files-cronjob.yml.j2
- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
This work should randomize the timepoint for cronjobs to run. 
That should be help to decrease the amount of cron jobs who run at the same time and this should decrease the scale-up and scale-down rate for the kubernetes worker at least.
- https://ticketsystem.dbildungscloud.de/browse/BC-6938
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/921
> BC-6938 - randomize cronjob execution point 

- apps/server/src/modules/board/service/internal/column-board-copy.service.spec.ts
- apps/server/src/modules/board/service/internal/column-board-copy.service.ts
> BC-7794 - fix board link swap when copy course

- apps/server/src/shared/repo/mongo.patterns.ts
- apps/server/src/shared/repo/user/user.repo.integration.spec.ts
- apps/server/src/shared/repo/user/user.scope.spec.ts
- apps/server/src/shared/repo/user/user.scope.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2134
> N21-2134 bugfix missing users in migration wizard

- apps/server/src/modules/learnroom/controller/api-test/course.api.spec.ts
- apps/server/src/modules/learnroom/controller/course.controller.ts
- apps/server/src/modules/learnroom/controller/dto/course-cc-metadata.response.ts
- apps/server/src/modules/learnroom/mapper/course.mapper.ts
- apps/server/src/modules/learnroom/uc/course.uc.spec.ts
- apps/server/src/modules/learnroom/uc/course.uc.ts
In this ticket a new Get-API is provided to get specific metadata of a course that is needed for the Common Cartridge Export Microservice
https://ticketsystem.dbildungscloud.de/browse/EW-994
> EW-994 provided a new API to get course metadata by ID

- apps/server/src/modules/learnroom/controller/api-test/course.api.spec.ts
- apps/server/src/modules/learnroom/controller/course.controller.ts
In this ticket the path of the API get common cartridge metadata of a course by id was changed from /courses/:courseId to /courses/:courseId/cc-metadata
https://ticketsystem.dbildungscloud.de/browse/EW-1000
> EW-1000 renamed the get course by id API

- apps/server/src/core/error/loggable/axios-error.loggable.spec.ts
- apps/server/src/core/error/loggable/axios-error.loggable.ts
- apps/server/src/modules/oauth-provider/domain/error/hydra-oauth-failed-loggable-exception.spec.ts
- apps/server/src/modules/oauth/loggable/token-request-loggable-exception.spec.ts
- apps/server/src/modules/tool/external-tool/service/external-tool.service.ts
https://ticketsystem.dbildungscloud.de/browse/BC-5724
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/935
> BC-5724 improve logging

- apps/server/src/modules/account/domain/services/account.service.ts
- src/middleware/errorHandler.js
> BC-8054 - fix log of email from user

- ansible/roles/common-cartridge/templates/deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/admin-api-server-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/amqp-files-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-files-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-fwu-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/board-collaboration-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/preview-generator-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/tldraw-deployment.yml.j2
- ansible/roles/schulcloud-server-h5p/templates/api-h5p-deployment.yml.j2
- ansible/roles/schulcloud-server-init/templates/management-deployment.yml.j2
- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-worker-deployment.yml.j2
- ansible/roles/schulcloud-server-migration-system/templates/deployment.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-deployment.yml.j2
Add annotations to the kubernetes deployments so that they cann automaticly restart by the stakater reloader if configmaps or secrets change 
- hpi-schul-cloud/dof_app_deploy#981
- hpi-schul-cloud/schulcloud-client#3527
- hpi-schul-cloud/nuxt-client#3413
- hpi-schul-cloud/superhero-dashboard#267
- hpi-schul-cloud/shd-client#21
- hpi-schul-cloud/antivirus_check_service#64
- hpi-schul-cloud/schulcloud-calendar#164
- hpi-schul-cloud/version-aggregator#23
- hpi-schul-cloud/h5p-staticfiles-server#12
- hpi-schul-cloud/tldraw-server#20
- hpi-schul-cloud/tldraw-client#100
- https://ticketsystem.dbildungscloud.de/browse/BC-5112
> BC-5112 - add Annotations to deployment for Restart

- ansible/roles/common-cartridge/templates/external-secret.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-sync-external-secret.yml.j2
- ansible/roles/schulcloud-server-core/templates/admin-api-server-external-secret.yml.j2
- ansible/roles/schulcloud-server-core/templates/amqp-files-external-secret.yml.j2
- ansible/roles/schulcloud-server-core/templates/external-secret-admin-api-client.yml.j2
- ansible/roles/schulcloud-server-core/templates/external-secret.yml.j2
- ansible/roles/schulcloud-server-core/templates/tldraw-server-external-secret.yml.j2
To reduce the trouble by the lag of the nfs PVCs and mongo DB on dev thr we activate for dev THR the mode to use one mongodb replicaset for all.
- https://ticketsystem.dbildungscloud.de/browse/BC-8267
- hpi-schul-cloud/tldraw-server#24
- hpi-schul-cloud/dof_app_deploy#998
> BC-8267 - aktivate for dev thr only the one mongo cluster for all mode

- apps/server/src/modules/group/uc/class-group.uc.spec.ts
- apps/server/src/modules/group/uc/class-group.uc.ts
Within NBC classes are also known as groups. Within that setting, group belonging to the new RoomMember(ship) Entity are also shown there. As for now the business case, where and how to show these new groups is not finally decided, we should filter the classes/groups for only the class type and remove the ones, belonging to the new type rooms.
BC-8362
- filter groups for group type class status in BE
> BC-8362 - RoomMember groups are shown in class administration

- .github/workflows/push.yml
- hpi-schul-cloud/nuxt-client#3442
- hpi-schul-cloud/superhero-dashboard#269
- hpi-schul-cloud/schulcloud-client#3538
- hpi-schul-cloud/h5p-staticfiles-server#14
- hpi-schul-cloud/tldraw-client#111
- hpi-schul-cloud/schulcloud-server#5325
- hpi-schul-cloud/shd-client#33
- hpi-schul-cloud/antivirus_check_service#65
- hpi-schul-cloud/version-aggregator#24
- hpi-schul-cloud/schulcloud-calendar#165
- https://ticketsystem.dbildungscloud.de/browse/BC-8372
> BC-8372 - update trivy to an version who cann use the cache

- apps/server/src/shared/repo/teams/teams.repo.ts
only data that isnt subject to change should be
cached for langer than usual (1 sec by default)
BC-8398
> BC-8398 - remove teams cache

- apps/server/src/modules/board/board-collaboration.config.ts
- apps/server/src/modules/tldraw-client/interface/tldraw-client-config.interface.ts
- apps/server/src/modules/tldraw-client/service/drawing-element-adapter.service.spec.ts
- apps/server/src/modules/tldraw-client/service/drawing-element-adapter.service.ts
- apps/server/src/modules/tldraw-client/tldraw-client.config.spec.ts
- apps/server/src/modules/tldraw-client/tldraw-client.config.ts
- config/default.schema.json
if you do not pull the config to the forroot it does not get validated. if you config is not validated it gets to process.env as a fallback in process.env everything is a string, thus a thought to be boolean will be "false" resulting in if ("false") to be true
in this particular case, it was WITH_TLDRAW2 that lead to this issue
- https://ticketsystem.dbildungscloud.de/browse/BC-8510
> BC-8510 - Wrong handling of WITH_TLDRAW2 by ConfigModule

- apps/server/src/infra/etherpad-client/etherpad-client.adapter.spec.ts
- apps/server/src/infra/etherpad-client/loggable/etherpad-error-loggable-exception.ts
- apps/server/src/infra/etherpad-client/loggable/etherpad-server-error-exception.spec.ts
- apps/server/src/infra/etherpad-client/mappers/etherpad-response.mapper.ts
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1056
> BC-8531 add original error message to etherpad error

- apps/server/src/modules/school/api/dto/response/school-user.response.ts
- apps/server/src/modules/school/api/dto/response/school.response.ts
- apps/server/src/modules/school/api/mapper/school-user.response.mapper.ts
- apps/server/src/modules/school/api/mapper/school.response.mapper.ts
- apps/server/src/modules/school/api/test/school-users.api.spec.ts
- apps/server/src/modules/school/domain/do/school.spec.ts
- apps/server/src/modules/school/domain/do/school.ts
- apps/server/src/modules/school/repo/mikro-orm/mapper/school.entity.mapper.ts
Users are not able to add members to a room, if the database contains schools that have no federalState defined.
BC-8746
https://github.com/hpi-schul-cloud/nuxt-client/pull/3503
* required property **federalState** for **schools** is now optional
* pagination information is not any longer part of the getTeachersResponse
> BC-8746 - fix add members

- apps/server/src/modules/board/service/column-board.service.ts
- apps/server/src/modules/meta-tag-extractor/controller/dto/meta-tag-extractor.response.spec.ts
- apps/server/src/modules/meta-tag-extractor/controller/dto/meta-tag-extractor.response.ts
- apps/server/src/modules/meta-tag-extractor/controller/meta-tag-extractor.controller.ts
- apps/server/src/modules/meta-tag-extractor/service/meta-tag-external-url.service.ts
- apps/server/src/modules/meta-tag-extractor/service/meta-tag-extractor.service.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/meta-tag-extractor.service.ts
- apps/server/src/modules/meta-tag-extractor/service/meta-tag-internal-url.service.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/meta-tag-internal-url.service.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/abstract-url-handler.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/abstract-url-handler.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/board-url-handler.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/board-url-handler.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/course-url-handler.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/course-url-handler.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/lesson-url-handler.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/lesson-url-handler.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/task-url-handler.spec.ts
- apps/server/src/modules/meta-tag-extractor/service/url-handler/task-url-handler.ts
- apps/server/src/modules/meta-tag-extractor/types/meta-data.type.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2358
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3524
> N21-2358 Link elements display card title for board card links

- ansible/roles/common-cartridge/templates/deployment.yml.j2
- ansible/roles/h5p-library-management/templates/api-h5p-library-management-cronjob.yml.j2
- ansible/roles/media-licenses/templates/vidis-sync-cronjob.yml.j2
- ansible/roles/media-metadata-sync/templates/media-metadata-sync-cronjob.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-users-deletion-queueing-cronjob.yml.j2
- ansible/roles/moin-schule-sync/templates/moin-schule-users-sync-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/admin-api-server-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/amqp-files-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-files-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/api-fwu-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/board-collaboration-deployment.yml.j2
- ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob.yml.j2
- ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2
- ansible/roles/schulcloud-server-core/templates/preview-generator-deployment.yml.j2
- ansible/roles/schulcloud-server-h5p/templates/api-h5p-deployment.yml.j2
- ansible/roles/schulcloud-server-init/templates/job_init.yml.j2
- ansible/roles/schulcloud-server-init/templates/management-deployment.yml.j2
- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
- ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-worker-deployment.yml.j2
- ansible/roles/schulcloud-server-migration-system/templates/deployment.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-cronjob.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-deployment.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-init.yml.j2
- ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
- https://ticketsystem.dbildungscloud.de/browse/BC-8876
- hpi-schul-cloud/dof_app_deploy#1100
- hpi-schul-cloud/schulcloud-calendar#170
- hpi-schul-cloud/tldraw-server#52
- hpi-schul-cloud/antivirus_check_service#70
- hpi-schul-cloud/schulcloud-client#3577
- hpi-schul-cloud/nuxt-client#3530
- hpi-schul-cloud/superhero-dashboard#277
- hpi-schul-cloud/version-aggregator#28
- hpi-schul-cloud/tldraw-client#123
- hpi-schul-cloud/h5p-staticfiles-server#17
- hpi-schul-cloud/shd-client#40
> BC-8876 - set os filed for POD Templates from Deployments, CronJobs and Jobs

- apps/server/src/modules/provisioning/service/tsp-provisioning.service.ts
- apps/server/src/modules/user/domain/do/user.do.ts
- apps/server/src/modules/user/repo/mikro-orm/user-do.repo.ts
New TSP Sync now sets lastSyncedAt during syncs and ad hoc provisioning.
https://ticketsystem.dbildungscloud.de/browse/EW-1158
> EW-1158: New TSP Sync now sets lastSyncedAt.

- apps/server/src/modules/provisioning/service/tsp-provisioning.service.spec.ts
- apps/server/src/modules/provisioning/service/tsp-provisioning.service.ts
The consent creation for tsp users has been adjusted so that consent is created if user consent or parent consent is missing.
https://ticketsystem.dbildungscloud.de/browse/EW-1188
> EW-1188 Fix consent creation for tsp users

- apps/server/src/modules/room-membership/repo/entity/room-membership.entity.ts
When accessing the page "/rooms" the rooms which the user can access are loaded and filtered in the background. Within the process the `userGroupId` is requested, but this property does not have an index, which is the source of the "delay".
BC-9495
- set index in room membership on `userGroupId`
> BC-9495 - During first load the rooms page /rooms takes longer then expected

- apps/server/src/modules/board/domain/colum-board.do.ts
- apps/server/src/modules/board/service/board-node.service.spec.ts
- apps/server/src/modules/board/service/board-node.service.ts
When the "readers can edit" flag is set on a published (visible) board and said board is set to draft (invisible) the "readers can edit" flag is reset to false.
https://ticketsystem.dbildungscloud.de/browse/BC-10563
> BC-10563: Reset readersCanEdit flag when unpublishing a board

- src/services/wopi/hooks/index.js
for some reason the jwt may contain query parameters?! and this bug existed since its initial implementation with a hacky workaround
which is now just replaced with a more robust workaround
https://ticketsystem.dbildungscloud.de/browse/BC-10647
> BC-10647 libreoffice may not be able to access file via wopi
