hpi-schul-cloud/schulcloud-server

package.json, src/services/authentication/strategies/lernsax.js, test/services/authentication/lernsax.test.js
=> create lern sax login strategy

src/hooks/index.js, src/services/authentication/service.js, src/services/role/hooks/index.js, src/services/role/model.js, src/services/user/hooks/index.js, src/services/user/model.js, src/setupEnvironment.js
Reverts schulcloud/schulcloud-server#41
=> Revert "165 Refactor database calls"

package.json
feathers-configuration implemented a breaking change about choosing the path
=> Fix config path

package.json, src/services/index.js, src/services/link/hooks/index.js, src/services/link/index.js, src/services/link/link-model.js, test/services/link/index.test.js
Uses custom express middleware to redirect clients. Currently, any user can create a link
=> Implement URL shortener service

package.json, src/services/account/strategies/itslearning.js, src/services/helpers/service.js
This was due to the secrets missing in the CI environment. I added a fallback
=> 295 mail service test fails on travis

package.json, src/app.js
=> changed to pretty-error hiding path

LICENSE
=> use AGPL license

src/index.js
=> fix spelling

src/services/lesson/model.js
I will rename this endpoint in the next PR - but for now theses changes are required for the client to work: https://github.com/schul-cloud/schulcloud-client/pull/181
=> Smaller changes to lesson endpoint

package.json, src/app.js
=> override console outputs and add timestamp

src/services/content/index.js
=> fix copy and paste mistake

src/services/homework/model.js, src/services/lesson/index.js
paginate limit wurde erhöht um stets alle Kurse per ajax abfragen zu können.
=> 628 verknüpfung von aufgaben und kursen

src/services/lesson/hooks/index.js, src/services/lesson/model.js
https://github.com/schul-cloud/schulcloud-client/pull/364
=> 625 reihenfolge und gliederung in themen verändern

package.json, src/services/homework/hooks/index.js
I'm using new commands to not interfere with existing usage
coverage tests doesn't work on windows so only run mocha
I'm using GitHub for Desktop and added it to the path like I was told to
#165 (comment)
=> 770 server tests starten unter windows nicht

src/hooks/index.js
=> allow superhero to edit regardless of school

src/services/homework/hooks/submissions.js
=> 774-aufgaben-schüler-können-ihre-eigene-note-über-die-api-setzen

src/services/account/model.js, src/services/homework/hooks/index.js, src/services/user-group/hooks/index.js, test/services/account/moodle/moodle.test.js
frontend already converts username to lowercase, but usernames are not saved in db with lowercase.
Accounts which are saved with any upercase usernames will be manually changed afterwards.
=> save username always as lowercase

package.json, src/hooks/index.js, src/services/account/hooksCJWT/index.js, src/services/account/index.js
`/accounts/jwt/`
post with userId
need to have the role superhero at any position in the roles array
=> create the possibility to forge JWTs of users

backup/setup/accounts.json, backup/setup/classes.json, backup/setup/courses.json, backup/setup/homeworks.json, backup/setup/lessons.json, backup/setup/materials.json, backup/setup/news.json, backup/setup/roles.json, backup/setup/schools.json, backup/setup/submissions.json, backup/setup/users.json
closes https://github.com/schul-cloud/schulcloud-server/issues/247
=> add demo data and timestamps

src/services/homework/hooks/submissions.js
https://github.com/schul-cloud/schulcloud-client/pull/527
=> 869 refactor submissions server

src/services/helpers/service.js
use smtp, if smtp process env isset, otherwise use sendmail, also allow custom sender address
=> Update email settings

src/services/account/hooks/index.js, src/services/account/strategies/iserv.js
skip an edge case in the password verification, as the account has no userId yet.
=> SC-77 SSO edge case

README.md
Add some VisualStudioCode information for debugging in VSCode
=> Debugging in VSCode

src/services/fileStorage/proxy-service.js
=> SC-116 ~ umlaute erlauben file upload

src/services/homework/hooks/index.js, src/services/homework/hooks/submissions.js, src/services/homework/model.js
=> SC-14 ~ Verknüpfung von Gruppen und Team-Abgaben

package.json, src/hooks/index.js, src/services/homework/copy-service.js, src/services/user-group/hooks/index.js
fix that android shows every course of the school not just user ones
=> 172 fix android course listing 2

src/services/school/model.js
allows the use of {{ currentSchoolData.pilot }} or experimental in frontend to show or test specific features only for marked groups
=> introduce pilots and experimental schools

src/services/helpdesk/model.js
...to enable submits of "Technische Probleme" in "Probleme melden"
https://ticketsystem.schul-cloud.org/browse/SC-207
=> SC-207-fix-technical_problem-submit

package.json
inspect line for webstorm debugging
=> inspect line for webstorm debugging

package.json, src/services/index.js, src/services/socket/index.js
as soon as loggedin.hbs is loaded a websocket connects to the server and the server checks whether the user has seen the newest Release if so it will send a trigger to the client.
Can also be used for other things.
SC-8
=> use websockts for releases

src/services/fileStorage/docs/index.js, src/services/fileStorage/proxy-service.js, src/services/fileStorage/strategies/awsS3.js, src/services/fileStorage/strategies/interface.js, src/services/fileStorage/utils/filePermissionHelper.js, src/services/lesson/index.js
Copy Service implemented. Example json-body:
POST `/fileStorage/copy/`
```
{
oldPath: users/59ad4c412b442b7f81810285/,
newPath: courses/59a3cabaa2049554a93fec60/,
fileName: FylerSeite1.png
}
```
LessonsFile Service implemented
GET `/lesons/[...]/files?shareToken=[...]`
=> SC -57 ~ share topics with data

src/services/fileStorage/proxy-service.js, src/services/fileStorage/strategies/awsS3.js, src/services/fileStorage/utils/filePermissionHelper.js
Now it is possible to open external shared files. In past there was a 404 error (caused by a wrong schoolId -> wrong bucket).
=> SC-353 ~ Fix External Shared File View

src/hooks/index.js, src/services/user/hooks/registrationPins.js
Fixes some PIN misbehaviour, see commit message for more details
=> fix mailing, mailtext and optimize PINs

.gitignore, src/services/helpdesk/hooks/index.js, src/services/user/registration.js, test/app.hooks.test.js, test/services/helpdesk/index.test.js
Cherrypick Helpdesk into N21/main. Server code from #364 
Tests in Client Cherrypick PR [#899](https://github.com/schul-cloud/schulcloud-client/pull/899)
=> cherrypick new helpdesk server

src/services/helpdesk/hooks/index.js
Fixes SC-532
Belongs to [#910](https://github.com/schul-cloud/schulcloud-client/pull/910)
=> fixes bug from SC-532

src/services/helpdesk/hooks/index.js
Solves Issue [SC-576](https://ticketsystem.schul-cloud.org/browse/SC-576)
=> Helpdesk to JIRA, Instanz

src/services/analytics/index.js, src/services/analytics/model.js
related pr: https://github.com/schul-cloud/schulcloud-client/pull/933/
=> extend logging model by networkProtocol

src/services/user/hooks/index.js, src/services/user/model.js, test/services/user/unit.test.js
Backend Part
Possible ToDos (know and later): 
- let user deside his color from a given list
- list of colors from a global school wide theme
- fancy styled avatars
=> Support for simple Avatars

src/services/user-group/model.js
has no effect, since the color comes from the frontend anways... but it's the new default (grey) and should be reflected in backend
=> change default color of course

src/services/fileStorage/proxy-service.js, src/services/fileStorage/strategies/awsS3.js
https://ticketsystem.schul-cloud.org/browse/SC-665
=> S3 set correct fileName on download

src/hooks/index.js, src/services/lesson/hooks/index.js
Restrict find/get to users lessons with a global hook. Possible side effects on some functions so testing (Mocha, Postman, manually) is needed, see my first comment.
https://ticketsystem.schul-cloud.org/browse/SC-678
=> SC-678-fix find/get of lessons

src/services/sync/strategies/LDAPSystemSyncer.js
=> quick fix ldap sync limit

src/services/account/hooks/index.js, src/services/sync/strategies/CSVSyncer.js, src/services/user/hooks/index.js, test/services/account/index.test.js, test/services/helpers/testObjects.js, test/services/user/unit.test.js
ticket: https://ticketsystem.schul-cloud.org/browse/NC-112
related: https://ticketsystem.schul-cloud.org/browse/NC-141
=> [NC-112] case-sensitive emails

CODEOWNERS
Next steps:
- the @schul-cloud/data-protection team needs to have write permissions to the repository (I'm convinced that it has, but I don't know how to check that)
- code owner review must be enabled after this PR is merged (https://help.github.com/articles/enabling-required-reviews-for-pull-requests/)
=> SC-763 code owners

migrations/files.js, migrations/index.js, migrations/submissions.js
- Added robust errorhandling: the script will now exit even there were errors and will display these errors
- This will also fix SC-923 (https://ticketsystem.schul-cloud.org/browse/SC-923) for already migrated files as the access rights for the teacher responsible for the homework will be set
=> SC-868: Adjust migration script for submissions

src/services/link/index.js, src/services/user-group/hooks/index.js
This works now. Note that this wasn't a bugfix, I don't know how this was ever supposed to work.
Hint: passing query params in a PATCH request will result in mongoose-feathers in not updating anything. The DB query gets build from id and the query, which does not really makes sense when providing a unique id anyway.
=> enable students to join courses through link

src/services/homework/hooks/index.js
lines 163 - 182 is the fix.
frontend PR is linked below.
=> SC-901 allow students to archive / reactivate own homeworks

package-lock.json, src/services/ldap/hooks/index.js, src/services/ldap/index.js, src/services/sync/strategies/LDAPSystemSyncer.js, src/services/system/model.js
database changes in systems necessary before merge
=> SC-795 General LDAP-Self Service

src/services/user-group/hooks/index.js
https://ticketsystem.schul-cloud.org/browse/SC-983
@Parnswir Maybe we should discuss that on Monday. Fix is working but I don't like the way the classes are handled here.
=> [WIP] Sc 983 fix add tool removes all users from course

src/services/user/hooks/registrationPins.js
https://ticketsystem.schul-cloud.org/browse/SC-1042
=> PIN Mail Theming fixen

src/services/user/hooks/admin.js, src/services/user/index.js, src/services/user/services/AdminStudents.js, src/services/user/services/index.js
Client PR: https://github.com/schul-cloud/schulcloud-client/pull/1115
Der SuHe sieht jetzt auch nur noch die angefragte Schule.
=> Fix admin student view

src/services/analytics/index.js
this will disable logging to database until env variable will be set
=> requires ANALYTICS_LOGGING to be set for persist logging to db

src/services/fileStorage/utils/filePermissionHelper.js
https://ticketsystem.schul-cloud.org/browse/SC-1112
=> SC-1112: Fix permission check for submission files.

README.md
- N/A
- Begründung:
- Code
- Swagger
=> Update Readme Status Links

src/services/school/hooks/index.js
=> SC-1090 disable school remove route

.eslintci.json, .pullapprove.yml, .stickler.yml, .travis.yml, PULL_REQUEST_TEMPLATE.md, codecov.yml
- Begründung:
- Code
- Swagger
=> costumize codecov

.pullapprove.yml, PULL_REQUEST_TEMPLATE.md
---
labels: WIP
---
- Begründung:
- Code
- Swagger
=> full path to team name

src/services/user/services/AdminStudents.js, test/services/user/services/AdminStudents.test.js
- ~~Alle DB-Anpassungen müssen in den Seed-Daten reflektiert werden~~
- Begründung:
- Code
- Swagger
=> SC-1100 Fix class displayname in administration/student list

src/services/ldap/index.js
- Begründung:
- Code
- Swagger
=> Fix Issue Max Size in LDAP Search Collection

src/services/fileStorage/utils/filePermissionHelper.js
=> NC-227: Fix order of permission checks

package.json
- Begründung:
- Code
- Swagger
=> Update coverage for codecov to run only once

test/services/teams/hooks/helpers.test.js
- ~~Alle DB-Anpassungen müssen in den Seed-Daten reflektiert werden~~
- Code
- Swagger
=> SC-1143 Fix unstable unit test

.pullapprove.yml
Required is just one
But we have technical and non-technical people in this review group
- Begründung:
- Code
- Swagger
=> Request review from all privacy members

src/services/editor/services/Lesson.js, src/services/editor/services/Section.js
- Begründung:
- Code
- Swagger
=> EDTR-78 section save fixes

test/jobs/rss-news/index.integration.test.js
=> Fix rss tests to unblock PRs

PULL_REQUEST_TEMPLATE.md
Migrationsskript etwas prominenter erwähnt, damit es wahrgenommen wird
- Begründung:
- Code
- Swagger
=> SC-1188 Wording Anpassung

Dockerfile
Docker containers can be given health checks. If timeouts occur on client because the server is stuck and the process is still running, a restart can be triggered. /etc/localtime does not work reliably everywhere and is replaced by the complete tzdata package.
- Begründung:
- Code
- Swagger
Weitere Informationen zur DoD [hier im …
=> curl for health checks and tzdata for correct time zone

src/services/teams/index.js
- Begründung:
- Code
- Swagger
=> fix team emails

src/services/rocketChat/hooks/index.js, src/services/rocketChat/index.js
- ~[ ] Links zu verwandten PRs anderer Repositories~
- ~[ ] Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-????~
- Begründung:
- Code
- Swagger
=> rocketchat-ensure-user-in-channel

package.json, src/app.js, src/middleware/handleResponseHeaders.js, src/services/fileStorage/hooks/index.js, src/services/wopi/hooks/index.js, src/services/wopi/index.js, src/services/wopi/utils/filePostActionHelper.js, src/services/wopi/utils/hostCapabilitiesHelper.js, test/services/wopi/index.test.js
- Begründung:
- Code
- Swagger
=> Fix wopi bug

src/services/fileStorage/proxy-service.js
[SC-1246](https://ticketsystem.schul-cloud.org/browse/SC-1246)
- Begründung:
- Code
- Swagger
=> SC-1246-fix-move-file-to-personal-files

src/services/teams/hooks/index.js, test/services/helpers/testObjects.js, test/services/teams/index.test.js
Dieser PR entfernt einen unnötigen Check, der verhindert, dass Superheroes Teams erstellen können. Mit diesen Changes ist dies möglich. Aktionen im Team sind auch alle möglich bis auf News erstellen. Dafür bräuchte der Superhero die nötige Permission.
- Code
- Swagger
=> SC-1036 Teams als SuperHero erstellen

src/services/teams/hooks/index.js
- Begründung:
- Code
- Swagger
=> SC-832 enable pagination in teams

test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-1199
=> [SC-1199] Do not skip tests

src/services/rocketChat/index.js
- ~[ ] Links zu verwandten PRs anderer Repositories~
- Begründung:
- Code
- Swagger
=> make teamadmins and owners moderators

.pullapprove.yml
- Begründung:
- Code
- Swagger
=> add PR comment after review

.pullapprove.yml
- Begründung:
- Code
- Swagger
=> Update PR comment after review

.pullapprove.yml
New text for approved PRs with link to review guide
=> link review guide

src/services/helpers/service.js
this resolves mails sent to helpdesk when running tests and simplifies reading email content in development mode.
requires `NODE_ENV` is set to `production` in running systems to enable mailing
- Begründung:
- Code
- Swagger
=> if not in production, print email messages on console only.

PULL_REQUEST_TEMPLATE.md
- Begründung:
- Code
- Swagger
=> Fix typo in PR Template

src/services/user/hooks/index.js, src/services/user/index.js, src/services/user/services/AdminUsers.js, src/services/user/services/UserLinkImportService.js, src/services/user/services/index.js
Ein bisschen linter und outsourcing.
Der eigentlich fix ist der letzte commit https://github.com/schul-cloud/schulcloud-server/pull/640/commits/4c69dc74035986d289d55be3b81fe0e246182272
=> SC-1397-Einstellung-Sichtbar-für-Teameinladungen

src/services/account/strategies/itslearning.js, src/services/fileStorage/strategies/awsS3.js
* fix aws s3 promisify error
* add yarn.lock (see previous commit)
* correction of secrets import
* linting
* revert yarn file changes
* revert package lock file changes
* lint
* fix itslearning promisifies
* lint
- Begründung:
- Code
- Swagger
Weitere Informationen zur DoD [hier im …
=> Fix aws s3 promisify (#657)

.travis.yml, package.json
- Begründung:
- Code
- Swagger
=> Switch back to codecov

.pullapprove.yml
- Begründung:
- Code
- Swagger
=> Should fix of missing privacy group review

src/app.js
requires KEEP_ALIVE to be set in boss env
=> set keep alive response header

src/services/sync/strategies/CSVSyncer.js, test/services/helpers/services/classes.js, test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js, test/services/sync/strategies/CSVSyncer/CSVSyncer.unit.test.js, test/services/sync/strategies/CSVSyncer/helper.js
Ein paar nötige Refactorings als Vorbereitung für [SC-1111](https://ticketsystem.schul-cloud.org/browse/SC-1111) und weitere Tickets. *Teil* von [SC-767](https://ticketsystem.schul-cloud.org/browse/SC-767).
=> [SC-767] refactor csv importer & consolidate its test helpers

src/services/link/index.js
-~ [ ] Links zu verwandten PRs anderer Repositories~
-~ https://github.com/schul-cloud/schulcloud-client/pull/????~
- Begründung:
- Code
- Swagger
=> dont overwrite importhashs that already exist

src/services/fileStorage/proxy-service.js, src/services/fileStorage/utils/filePermissionHelper.js, src/services/helpers/scopePermissions/index.js, src/services/teams/index.js
- Begründung:
- Code
- Swagger
=> add proof of concept for find files

migrate.js, migrations/template.js, package-lock.json, package.json, src/utils/database.js
* Neue Migration anlegen: `$> ./node_modules/.bin/migrate create EinEindeutigerName` => `Created migration EinEindeutigerName in ./migrations. Migration created. Run mongoose-migrate up EinEindeutigerName to apply the migration.`
* Migration(-en) ausführen: `$> ./node_modules/.bin/migrate up [optionalerName]`
* Migration zurückrollen: `$> ./node_modules/.bin/migrate down NameDerMigration`
- Gibt es ein Migrationsskripte? 😸 
- neue Abhängigkeit: `migrate-mongoose`
- Code
=> [SC-1333] useful DB migrations

deploy.sh
The Commit-SHA is desired. Should then be found under https://api.../commitsha.txt
- Begründung:
- Code
- Swagger
=> mit commitsha

package-lock.json, package.json, src/app.js, src/services/index.js, src/services/version/index.js
=> version route added as service

src/services/fileStorage/proxy-service.js
-~~ [ ] Links zu verwandten PRs anderer Repositories~~
~~ - https://github.com/schul-cloud/schulcloud-client/pull/????~~
- Begründung:
- Code
- Swagger
=> fix teams without files

deploy.sh
replaced autodeploy by chat message to #deployment
=> Disable prod auto deployment

src/services/ltiTool/model.js
Dieser PR fügt den Permissions-Typ "pseudonymous" dem DB-Model hinzu, wodurch theoretisch Pseudonyme für die Authentifizierung bei Drittanbieter-Tools genutzt werden können.
- [x ] Links zu verwandten PRs anderer Repositories
- [ x] Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-????
- [x ] Code mit Hinblick auf Security und Datensicherheit betrachten
- [x ] Linter darf keine Probleme bei veränderten Dateien aufweisen
- [ x] Kern-Logik ist hinter der API implementiert?
- [x ] Test-Coverage darf durch PR nicht sinken
- [x ] Unit-Tests und …
=> Add "pseudonymous" as permission type for ltitools

.dockerignore
=> ignore node modules in dockerignore

src/services/school/hooks/index.js, src/services/school/logic/year.js, test/services/school/year.logic.test.js
=> add schoolYear support for get school method

backup/setup/migrations.json, migrations/1562595327050-AddPositionToLessons.js, migrations/1563351138480-addStartAndEndDateToYearCollection.js, migrations/helpers/DatabaseTaskTemplate.js
=> Fix helper to handle empty values.

migrations/1562847510503-lessonIsCopyFrom.js
=> fix migration helper

src/services/rocketChat/helpers.js, src/services/rocketChat/index.js, test/services/rocketChat/helpers.test.js
- Begründung:
- Code
- Swagger
=> Sc 1514 fix regex

src/services/fileStorage/hooks/resolveStorageType.js
Fix that share lessons, will work too.
=> SC-1329 share lessons

src/services/school/logic/year.js, src/services/sync/strategies/LDAPSchoolSyncer.js, src/services/sync/strategies/LDAPSyncer.js
Diverse Bugfix für LDAP Schuljahreswechsel
=> Fixes für LDAP-Schuljahreswechsel

src/logger/index.js, src/services/fileStorage/strategies/awsS3.js, src/services/fileStorage/utils/copyFile.js, src/services/lesson/hooks/copy.js, src/services/lesson/index.js, src/services/user-group/services/course-copy-service.js
- https://github.com/schul-cloud/schulcloud-client/pull/1329
- https://ticketsystem.schul-cloud.org/browse/SC-1744
=> SC-1744 Fix copy course and lessons

src/logger/index.js
Related to : https://github.com/schul-cloud/schulcloud-server/pull/734
But with develop as base branch. The other PR is still open, for looking conversations. Please close and delete it, after this is merged.
=> add env variable LOG_LEVEL

package.json, src/services/user-group/services/courseScopeLists.js
=> SC-1757 display course  with null

src/services/me/index.js
- https://github.com/schul-cloud/nuxt-client/pull/230
=> add schoolName to /me route

src/services/user/hooks/index.js, src/services/user/registration.js
- https://github.com/schul-cloud/schulcloud-client/pull/1352
- Begründung:
- Code
- Swagger
=> flexibles mindestalter für consents ohne Eltern fixes

src/hooks/index.js, test/services/school/maintenance.integration.test.js
Der Code sollte sich niemals für einen Test anders verhalten.
- Begründung:
- Code
- Swagger
=> no changed behavior on test env

test/services/teams/helper/helper.user.js
Fix für lokale tests (wenn TEST_PW und TEST_HASH nicht gesetzt sind). Ohne Ticket.
=> Fix logger objects being used as passwords

package.json
- Begründung:
- Code
- Swagger
=> Let Greenkeeper create PRs for mongoose updates

src/services/account/hooks/index.js, src/services/passwordRecovery/index.js, src/services/user/firstLogin.js
- Begründung:
- Code
- Swagger
=> SC-1759 - Disallow password editing without old password

package-lock.json, package.json, src/app.js, src/helper/version.js, src/services/version/index.js
set `SENTRY_DSN` to `https://ddbf596711d84a2bb3f927281e978b2e@sentry.schul-cloud.dev/4` will report errors to sentry
=> Add sentry error reporting

backup/setup/roles.json, migrations/1568021901926-AddCourseRoles.js, src/services/helpers/scopePermissions/index.js, src/services/role/services/permissions.js, src/services/user-group/index.js, src/services/user-group/services/coursePermission.js, test/services/courses/services/coursePermission.test.js
* neue Kursrollen, die im Kurs-Scope verwendet werden, um Berechtigungen für die Kursteilnehmer zu bestimmen (Migration notwendig)
* zusätzliche Berechtigungen für Lehrer und Vertretungslehrer in Absprachen mit @CordlessWool 
* Anpassung der bestehenden Tests
- Gibt es ein Migrationsskripte? ja
- Code
=> [SC-2012] add admin and superhero to course scope permissions

src/services/ldap/strategies/general.js
- https://github.com/schul-cloud/schulcloud-client/pull/1409
- Begründung:
- Code
- Swagger
=> Possibility to use several user paths for general ldap

src/services/user-group/hooks/index.js
- https://github.com/schul-cloud/schulcloud-client/pull/1410
- Begründung:
- Code
- Swagger
=> SC-2123 | removed limit of courses displayed

src/app.hooks.js, src/services/authentication/logic/index.js
=> fix authentication logic

src/services/fileStorage/utils/filePermissionHelper.js
Quickfix until scope rewrite comes along...
=> SC-2299 Fix permission check on homework submissions for co- and subst-teachers

src/services/user-group/hooks/classes.js
- https://github.com/schul-cloud/schulcloud-client/pull/1428
- Begründung:
- Code
- Swagger
=> SC-1976 | removed limit of classes displayed

src/services/rocketChat/services/rocketChatChannel.js
=> SC-2362 TypeError: logger.warn is not a function

.travis.yml, package-lock.json
```bash
curl https://gist.githubusercontent.com/schul-cloud-bot/a849c38804174f99ca7818782bf03c00/raw/index.sh > integration-test.sh
chmod 700 integration-test.sh
bash integration-test.sh
```
=> cleanup travis configuration + integration tests

src/app.js
=> fix sentry url obfuscation

.travis.yml
- Just a small change to skip the install of all the node stuff. 
https://docs.travis-ci.com/user/languages/minimal-and-generic/
=> use "generic" image for deployments

src/jobs/rss-news.js
return code >0 if something fails
continue if a school or a single job fails too loop always through all jobs/schools
enhanced logging details to easily find errors
=> catch rss feed update and schools by each other

config/globals.js, package.json, src/services/calendar/index.js, src/services/content/index.js, src/services/ldap/strategies/iserv.js, src/services/ldap/strategies/univention.js, src/services/notification/index.js, src/services/rocketChat/helpers.js
=> hotfix/SC-2984 Add global request timeout and set it to 8sec.

src/services/user/registration.js
https://ticketsystem.schul-cloud.org/browse/SC-3058
enhanced error reporting to get more information about this error
=> SC-3058 extended error logging on account creation

package-lock.json, package.json
=> Update chalk to ^3.0.0

src/services/fileStorage/strategies/awsS3.js, src/services/fileStorage/utils/filePathHelper.js
=> SC 1621 storage file name

config/default.json, config/globals.js, config/test.json, package-lock.json, package.json, src/services/helpers/service.js, test/services/helpers/service.test.js
- Folgeticket: https://ticketsystem.schul-cloud.org/browse/SC-3105
=> implement new notification service for mail handler

src/services/helpers/service.js, test/services/helpers/service.test.js
- benötigt, damit im hilfebereich dateien angehangen werden können
- https://github.com/schul-cloud/node-notification-service/pull/95
- Begründung:
- Code
- Swagger
=> Feature/SC-3105 - fix mail attachments

src/services/authentication/index.js, src/services/authentication/strategies/TSPStrategy.js, src/services/authentication/strategies/index.js
- Begründung:
- Code
- Swagger
=> WIP: Add TSP Auth Strategy

test/services/helpers/service.test.js
- this adds an assertion to check that the expects in the callback were actually executed
=> assert that notification service was actually called in tests

src/middleware/errorHandler.js
=> Remove jwt in login errors.

src/utils/sanitizeHtml.js
- Begründung:
- Code
- Swagger
=> SC-2941-allow-sub-sup-tags

src/services/fileStorage/strategies/awsS3.js
- https://github.com/schul-cloud/schulcloud-client/pull/1576
=> BooleanValue to trigger PDF preview

src/middleware/errorHandler.js
=> add secret keys

src/app.hooks.js
- Adds a simple blacklist for paths to be ignored by the auto-logout feature.
- Adds the `authentication` route to this list to enable login with an existing (expired) jwt (e.g. with SSO)
=> SC-3331 Auto-logout blacklist

package-lock.json, package.json
=> Update simple-oauth2 to ^3.0.0

src/services/school/hooks/index.js, test/services/school/index.test.js
- Begründung:
- Code
- Swagger
=> allow superheroes to patch schools

package-lock.json, package.json, src/hooks/index.js, src/services/helpdesk/hooks/index.js, src/services/helpers/service.js
=> 22.1.4 SC-3381 update from in emails for helpdesk 

src/services/statistic/index.js
Extended stats (no UI) for reporting needs
- Begründung:
- Code
- Swagger
=> Add more Stats for files

package-lock.json, package.json, src/services/authentication/strategies/TSPStrategy.js
Updates jose and verifies TSP ticket signatures (which is now possible, because the library doesn't enforce strict base64url encoding anymore)
=> SC-3067 verify tsp signature

package-lock.json, package.json
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-3338
=> SC-3338 Remove unused dependencies

package-lock.json, package.json, src/services/sync/strategies/TSP/TSPSchoolSyncer.js, src/services/user/services/AdminUsers.js
- internally created class without users work fine @tofixx 
And: check other administration pages to handle this issue correctly too...
=> SC-3530 fix useradministration with classes having no users 

src/logger/index.js, src/services/authentication/strategies/TSPStrategy.js, src/services/sync/logger.js, src/services/sync/strategies/Syncer.js, src/services/sync/strategies/TSP/TSP.js, src/services/sync/strategies/TSP/TSPBaseSyncer.js, src/services/sync/strategies/TSP/TSPSchoolSyncer.js, src/services/sync/strategies/mixins/ClassImporter.js, test/services/helpers/services/schools.js, test/services/sync/strategies/TSP/TSP.integration.test.js, test/services/sync/strategies/TSP/TSP.unit.test.js
- Creates users from login ticket if they don't exist (instead of triggering a costly sync)
- Starts an asynchronous sync for updating classes
- adds config validation for TSPSchoolSyncer
- adds lastChange parameter to TSPSchoolSyncer to limit TSP API request size and implements small changes in the ClassImporter mixin to update classes accordingly
- fixes Syncer-sub-class log level
- unit tests by @Ojself ❤️ 
- Code
=> SC-3306 Reworked TSP login

src/services/authentication/strategies/TSPStrategy.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-3667
somewhat related to https://github.com/schul-cloud/schulcloud-client/pull/1668
- more validation of required attributes
- better error messages
- less verbose logging
=> SC-3667 Validate attributes and improve error messages for TSP login

config/default.schema.json, package-lock.json, package.json, src/services/user/hooks/registrationPins.js, src/services/user/registration.js, test/services/account/index.test.js, test/services/helpers/registration.test.js, test/services/user/unit.test.js
See https://ticketsystem.schul-cloud.org/browse/SC-3635 for what this does
this relates to client pr https://github.com/schul-cloud/schulcloud-client/pull/1670
=> Pin Registration SC-3635

PULL_REQUEST_TEMPLATE.md
=> Added PR items for performance

backup/setup/migrations.json, migrations/1584966605306-runIndexSync2.js, package-lock.json, package.json, src/services/homework/hooks/submissions.js, src/services/homework/model.js, src/services/user-group/model.js
add homework submission course comment index
=> 22.6.2 index optimization

migrations/1585056558218-update schema indexes.js, package-lock.json, package.json, src/services/user-group/model.js
update course indexes, re-run index updates from previous migrations due to missing awaits
=> 22.6.3 fix indexes for courses

src/utils/redis.js
for invalid jwt, the object destructuring fails
before: (unhandled error in client)
now:
=> SC-3678 handle invalid jwt

package-lock.json, package.json, src/services/account/hooks/index.js, src/services/user/hooks/index.js
- disabled patch on account/user for demoUsers
- Links zu verwandten PRs anderer Repositories:
schul-cloud/schulcloud-client#1698
=> Hotfix 22.6.4 | disabled patch on account/user for demoUsers

src/services/homework/hooks/index.js
- https://github.com/schul-cloud/schulcloud-client/pull/1712
- Begründung:
- Code
- Swagger
=> SC-3791 | dashboard rework homeschooling

deploy.sh
Only for deployment on test.schul-cloud.org
=> gitflow-feature-stash: fix-test-deployment

src/services/user-group/index.js, src/services/user-group/services/courses.js, src/utils/index.js, src/utils/modelServices.js, test/services/user-group/services/courseModelService.test.js, test/services/user-group/services/courses.test.js
- Begründung:
- Code
- Swagger
=> implement initial course tests

CHANGELOG.md, backup/setup/migrations.json, backup/setup/users.json, migrations/1585665498001-add_edtr_feature_to_klara_fall.js
=> added feature flag to klara.fall

backup/setup/migrations.json
=> gitflow-feature-stash: fix_migration.json

config/globals.js
add missing db username and password to globals
=> database auth fix

package-lock.json, package.json, src/services/user/hooks/publicTeachers.js
=> hotfix 22.9.5

src/services/content/hooks/index.js
Disallow unused routes for better logging
=> Disallow unused routes

package-lock.json, package.json
general dependency update
- added missing peers: source-map-support, ts-node, typescript
- sort dependencies in package file
- npm audit fix
=> add missing peers, sort dependencies, audit fix

README.md
These are just a few tiny updates on the README, applying consistent formatting and fixing a couple of typos. 🤓 
I am unsure about what to do with the checklist below. Please let me know if I can/should act on any of these. Thank you. 🙂 
- Begründung:
- Code
- Swagger
Weitere Informationen zur DoD [hier im …
=> Update README, format & fix typos

CHANGELOG.md, package-lock.json, package.json, src/services/authentication/strategies/ApiKeyStrategy.js
- Begründung:
- Code
- Swagger
=> fix api-key-strategy with queryparams

.travis.yml
Related to #1191. 
_To be sure this condition properly works, we should double-check that once this PR is merged, the deploy job is run from the `develop` branch of this repo._
- Begründung:
- Code
- Swagger
=> Do not deploy forks via Travis CI

README.md
We had to do a little bit of digging when first setting up the project so I figured it'd be helpful to give hints on the desired versions in the `README.md`. ✌️
=> Add Node.js and MongoDB version hints to README

CHANGELOG.md, src/services/user/hooks/userService.js, src/services/user/services/userService.js, test/services/user/hooks/userService.hooks.test.js
Reverts schul-cloud/schulcloud-server#1163
=> Revert "feature/SC-4008 - migrate generateRegistrationLink to server"

.editorconfig, .pullapprove.yml, codecov.yml
- Begründung:
- Code
- Swagger
=> Fix YAML file formatting

backup.sh, deploy.sh, startup.sh
These scripts contained mixed whitespace (tabs & spaces). This adjusts them to use tabs throughout as specified by the `.editorconfig`. ✨ 
- Begründung:
- Code
- Swagger
=> Fix whitespace in shell scripts

src/services/account/index.js, src/services/homework/hooks/submissions.js, src/services/rocketChat/randomPass.js, src/services/user/registration.js, src/services/user/services/SkipRegistration.js, test/services/content/content.test.js, test/services/teams/hooks/collection.test.js
Based on #1206 
Fix:
- `no-void`
- `no-useless-escape`
- `no-plusplus`
- `no-restricted-properties`
- … (more as per commit messages)
- Begründung:
- Code
- Swagger
=> Fix further lint issues

config/globals.js, src/app.js, src/index.js
The test output was cluttered with `console.debug` output which created a lot of noise and broke the output of the test runner/reporter.
=> Fix test output

.github/PULL_REQUEST_TEMPLATE.md
=> Fix PR template typos

CHANGELOG.md, src/services/fileStorage/utils/filePermissionHelper.js, src/services/homework/hooks/index.js, src/services/homework/model.js, test/services/helpers/services/files.js, test/services/helpers/services/index.js, test/services/helpers/testObjects.js, test/services/homework/submissionService.test.js
Part 1 of [SC-4064](https://ticketsystem.schul-cloud.org/browse/SC-4064)
Client PR: https://github.com/schul-cloud/schulcloud-client/pull/1776
- Add gradeFileIds to submission, so that a teacher can upload e.g. commented pdf files
- Add a file-object factory to the test helpers
- Begründung:
- Code
- Swagger
Weitere Informationen …
=> [#SC-4064] Aufgaben feedback mit files erweitern (1/4)

CHANGELOG.md, package-lock.json, package.json, src/services/user/services/AdminUsers.js, test/services/user/services/AdminUsers.test.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-4389
=> [Hotfix] SC-4389 - fixed pagination for students/teacher table

src/services/user/services/AdminUsers.js, test/services/homework/submissionService.test.js
https://github.com/schul-cloud/nuxt-client/pull/971
=> SC-3513 - fixed sorting for classes column

src/services/consent/model.js
https://ticketsystem.schul-cloud.org/browse/SC-4045
Add an enum to narrow the type of consent.source.
=> SC-4045 Created enum for type of consent.source

src/services/school/hooks/index.js, test/services/school/index.test.js
Fix bug with multiple error messages for get not paginated schools.
- https://ticketsystem.schul-cloud.org/browse/SC-4335
=> SC-4335 Fix bug with school result pagination

config/default.json, config/default.schema.json
Change default value for STUDENT_TEAM_CREATION to opt-out
https://github.com/schul-cloud/schulcloud-client/pull/1839
https://ticketsystem.schul-cloud.org/browse/SC-4075
=> SC-4075 change default value for STUDENT_TEAM_CREATION to opt-out

src/hooks/index.js, src/services/helpdesk/hooks/index.js, src/services/helpers/service.js, test/services/helpers/service.test.js
https://ticketsystem.schul-cloud.org/browse/SC-4291
With this PR the e-mail address of the help desk ticket sender is not set as the senders address.
The reason for that is that the mail server only accepts e-mails, that has been verified (practically only e-mails *@schul-cloud.org would be accepted)
=> SC-4291 Remove overwriting from-address in the helpdesk e-mail

package-lock.json, package.json, src/services/fileStorage/proxy-service.js
=> hotfix 23.1.5

src/middleware/errorHandler.js
https://ticketsystem.schul-cloud.org/browse/SC-4552
https://ticketsystem.schul-cloud.org/browse/SC-4553
=> SC-4552 Fix server logs showing sensitive data

CHANGELOG.md, package-lock.json, package.json, src/services/link/index.js
This PR removes the shortlink generation of registration links. New registration links are no more shortened. Further cleanup happens in SC-4606.
https://ticketsystem.schul-cloud.org/browse/SC-4720
=> Hotfix/23.2.1 SC-4720 SC-4606 Remove ShortLinks-Service from registrastion links

config/default.schema.json, package-lock.json, package.json, src/services/etherpad/hooks/Pad.js
=> fix missing env

src/app.js
https://ticketsystem.schul-cloud.org/browse/SC-3926
=> SC-3926 remove x-powered-by header

src/services/rocketChat/services/rocketChatUser.js
- https://ticketsystem.schul-cloud.org/browse/SC-4924
=> dont join defaultchannels

compose-server-test.dummy
change content url in test compose file
=> change content url

src/services/user/firstLogin.js, test/routes/whitelist.js
=> Fix broken test

src/services/me/index.js
accountId was overwritten by the user object. AccountId is now added afterwards.
=> SC-4520 - fix small bug in me service

src/services/edusharing/logic/connector.js
=> SC-5057: fixed edu-sharing cookie expired

src/services/user/utils/consent.js
- https://ticketsystem.schul-cloud.org/browse/SC-5448
=> fix error when parentConsents undefined

CHANGELOG.md, package-lock.json, src/services/sync/strategies/CSVSyncer.js, test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Makes the CSV-Import work, even if there are whitespaces in the column-names (first line).
https://ticketsystem.schul-cloud.org/browse/SC-5250
Adds a .trim() to the code, where the column-names are used.
=> SC-5250 - adds a trim to the column-names of the csv

src/services/user/model/consent.schema.js
https://ticketsystem.schul-cloud.org/browse/SC-4970
=> SC-4970 Add consent source to user consent

deploy.sh
Teams 6 and 7 requested hotfix instances which were deployed. Changes were made to deploy.sh to accomodate new instances.
- https://ticketsystem.schul-cloud.org/browse/OPS-912
- https://ticketsystem.schul-cloud.org/browse/OPS-913
=> include team 6 and 7 hotfix instances

.mergify.yml
add label to auto update the pull request, should not work on the change request
=> try mergify auto update pull requests

CHANGELOG.md, package-lock.json, package.json, src/services/school/logic/year.js
… the date for creating classes
https://ticketsystem.schul-cloud.org/browse/SC-5883
=> SC-5888 fix: Choose current schoolyear based on the school

CHANGELOG.md, package-lock.json, package.json, src/services/ldap/index.js
https://ticketsystem.schul-cloud.org/browse/SC-5917
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2049
=> SC-5917 Fix bug in LDAP activation

config/default.schema.json, src/middleware/errorHandler.js
[Ticket SC-5820](https://ticketsystem.schul-cloud.org/browse/SC-5820)
Changed if statement from 'istanceof' to 'foo === bar'
**NB!**
"SILENT_ERROR_ENABLED" has been set to default `false`
=> add new conditional for error-name

src/services/edusharing/logic/connector.js
Edusharing authentication issues
=> SC-6091 authentication retry edusharing. More specific error codes

src/services/edusharing/logic/connector.js
=> SC-6122 preload edu sharing images

src/services/user/services/AdminUsers.js, src/services/user/utils/aggregations.js
The class maintenance screen could no be open because the old consent route shall no longer be used to retrieve user consents. The new user/admin/students route should be used instead.
I've extended the route so it is possible to filter by user Ids. (the existing filters stays unchanged i.e. the users list is going to be narrowed down to the current user school)
https://ticketsystem.schul-cloud.org/browse/SC-6248
=> SC-6248 extends the admin student route

backup/setup/migrations.json, migrations/1597654308406-remove-importHashes-from-users-with-accounts.js, package-lock.json, package.json, src/services/user/registration.js
https://ticketsystem.schul-cloud.org/browse/SC-6074
=> SC-6074 Improve logging of errors in registration

src/services/user/services/AdminUsers.js, src/services/user/utils/aggregations.js
A follow up fix for SC-6248 to avoid foreach on undefined error.
https://ticketsystem.schul-cloud.org/browse/SC-6248
=> SC-6248 Further fix for find consents

package-lock.json, package.json, src/services/authentication/strategies/TSPStrategy.js, src/services/sync/strategies/TSP/TSP.js, src/services/sync/strategies/TSP/TSPSchoolSyncer.js
*Ticket:* https://ticketsystem.schul-cloud.org/browse/SC-5983
*Client PR:* https://github.com/hpi-schul-cloud/schulcloud-client/pull/2090
=> Hotfix SC-5983 Rework TSP consent process

CHANGELOG.md, backup/setup/migrations.json, backup/setup/schools.json, migrations/1598266672663-setStudentListSettingsInSchoolsToFalse.js, package-lock.json, package.json
- https://ticketsystem.schul-cloud.org/browse/SC-6328
=> hotfix/24.4.5/SC-6328/ add migration to set StudentList Settings in schools to false

.github/workflows/migrations.yml, backup.js, backup/setup/migrations.json, package.json
This PR cleans up migrations which are out of sync between file system and migrations.json (dump) and adds a GitHub action that ensures that in future.
Data-Security hint: there were only formatting changes
https://ticketsystem.schul-cloud.org/browse/SC-6351
=> SC-6351 verify migrations

src/services/user/services/AdminUsers.js
- https://ticketsystem.schul-cloud.org/browse/SC-6484
=> SC-6484 remove default current date birthday

src/services/user/services/AdminUsers.js
Added sendRegistrationLink to create's method after hooks.
https://ticketsystem.schul-cloud.org/browse/SC-6594
=> SC-6594 - add sendregistrationlink hook

test/services/user/services/AdminUsers.test.js
Add tests for route security.
Origin ticket: https://ticketsystem.schul-cloud.org/browse/SC-6369
Subtask of: https://ticketsystem.schul-cloud.org/browse/SC-5474
=> SC-6369 - security adminUser teachers route

.github/workflows/require_changelog.yml, CHANGELOG.md
=> added changelog file change test action

CHANGELOG.md, package-lock.json, package.json, src/services/user/services/AdminUsers.js, test/services/user/services/AdminUsers.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6697?
=> SC-6697 - edit email (Hotfix 24.4.4)

CHANGELOG.md, src/services/user/registration.js, test/services/user/registration.test.js
Currently it's possible to have the same email address for student and parent by changing the case, e.g.
student@test.de and student@test.De
The e-mail check should be case insensitive, i.e. student@test.de and student@test.De are interpreted as exactly the same e-mail address.
Note: We should not change the case when storing the email addresses. But nevertheless all checks and queries should be case insensitive.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6640
Updated the verification of student and parent email: Use lower case strings for comparison.
More and detailed information on the *definition of done* can be found [on …
=> SC-6640 - Registration: Stundent vs. Parent e-mail verification

deploy.sh
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1109
Remove automatic deployment on test environment. Replaced by sc-app-ci GitHub action.
=> ops-1109 removed deployment on testenvironment.

.eslintignore, .prettierignore, CHANGELOG.md, src/services/version/index.js, test/services/user/services/AdminUsers.test.js
As eslint does only accept one ignore file manually defined and prettier should not be applied on database seed files which should stay as they were exported some ignore files have been added to match for prettier locally, eslint, and codacy.
=> Cleanup prettier/eslint ignore files

CHANGELOG.md, package-lock.json, package.json, src/services/user/services/AdminUsers.js
- https://ticketsystem.schul-cloud.org/browse/SC-6637
=> Hotfix SC-6637

CHANGELOG.md
This PR updates the existing changelog file to match our linter/prettier rules:
- all headings have been updated to be distinct. change type headings were suffixed by "in version" like addedn in XX.XX.XX
- the order of some entries has been fixed
- duplicated same name sections under one version have been merged
=> lint and fix changelog entries

CHANGELOG.md, package-lock.json, package.json, src/services/sync/strategies/CSVSyncer.js, test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
=> Hotfix SC-6733

CHANGELOG.md, src/services/user/services/AdminUsers.js
Fixed invalid date adminUsers by removing duplicated code
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6784
=> SC-6784 - fix invalid date adminUsers

CHANGELOG.md, src/services/user/services/AdminUsers.js
Removed usersForConsent related things 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6743
=> SC-6743 - service cleanup

.github/workflows/require_changelog.yml
fix indention steps
make check conditional
write enabled to output
echo return value
FEATURE_OR_HOTFIX
braces added
remove braces
test
foo
env
env
or
env
use set env
add quotes
foo
foo
naming
indention
or
true
add defaults
fix indention
separate set env
true
remove braces from head ref
text
=> ignore checks for non feature-/hotfix-pr's 

CHANGELOG.md, package-lock.json, package.json, src/services/messengerSync/consumer.js, src/services/messengerSync/producer.js, src/utils/rabbitmq.js, test/services/messengerSync/rabbitmqMock.js, test/services/messengerSync/services/schoolSyncService.test.js
When the messenger is active, different event trigger sync request to inform the matrix messenger about new/updated users/courses/schools...
The updates are handled via RabbitMQ. This PR ensures that a valid RabbitMQ is available.
ToDo:
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6809
- store connection and channel in central place
- clean connection/channel if they are closed
- retry to subscribe consumer if channel was closed
- establish new connection when needed again
- catch failed requests internally, to avoid influence on core schul-cloud logic.
- -
- The messenger beta is currently running only on the hpi/boss instance. This instance requires this fix, it will have no influence on other instances.
- -
> Notice: Please remove the WIP label if the PR is ready to review, …
=> Hotfix: SC-6809: rabbitmq connection fix

CHANGELOG.md, src/services/messengerSync/consumer.js, src/services/messengerSync/producer.js, src/utils/rabbitmq.js, test/services/messengerSync/consumer.test.js, test/services/messengerSync/rabbitmqMock.js, test/services/messengerSync/services/schoolSyncService.test.js
When the messenger is active, different event trigger sync request to inform the matrix messenger about new/updated users/courses/schools...
The updates are handled via RabbitMQ. This PR ensures that a valid RabbitMQ is available.
The previous attempt to fix this problem (#1760) failed on deployment, because the same channel was used to send and to subscribe to messages. I was able to reproduce that failure and fixed it in this version. 
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6809
- extract rabbitmq channels in own class to handle connection failure 
- clean connection/channel if they are closed
- retry to subscribe consumer if channel was closed
- establish new connection when needed again
- catch failed requests internally, to avoid influence on core schul-cloud logic.
- - …
=> SC-6899: Add rabbitmq channel class to maintain channel connection

src/services/school/index.js
Increased the amount of schools that can be fetched to match the amount that can be choosen in SHD
=> increase possible amount of schools per page

CHANGELOG.md, config/default.schema.json, package-lock.json, package.json, sc-config.json
remove additional properties from configuration
print current configuration on startup
changelog updated
=> SC-6080 update commons to 1.2.7

CHANGELOG.md, package-lock.json, package.json, src/services/user/hooks/registrationPins.js, src/services/user/index.js, src/services/user/model/registrationPin.schema.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-6973
Related Client PR: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2239
=> Hotfix SC-6973

CHANGELOG.md, backup/setup/migrations.json, migrations/1601563383652-addIndexesForSlowQueries.js, package-lock.json, package.json, src/services/fileStorage/model.js, src/services/homework/model.js
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1316
- Adds indexes for files and submissions to speed up identified slow queries
- Contains a migration
=> Create indexes for slow queries

.pullapprove.yml
clean up no more existing groups: 
- loki/integrathor reviews have been removed
- privacy groupo has been removed
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/ARC-111
=> ARC-111 Avoid privacy PR reviews

CHANGELOG.md, package-lock.json, package.json, src/services/user/registration.js
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/SC-6960
- uses Model.replaceOne to rollback the user after a failed registration process instead of deleting and re-creating them
- properly raises exceptions during the registration process. In at least three places, an exception was either returned from a promise or a promise was rejected without an error.
=> SC-6960 fix registration eating users

CHANGELOG.md, README.md
=> fixes readme badges

.eslintrc.js, CHANGELOG.md, package-lock.json, package.json
Enforce Promise styles in https://github.com/xjamundx/eslint-plugin-promise/tree/master#rules via ESLint.
=> SC-6766 catch promise style

package-lock.json, package.json, src/index.js
- remove auto print config (which appears often in tests)
- explicit print config on application startup only
=> Update Commons to 1.2.8

CHANGELOG.md, package-lock.json, package.json, src/services/role/hooks/index.js, src/services/role/model.js, src/utils/cache.js, src/utils/index.js
TODO:
https://ticketsystem.schul-cloud.org/browse/SC-7115
=> Hotfix/3/sc 7115/reduce role db requests

src/services/user/registration.js
Caused by merging 25.0.8 into develop (Changes: #1799).
=> Repair merge conflict causing tests to fail

src/services/homework/hooks/index.js, test/services/homework/index.test.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7201
=> SC-7201 Fix homeworks test

.github/workflows/require_changelog.yml
This pr adds release branches to the scope of the GitHub action which requires changes in changelog files. On a release branch, the changelog versions have to be updated which will be checked.
=> OPS-1297 add release branches to scope of changelog action

CHANGELOG.md, src/services/account/hooks/index.js, src/services/account/services/accountApiService.js, test/services/account/services/accounts.test.js
Replaced a hook in the account service to check if the requester and requested user are from the same school.
Password change was failing because of the failing hook.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6986
=> SC-6986 - fix changing password error

CHANGELOG.md, src/errors/index.js, src/errors/utils.js, src/helper/compare.js, src/middleware/errorHandler.js, src/utils/incomingMessageToJson.js, src/utils/index.js, test/errors/utils.test.js, test/utils/incomingMessageToJson.test.js
=> add util to cleanup IncomingMessage for errors

CHANGELOG.md, config/default.schema.json, src/app.js, src/utils/prometheus.js
To have api metrics disabled by default, introduced FEATURE_PROMETHEUS_ENABLED in configuration.
This is required to analyze components in schulcloud-server for having high performance impact to be optionally disabled.
=> Introduce FEATURE_PROMETHEUS_ENABLED

CHANGELOG.md, package-lock.json, package.json, src/middleware/requestLogger.js, src/services/calendar/index.js, src/services/link/index.js, src/services/notification/index.js
This pr removes own querystring implementations in some services and replaces `querystring` dependency by `qs`, which supports nested properties to be transformed.
The method signatures of `parse` and `stringify` in `qs` more less equal to querystring.
=> replace querystring by qs

CHANGELOG.md, config/default.schema.json, src/services/school/index.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6293
=> SC-6293 - changes feature flag to boolean

CHANGELOG.md, backup/setup/migrations.json, migrations/1603872433544-addIndexForUserEmail.js, package-lock.json, package.json, src/services/user/model/user.schema.js
- adds an index on users.email to speed up a slow query
=> Hotfix SC-7491 add index on users.email

CHANGELOG.md, test/services/oauth2/hydra.js, test/services/oauth2/mock.js
This PR should fix concurrency issues with oauth tests.
Missing awaits of async code execution have been added and some restucturing has been done around nested promises.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7517
=> SC-7517/Feature/fix oauth2 tests

.travis.yml, CHANGELOG.md
=> rename integration test repo

src/services/user/services/AdminUsers.js
=> quickfix - adminUser search fix

CHANGELOG.md, config/default.schema.json
This sets some defaults, so that the server can start without any envs who need to be set.
=> SC-6690 - set defaults to fix server not starting

CHANGELOG.md, src/services/user/hooks/registrationPins.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7638
=> Hotfix SC-7638

CHANGELOG.md, test/services/messenger/services/messengerConfigService.test.js, test/services/messenger/services/messengerPermissionService.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-5476
=> SC-5476 Extend tests for Matrix messenger config and permission service

CHANGELOG.md, src/services/edusharing/services/EduSharingConnector.js, test/services/edusharing/EduSharingConnector.test.js
This PR reduces the expiration time for edu-sharing cookie and adds a fallback for trying a connection in case it fails.
It was tested that Edu-Sharing cookie validity is not 1h, but ~5 min.
This should lead to fewer bad results as well as 500s when fetching images gets "unauthorised" response on lernstore detail page.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7615
=> SC-7615 - reduces erros in lernstore

CHANGELOG.md, config/default.schema.json, package-lock.json, package.json, src/app.js, src/configuration/MemorySchedule.js, src/configuration/index.js, src/errors/utils.js, src/services/rocketChat/services/rocketChatChannel.js, src/utils/systemInfo.js, startup.sh
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7683
- Environment variables like MEMORY_INTERVAL_TIME=60
=> Hotfix/3/sc 7683/add log metrics and fix errors

CHANGELOG.md, package-lock.json, package.json, src/services/sync/strategies/CSVSyncer.js, test/services/helpers/testObjects.js, test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
=> Hotfix/3/sc 7695/secure csv user patches

CHANGELOG.md, src/services/edusharing/docs/openapi.yaml
Creates documentation for edu sharing endpoints
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7614
Creates schemas and documents for edu sharing service
=> SC-7614 - creates documentation for edu-sharing endpoints

src/common/disallow.hook.js, src/components/user/index.js, src/components/user/repo/account.repo.js, src/components/user/repo/index.js, src/components/user/repo/trashbin.repo.js, src/components/user/repo/user.repo.js, src/components/user/services/user.service.v2.integration.test.js, src/components/user/services/user.service.v2.js, src/components/user/uc/users.facade.js, src/components/user/uc/users.uc.js, src/components/user/uc/users.uc.unit.test.js, src/services/account/model.js
=> SC-7555 build app classes, facade

CHANGELOG.md, src/services/alert/cache.js
The status api should not DoS the status system by calling it every time. In error state the caching time should be reflected too.
=> ARC-137 avoid DoS on alerts in error state

src/components/user/index.js, src/components/user/repo/account.repo.js, src/components/user/repo/index.js, src/components/user/repo/trashbin.repo.js, src/components/user/repo/user.repo.js, src/components/user/services/index.js, src/components/user/services/user.service.v2.integration.test.js, src/components/user/services/user.service.v2.js, src/components/user/uc/users.facade.js, src/components/user/uc/users.uc.js, src/components/user/uc/users.uc.unit.test.js, src/services/user/services/AdminUsers.js
=> Feature/SC-7555 - delete user trashbin dr

.github/workflows/require_changelog.yml, CHANGELOG.md
This PR is fixing the Changelog action as the former usage of environment variables is currently outdated and no more working.
=> ARC-138 fix changelog action

src/components/user/uc/users.uc.unit.test.js
=> feature/SC-7555 - Updated unit tests

CHANGELOG.md, src/services/teams/model.js
Currently it's possible to use empty strings as team names.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-1589?filter=13248
* Use the `trim` feature of Mongoose to remove empty spaces of team names (and description)
=> Bugfix/SC-1589 - Trim strings to avoid empty team names

CHANGELOG.md, config/default.schema.json, src/middleware/errorHandler.js, src/services/authentication/docs/openapi.yaml, src/services/authentication/logic/index.js
=> Fix audience of the jwt for new organisation name.

CHANGELOG.md, src/services/me/docs/openapi.yaml, src/services/user/docs/registration.openapi.yaml
Fix made by @Parnswir, which fixes authentication error while accessing any nuxt page in the client application.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7884
=> feature/SC-7884 - Authentication error when accessing any nuxt page in the client

CHANGELOG.md, package-lock.json, package.json, src/utils/sanitizeHtml.js, test/utils/sanitizeHtml.test.js
Changes sanitization to avoid scripts from creating attributes.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7714
Changes sanitization to avoid scripts from creating attributes.
=> Hotfix/SC-7714 - xss risk

CHANGELOG.md, config/globals.js, package-lock.json, package.json, src/services/helpdesk/hooks/index.js, test/services/helpdesk/index.test.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6727
=> Change email addresses for tickets for niedersachcsen

CHANGELOG.md, config/default.schema.json, package-lock.json, package.json, src/services/helpdesk/hooks/index.js, test/services/helpdesk/index.test.js
=> SC-6727 Change email address - fix implementation after ops review

.mocharc.js, .nycrc.json, CHANGELOG.md, tsconfig.json
[https://ticketsystem.hpi-schul-cloud.org/browse/SC-6294](https://ticketsystem.hpi-schul-cloud.org/browse/SC-6294)
Changes in configuration to fix issues in tests that are placed in source (src) directory.
Changed command line coverage reporter to only show summary
=> SC-6294 - fixed test issues, coverage reporter changed

CHANGELOG.md, migrations/1601022564938-copy-parents-data-into-children-entities-and-delete-parent-users.js, package-lock.json, package.json
Fixed migration for copying parents data into students entity (removed cursor on behalf of the bulk operations). There was a problem with cursor being closed by the DB.
Removed mongoose cursor on behalf of the bulk operations in copy-parents-to-users migration.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8077
=> hotfix/4/SC-8077 - migration copy parents to users broken

CHANGELOG.md, package-lock.json, package.json, src/services/lesson/hooks/index.js, test/services/lessons/index.test.js
This pr takes care of existing lessons and new lessons added through course. A valid merlin url will be created as soon as the course is accessed
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7734
=> valid merlin url will be created as soon as the course is accessed

CHANGELOG.md, backup/setup/migrations.json, config/default.schema.json, migrations/1606739119373-merlin_credentials.js, src/services/edusharing/helpers.js, src/services/edusharing/index.js, src/services/edusharing/services/EduSharingConnector.js, src/services/edusharing/services/MerlinTokenGenerator.js, src/services/federalState/countyModel.js, src/services/lesson/hooks/index.js
This PR contains logic for accessing county specific materials for Lern-Store.
In Niedersachsen, schools who have the county where they belong defined, will be able to access on Lern-Store materials licensed to their county only.
The link to material is protected by the provider with credentials for the county only. 
The sensitive credentials needed on import are not part of the git. They are to be used on production, and can be found in 1Password.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6692
* using encoded with unique key credentials
* json file with credentials needs to be added for production: migrations/helpers/secret_counties_Ni.json (1 password)
* env vars: 
** remove (or set true) FEATURE_ES_MERLIN_ENABLED
** SECRET_ES_MERLIN_KEY=random key of min 16 chars
> Notice: …
=> SC-6692 - adds lern-store county filter

CHANGELOG.md, package-lock.json, package.json, src/services/fileStorage/strategies/awsS3.js
* use transaction helper
* properly close session
* use correct readPreference# Description
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1735
**Should not be merged into master directly, because this is based on 25.2.4!**
=> Fix transaction handling in file service OPS-1735

CHANGELOG.md, test/services/helpers/services/users.js
It fix the unit tests after hotfix 8149
=> sc-8179 build repaired

CHANGELOG.md, config/default.schema.json, config/test.json, src/services/edusharing/services/EduSharingConnector.js, test/services/edusharing/services/EduSharingConnector.test.js
adds a feature flag for searchable content for lern-store: when this is set to true, then lern-store searchable flag will be used, esentially excluding records which are not supposed to show in search.
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7763
=> SC-7763 - adds searchable flag for lern-store results

CHANGELOG.md, config/default.schema.json, config/test.json, src/services/edusharing/docs/openapi.yaml, src/services/edusharing/services/EduSharingConnector.js, src/services/lesson/hooks/index.js, test/services/edusharing/services/EduSharingConnector.test.js
This PR adds a new param and filter for the search endpoint of edu-sharing to return elements inside a collection.
Note: branch name is to match the (bigger) nuxt branch
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7932
https://github.com/hpi-schul-cloud/nuxt-client/pull/1599
=> SC-8020 - adds collection filter to lernstore

CHANGELOG.md, src/services/ldap-config/errors.js
Added invalid DN error handling to the LDAP-config service
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8229
=> SC-8229 - Invalid DN error handling

CHANGELOG.md, src/services/ldap-config/docs/schemas/get.response.yaml, src/services/ldap-config/docs/schemas/patch.requestBody.yaml, src/services/ldap-config/docs/schemas/post.requestBody.yaml
Removed attribute and member as required attributes for the LDAP-config service
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8233
=> SC-8219 - Removed required attributes

CHANGELOG.md, migrations/1608214028384-syncTeamIndexes.js, src/services/teams/model.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8260
=> Add team indexes and migration

CHANGELOG.md, src/services/edusharing/services/EduSharingConnector.js
This PR fixes the case when Lernstore searchable feature is enabled in combination with lernstore collections (allows collections items to show up in collection view).
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7763
=> SC-7763 - fixes searchable flag for lernstore items

CHANGELOG.md, package-lock.json, package.json, src/services/calendar/hooks/index.js
Solve problem of getting old object in cluster
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8189
=> get last updated object

backup/setup/migrations.json
=> migrations.json

src/services/pseudonym/hooks/index.js, src/services/pseudonym/model.js, src/services/roster/index.js
=> SC-8315 pseudynom/roster cleanup

src/services/fileStorage/strategies/awsS3.js
=> SC-8322: improve s3 stability

src/services/pseudonym/docs/openapi.yaml, src/services/roster/docs/openapi.yaml
=> add pseudonym model in api schema

test/services/fileStorage/aws/awsS3.test.js
=> SC-8322: fix test

test/services/fileStorage/aws/awsS3.test.js
=> fix aws test

CHANGELOG.md, src/errors/helper/assertionErrorHelper.js, src/services/videoconference/logic/index.js, test/services/videoconference/logic/index.js
This PR introduces whitelisting bbb room names and usernames on a predefined regex. This should avoid non-working room creation/join which is caused by malicous checksums caused by special chars in these fields.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-4576
=> SC-4576 sanitize bbb room and member names

.gitignore, CHANGELOG.md, src/services/messengerSync/utils.js, src/services/sync/strategies/CSVSyncer.js, src/services/sync/strategies/LDAPSchoolSyncer.js, src/services/sync/strategies/Syncer.js, src/services/user/docs/adminusers.openapi.yaml, src/services/user/docs/openapi.yaml
Currently errors in the syncers are logged twice. By the super class Syncer and the sub classes.
Therefor I added a couple of logs to the sub classes where they were missing and removed the logging from the super class Syncer.
The errors array in Syncer were meant to be shown to the admin. These errors can contain personal data, because the admin knows about this information  anyways. He is in control over the CSV or the LDAP that is synced. In the log we have to restrict the amount of personal data. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8300
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.actio …
=> SC-8300 consolidate logging of (ldap-)syncer

CHANGELOG.md, package-lock.json, package.json, src/services/user-group/services/course-copy-service.js
Added a missing await and resolve with the updated instead of outdated share token, when the update succeeded.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8444
=> Hotfix/3/25.5.6 SC-8444

CHANGELOG.md, package-lock.json, package.json, src/services/homework/hooks/index.js, test/services/homework/index.test.js
=> Hotfix 25.5.7 SC-8489

CHANGELOG.md, package-lock.json, package.json, src/errors/utils.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8480
=> Hotfix SC-8480

Dockerfile, backup.js, startup.sh
=> Kubectls experiments dockerfile

backup.js, k8s/configmap.yaml, k8s/deployment.yaml, package.json, startup.sh
Using a MongoDB cluster (ReplicaSet)
=> Kubectls experiments mongodb replicaset

CHANGELOG.md, package-lock.json, package.json, src/services/homework/hooks/index.js
Fix homework permission check. Rollback for #2201
=> SC-8503 - Clicking on task in BRB and THR shows pencil page

.github/workflows/main.yml, k8s/ingress.yaml
=> Kubectls experiments ssl

CHANGELOG.md, package-lock.json, package.json, src/services/ltiTool/hooks/index.js, src/services/videoconference/index.js, src/services/videoconference/logic/constants.js
This PR adds the requesting domain name to bbb requests to be able there to separate different origins.
REVIEW STATE
=> Hotfix/3/ SC-8506

CHANGELOG.md, backup/setup/migrations.json, migrations/1611829684290-addUniquePseudonymIndex.js, package-lock.json, package.json, src/services/pseudonym/hooks/index.js, src/services/pseudonym/model.js
=> Hotfix SC-8499

CHANGELOG.md, src/services/user/services/QrRegistrationLinks.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8514
https://github.com/hpi-schul-cloud/nuxt-client/pull/1645
- fixed the Bad Request Error
=> SC-8514 - QR Code generation fails

CHANGELOG.md, package-lock.json, package.json, src/services/homework/hooks/index.js
=> SC-8462 add logging for homework deletion

CHANGELOG.md, package-lock.json, package.json, src/services/user/model/user.schema.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8420
=> hotfix 25.5.14 fix broken user index

CHANGELOG.md, src/services/link/index.js
=> SC-8534 - registration link generation bug

src/services/videoconference/logic/index.js, test/services/videoconference/logic/index.js
This PR is removing simple apostrophe`'`  from bbb room name character whitelisting as it is issuing checksum generation not to be working. PR has been started from selected base `branch release/25.6.0`.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8588
=> SC-8588 remove apostrophe from bbb allowed room name chars

CHANGELOG.md, backup/setup/migrations.json, migrations/1612529901503-remove_event_duplication.js, package-lock.json, package.json
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8512
- Migration for duplicated events
=> Hotfix/1/SC-8512 - migration of events duplicates

CHANGELOG.md, src/services/calendar/courseCalendar.js, src/services/calendar/index.js
Introduced the route to delete all calendar events for the given scope.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8408
https://github.com/hpi-schul-cloud/schulcloud-server/pull/2249
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/69
=> SC-8408: delete by scope route

CHANGELOG.md, config/default.schema.json, package-lock.json, package.json, src/components/task/repo/task.repo.integration.test.js, src/services/user/hooks/publicTeachers.js
https://ticketsystem.hpi-schul-cloud.org/browse/VOR-2
=> VOR-2 Adjust rule for adding team member from other schools

CHANGELOG.md, src/components/user/repo/user.repo.integration.test.js, src/components/user/uc/users.uc.integration.test.js, src/components/user/uc/users.uc.js, src/components/user/uc/users.uc.unit.test.js
When the user is deleted, we still have cases when the user is referenced in other collections. For this case we have created a tombstone user. In teams we access the school name. But the tombstone user didn't had any school assigned. For this cases a tombstone school was defined and with this PR assigned to the tombstone user.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8341
=> SC-8341: add tombstone school to the tombstone user

CHANGELOG.md, src/components/user/services/index.js, src/components/user/services/user.service.v2.integration.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8230
=> fix deletion of teachers via new route

CHANGELOG.md, migrations/1613348381637-replaceFileLinks.js, migrations/1613491062486-replaceFileLinksHomework.js, package-lock.json, package.json
SC-8657
SC-8634
VOR-3
25.6.6
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8657
=> hotfix/25.6.6/Fix migration and add secure patch conditions.

CHANGELOG.md, src/components/user/repo/db/trashbin.schema.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7021
automatic deletion of whatever is in the `trashbins` collection after 7 days.
=> SC-7021 Deletion of user data after a specific time

CHANGELOG.md, src/services/user/services/AdminUsers.js, test/services/user/services/AdminUsers.test.js
add isexternal check to adminusers patch
=> SC-8682 - add isexternal check to adminusers patch

CHANGELOG.md, test/services/messenger/services/messengerConfigService.test.js, test/services/messenger/services/messengerPermissionService.test.js, test/services/messengerSync/utils.test.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8728
=> SC-8728 fix configuration reset in tests

CHANGELOG.md, src/services/user/services/AdminUsers.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8707
prioritize sorting of columns over search result
=> switch sort priority

CHANGELOG.md, test/services/homework/index.test.js
This PR refactors a bit the homework tests and adds a couple of extra tests.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5202
=> SC-5202 - refactors a bit and adds a cople of tests

CHANGELOG.md, src/components/fileStorage/repo/fileStorageProvider.repo.integration.test.js
=> SC-7868 skip filestorage integration tests if not setup

CHANGELOG.md, package-lock.json, package.json, src/services/rocketChat/services/rocketChatLogin.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8829
=> Hotfix SC-8829

CHANGELOG.md, package-lock.json, package.json, src/services/ldap/index.js, src/services/ldap/lockingQueue.js, src/services/ldap/lockingQueue.unit.test.js
The parallel sync of multiple schools from the same LDAP system was not possible, because LDAP allows only one connection while in a paged search.
Solution: The connection is marked as "in use". If more connections are requested the requests are queued. Whenever the connection is released, it is given to the next request in the queue.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8691
=> SC-8691 Make parallel sync of schools possible

CHANGELOG.md, package-lock.json, package.json, src/services/user-group/hooks/classes.js, src/services/user-group/services/classes.js, test/services/user-group/hooks/classes.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8836
=> SC-8836 teachers can add classes from other teachers to their courses

CHANGELOG.md, src/services/user/docs/adminusers.openapi.yaml
After a search is done, when emptying the search input, an empty query is automatically sent to the server, which causes openapi to raise a validation error.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8880
=> SC-8880 - Empty query openapi error

CHANGELOG.md, package-lock.json, package.json, src/services/ldap/index.js, src/services/ldap/lockingQueue.js, src/services/ldap/lockingQueue.unit.test.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8691
=> SC-8691 ldap: ensure client is unlocked in case of error

CHANGELOG.md, package-lock.json, package.json, src/services/ldap/index.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8908
=> SC-8908 fix ldap lock

CHANGELOG.md, src/services/user/services/AdminUsers.js, test/services/user/services/AdminUsers.test.js
added an isExternal check to the adminUsers service remove method
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8910
=> SC-8910 - add external check to remove method

CHANGELOG.md, src/services/messengerSync/services/messengerTokenService.js, test/services/messengerSync/services/messengerTokenService.test.js
why? - the auto-generated device-ids clash quite often
we can generate the device-ids based on the user id
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8909
- update matrix login request
- -
- -
- -
=> SC-8909: fixed device ids

.eslintrc.js
This PR makes the eslintrc.js file compatible with the eslint version currently installes as some rules are no more provides after being merged into prettier itself.
With that change, eslint and prettier are working for me.
=> update eslintrc to new eslint version

.eslintrc.js, src/errors/applicationErrors.js, src/services/sync/strategies/LDAPSyncerConsumer.js
=> Poc sc 9005

CHANGELOG.md, src/services/school/hooks/index.js
in brandenburg, schools number can have 5 or 6 digits
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6950
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2532
=> SC-6950 - changes validation for officialSchoolNumber

.travis.yml, CHANGELOG.md
OPS-1559 - fixes condition in travis, which was making test stage be skipped 
=> OPS-1499 - fixes condition in travis

.travis.yml, CHANGELOG.md
=> OPS-1499 - fixes travis run on release branch

CHANGELOG.md, src/components/user/uc/users.uc.integration.test.js, src/components/user/uc/users.uc.js
**ToDo:** Tests missing
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9085
=> SC-9085 delete registration pin for parent in deletion concept

CHANGELOG.md, src/services/user/docs/adminusers.openapi.yaml
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8440
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2558
=> SC-8440 - fixed open api validation for manual consent

CHANGELOG.md, src/services/user/firstLogin.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8933
=> SC-8933 - fix date format on first login

CHANGELOG.md, package-lock.json, package.json
=> fix dependencies issue

CHANGELOG.md, package-lock.json, package.json, src/services/sync/repo/user.repo.js, src/services/user/model/user.schema.js
Add missing mongo indexes for LDAP Sync
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9134
Add missing mongo indexes for LDAP Sync
=> SC-9134 - Add missing mongo indexes for LDAP Sync

CHANGELOG.md, package-lock.json, package.json, scripts/syncIndexes.js
=> improve syncIndex

CHANGELOG.md, backup/setup/migrations.json, backup/setup/roles.json, migrations/1621240373574-add-task-dashboard-for-students.js, migrations/1623849218703-rename-task-permission.js, package-lock.json, package.json
=> rename permission TASK_DASHBOARD_VIEW_V3

.vscode/launch.default.json, package.json
let the script work again and update vscode default launch script
=> fix nest test/debug configuration

CHANGELOG.md, package-lock.json, package.json, src/services/sync/repo/school.repo.js, src/services/sync/strategies/consumerActions/ClassAction.js, src/services/sync/strategies/consumerActions/UserAction.js, test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js, test/services/sync/strategies/consumerActions/ClassAction.test.js, test/services/sync/strategies/consumerActions/UserAction.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9156
=> SC-9156: Add maintenance mode for LDAP rewrite

.github/workflows/tag.yml, CHANGELOG.md, package-lock.json, package.json, src/middleware/legacyForward.js, src/services/me/index.js
=> fix route forwarding

apps/server/src/legacy/nest-app-holder.ts, apps/server/src/modules/feathers/feathers-service.provider.spec.ts, apps/server/src/modules/news/uc/news.uc.spec.ts, apps/server/src/modules/news/uc/news.uc.ts, apps/server/src/modules/task/controller/task.controller.ts, apps/server/src/modules/task/entity/file-task-info.entity.ts, apps/server/src/modules/task/uc/task.uc.ts, apps/server/src/modules/user/entity/account.entity.ts, apps/server/src/modules/user/user.facade.ts, apps/server/src/shared/repo/base.repo.integration.spec.ts, apps/server/src/shared/repo/base.repo.ts
SC-9194 fix nestjs test coverage
=> SC-9194 fix nestjs test coverage

apps/server/src/legacy/nest-app-holder.ts, apps/server/src/modules/feathers/feathers-service.provider.spec.ts, apps/server/src/modules/news/uc/news.uc.spec.ts, apps/server/src/modules/news/uc/news.uc.ts, apps/server/src/modules/task/controller/task.controller.ts, apps/server/src/modules/task/entity/file-task-info.entity.ts, apps/server/src/modules/task/uc/task.uc.ts, apps/server/src/modules/user/entity/account.entity.ts, apps/server/src/modules/user/user.facade.ts, apps/server/src/shared/repo/base.repo.integration.spec.ts, apps/server/src/shared/repo/base.repo.ts
=> fix nestjs test coverage

.dockerignore, .github/workflows/build_push_service.yml, .github/workflows/main.yml, .github/workflows/tag.yml, Dockerfile
=> improved build process

CHANGELOG.md, src/services/helpers/service.js
=> SC-9292 Fix sending registration link mails

.github/workflows/test.yml
=> use global env instead of matrix definitions

CHANGELOG.md, migrations/1622209795280-add_S3_expiration.js, package-lock.json, package.json
=> SC-9092 add missing S3 key encryption

.github/workflows/test_e2e.yml
=> execute e2e tests on pr without wip label only

CHANGELOG.md
=> SC-9211 enable maildrop with mailcatcher (see docker-compose)

CHANGELOG.md, src/services/user/hooks/userService.js, src/services/user/services/MailRegistrationLink.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9053
Nuxt PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/1848
=> SC-9053 prevent repeated user requests

backup/setup/classes.json, backup/setup/schools.json
Updated seed data to be allign with school year 2021/22.
=> updated seed data for school year 2021/22

CHANGELOG.md, src/services/sync/strategies/CSVSyncer.js
=> SC-9212 fix changing classes via CSV import

CHANGELOG.md, src/components/user/docs/openapi.yaml, src/components/user/services/index.js, src/components/user/services/user.service.v2.integration.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9177
=> SC-9177 allow superheros to delete admins

CHANGELOG.md, package-lock.json, package.json, src/services/edusharing/services/EduSharingConnector.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9233
=> SC-9233 - fix Lern-Store for THR not loading WLO content

.github/PULL_REQUEST_TEMPLATE.md
Extended pull request template with QA check to verify the change was tested manually if possible.
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2638
=> extended pull request template with QA check

ansible/roles/schulcloud-server/tasks/main.yml, ansible/roles/schulcloud-server/templates/api-ldap-sync-full-cronjob.yml.j2, ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2, ansible/roles/schulcloud-server/templates/configmap_file_init_db.yml.j2
add kubernetes manifests for ldap integration in auto deployment
add kubernetes manifests for ldap integration in auto deployment
=> ldap integration

CHANGELOG.md, backup/setup/migrations.json, backup/setup/roles.json, migrations/1628265676996-addAdminEditToSuperheroRole.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9231
=> SC-9231 - add permission to superhero to edit admin role

.github/workflows/test_e2e.yml, apps/server/src/modules/user/controller/user.controller.ts
This PR changes the behaviour when e2e tests are executed.
By default, (creating the pr or adding a commit) the tests should not be executed, instead when
- the 'run tests' label is added on a pr, the action will be executed immediately
- the label is present and a commit in the pr is pushed
- the action is triggered manually
it should be executed.
=> SC-9211 re-evaluate labels when labels have changed after commit

apps/server/src/modules/mail/mail.service.spec.ts, apps/server/src/modules/mail/mail.service.ts
mail amqp-messages are now marked as persistent
=> marked amqp-mail-messages as persistent

apps/server/src/modules/mail/mail.service.spec.ts, apps/server/src/modules/mail/mail.service.ts
fix the formation of two lines of code at mail part for lint test to be okay. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9266
fix the formation of two lines of code at mail part for lint test to be okay. 
=> SC-9266 - fix formation of code

CHANGELOG.md, apps/server/src/main.ts, package-lock.json, package.json
=> SC-9192 - enable cors for nestjs app routes

.github/workflows/test_e2e.yml, .github/workflows/test_e2e_pull_request.yml, .github/workflows/test_e2e_push_main.yml, CHANGELOG.md
This PR adds a new github action on push event for the main branch regarding to BR-67 as part of BC64.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-67
=> BC-64 BC-67 enable e2e tests for push on main branch

CHANGELOG.md, config/default.schema.json, package-lock.json, package.json, src/services/fileStorage/strategies/awsS3.js
https://ticketsystem.hpi-schul-cloud.org/browse/BC-41
=> BC-41 - adds feature flag for S3 Bucket Lifecycle Management

CHANGELOG.md, apps/server/src/modules/authentication/strategy/jwt-validation.adapter.ts, package-lock.json, package.json, src/app.hooks.js, src/services/authentication/logic/whitelist.js
This PR should fix failing authentication on files via wopi clients.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-267
=> BC-267 skip whitelist-check for api requests on /wopi

CHANGELOG.md, config/default.schema.json, src/components/user/repo/db/trashbin.schema.js, src/services/fileStorage/strategies/awsS3.js, test/services/fileStorage/aws/s3.mock.js
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-262
=> BC-262 remove S3 lifecycle code

ansible/roles/schulcloud-server/templates/configmap.yml.j2, ansible/roles/schulcloud-server/templates/secret.yml.j2
edu sharing for auto deployment
=> bc-280 enabeling edusharing

.github/workflows/pull_request.yml, .github/workflows/test_unstable_e2e.yml, CHANGELOG.md
trigger e2e tests with label on PR `run unstable tests`.
These tests are not mandatory, and can be re-run in about 6 min
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-364
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/347
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1925
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2683
=> BC-364 - run unstable e2e tests

CHANGELOG.md, package-lock.json, package.json
fixed axios vulnerabilities
there is also a usage from nest of the problematic version, which should be solved with upgrade of nest to v8
https://ticketsystem.hpi-schul-cloud.org/browse/BC-377
=> BC-377 - fix axios vulnerabilities

CHANGELOG.md, migrations/1630928992986-addBucketToFiles.js, package-lock.json, package.json
=> BC-422 run bucket to files migration in parallel

CHANGELOG.md, apps/server/src/modules/task/uc/task.authorization.service.ts, apps/server/src/repositories/learnroom/course.repo.ts, apps/server/src/shared/domain/entity/course.entity.ts, apps/server/src/shared/domain/entity/lesson.entity.ts, apps/server/src/shared/domain/entity/task.entity.ts
=> BC-532 add indexes to lesson, course and task

CHANGELOG.md, src/components/fileStorage/repo/files.repo.js
=> fix flaky file repository test

CHANGELOG.md, apps/server/src/repositories/learnroom/dashboard.repo.integration.spec.ts, apps/server/src/shared/domain/entity/dashboard.entity.ts, apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts, package-lock.json
this is mostly a measure to make sure the order of elements within a
group is always consistent, no matter what changes are made, and how
they are sinced with the database or clients.
=> BC-605 sort references within groups alphabetically

apps/server/src/shared/repo/dashboard/dashboard.repo.ts
=> testing pr

CHANGELOG.md, src/services/helpers/service.js
after upgrade to node 16, on sending emails,  even if the email was being sent, we saw a 500 error on client,
"Converting circular structure to JSON"...
On server, an error was printing in logs even if NODE_END is production, and that error was containing the json for the email 
https://ticketsystem.hpi-schul-cloud.org/browse/BC-599
=> BC-599 - fix bug on email

CHANGELOG.md, migrations/1634814982190-ldap_federal_state.js
=> BC-489 fix error on migration

CHANGELOG.md, src/services/ldap/index.js
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-685
=> BC-685 - fix more usage of class attribute

.github/workflows/clean.yml, CHANGELOG.md
Fix for Mistakten for branch delete event.
It's not GITHUB_REF what shoud be used it's github.event.ref.
The action are triggert on the main branch, so GITHUB_REF shows to main and github.event.ref has the branchname of the deleted branch.
https://docs.github.com/en/rest/reference/git#delete-a-reference
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1959
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2716
- https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/94
- https://github.com/hpi-schul-cloud/antivirus_check_service/pull/14
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/138
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/60
More and …
=> BC-589 - Fix mistaken for branch delete event.

apps/server/src/modules/learnroom/controller/course.controller.spec.ts, apps/server/src/modules/learnroom/controller/course.controller.ts, apps/server/src/modules/learnroom/controller/dto/courseMetadata.response.ts, apps/server/src/modules/learnroom/controller/dto/index.ts, apps/server/src/modules/learnroom/learnroom.module.ts, apps/server/src/modules/learnroom/mapper/course.mapper.ts, apps/server/src/modules/learnroom/uc/course.uc.spec.ts, apps/server/src/modules/learnroom/uc/course.uc.ts, apps/server/src/shared/domain/entity/course.entity.spec.ts, apps/server/src/shared/domain/entity/course.entity.ts, apps/server/src/shared/repo/course/course.repo.integration.spec.ts, apps/server/src/shared/repo/course/course.repo.ts, apps/server/test/modules/learnroom/course.e2e-spec.ts
=> Bc 723 get courses

CHANGELOG.md, apps/server/src/modules/learnroom/controller/dashboard.controller.ts, config/default.schema.json
https://ticketsystem.hpi-schul-cloud.org/browse/BC-724
https://github.com/hpi-schul-cloud/nuxt-client/pull/1966
=> BC-724 fixed OpenAPI spec for dashboard

src/services/ldap/strategies/univention.js, test/services/ldap/strategies/univention.test.js
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-730
=> BC-730 add univention LDAP tests

CHANGELOG.md, ansible/group_vars/all/schulcloud-server.yml, ansible/roles/schulcloud-management/templates/management-deployment.yml.j2, ansible/roles/schulcloud-server/templates/api-delete-s3-files-cronjob.yml.j2, ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2, ansible/roles/schulcloud-server/templates/deployment.yml.j2
=> BC-740 change ansible vars for docker image and tag

config/default.schema.json, src/services/school/model.js, src/services/sync/model/userMigration.schema.js, src/services/sync/repo/user.repo.js, src/services/sync/strategies/SyncMessageBuilder.js, src/services/sync/strategies/consumerActions/ClassAction.js, src/services/sync/strategies/consumerActions/SchoolAction.js, src/services/sync/strategies/consumerActions/UserAction.js
=> some fixes

src/services/ldap/strategies/univention.js, test/services/ldap/strategies/univention.test.js
=> BC-915 sync admin role for univention

src/services/sync/model/importUser.schema.js, src/services/sync/strategies/consumerActions/UserAction.js
Update persistence format of usermatch in importuser to avoid usage of an embeddable with mikroorm which did not work.
=> BC-1049 inline user match into importuser

apps/server/src/shared/domain/entity/dashboard.entity.ts
fixed the first position in a Grid to be considered as position for new
elements
=> fix positioning of new dashboard elements

apps/server/src/core/error/filter/global-error.filter.spec.ts, apps/server/src/core/error/filter/global-error.filter.ts
With this PR we no more respond technical details via rest while they are logged only.
=> BC-1062 hide technical error details in error response

ansible/roles/schulcloud-server-core/templates/configmap.yml.j2
=> BC-1084 no default value for ALERT_STATUS_URL

apps/server/src/modules/learnroom/controller/dto/roomBoardResponse.ts, apps/server/src/modules/learnroom/mapper/board.mapper.ts
=> fix board API

ansible/roles/schulcloud-server-init/templates/management-deployment.yml.j2
=> BC-998 use prod for management service

apps/server/src/core/validation/pipe/global-validation.pipe.ts
=> update validationpipe parameters

apps/server/src/server.module.ts, apps/server/src/shared/testing/cleanup-collections.ts, apps/server/test/app.e2e-spec.ts, apps/server/test/modules/learnroom/course.e2e-spec.ts, apps/server/test/modules/learnroom/dashboard.e2e-spec.ts, apps/server/test/modules/learnroom/rooms.e2e-spec.ts, apps/server/test/modules/news/news.e2e-spec.ts, apps/server/test/modules/task/task-finished.e2e-spec.ts, apps/server/test/modules/task/task.e2e-spec.ts, apps/server/test/modules/user/user.e2e-spec.ts
Use an in memory databse for e2e tests by adding a server test module.
=> BC-1104 in memory databse for e2e tests

apps/server/src/modules/learnroom/controller/dto/roomBoardResponse.ts, apps/server/src/modules/learnroom/learnroom.module.ts, apps/server/src/modules/learnroom/mapper/board.mapper.spec.ts, apps/server/src/modules/learnroom/mapper/board.mapper.ts, apps/server/src/modules/learnroom/uc/rooms.uc.spec.ts, apps/server/src/modules/learnroom/uc/rooms.uc.ts, apps/server/src/shared/repo/lesson/lesson.repo.integration.spec.ts
Additionally to tasks now lessons will be added to rooms view.
Teacher will see any lesson from the course while students
will only see lessons which are not hidden.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-1103
=> BC-1103 implementing lessons into rooms - Backend

apps/server/src/shared/domain/entity/all-entities.integration.spec.ts, apps/server/src/shared/domain/entity/role.entity.ts, apps/server/src/shared/domain/entity/user.entity.ts
This PR introduces a test that checks all defined indexes can be set.
--> errors related to duplicated definitions have been removed. either use @index OR @unique only
=> BC-958 ensure, all defined indexes can be set (and fix issues)

package-lock.json, package.json
reduce logging output from configuration
=> BC-1093 update commons configuration to 1.3.4

apps/server/src/shared/repo/task/task.repo.integration.spec.ts, apps/server/src/shared/repo/task/task.repo.ts
=> BC-1071 fix sorting bug by similar dueDates for paginated requests

apps/server/doc/architecture-mapping.md
https://ticketsystem.hpi-schul-cloud.org/browse/EW-128
=> EW-128 document how to access nest from feathers

src/services/user-group/services/course-copy-service.js
=> BC-1280 - soften error on couse copy

ansible/roles/schulcloud-server-tspsync/tasks/main.yml, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-cronjob.yml.j2, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
Fix the ansible role for the tsp sync
hpi-schul-cloud/dof_app_deploy#140
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1335
=> BC-1335 - fix tsp sync

ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
Fix url for LDAP Sync
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1356
=> BC-1356 - Fix url for LDAP Sync

apps/server/src/shared/domain/entity/course.entity.spec.ts, apps/server/src/shared/domain/entity/course.entity.ts, apps/server/src/shared/domain/entity/dashboard.entity.ts, apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-1292
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2067
=> BC-1292 - fix display of emoji in course avatar

apps/server/src/modules/task/controller/task.controller.ts, apps/server/src/modules/task/uc/task.uc.spec.ts, apps/server/src/modules/task/uc/task.uc.ts, apps/server/src/shared/repo/task/task.repo.integration.spec.ts, apps/server/src/shared/repo/task/task.repo.ts, apps/server/test/modules/task/task.e2e-spec.ts
=> BC-180 delete task

package-lock.json, package.json
hpi-schul-cloud/dof_app_deploy#163
hpi-schul-cloud/schulcloud-client#2777
hpi-schul-cloud/nuxt-client#2073
=> version 27.8.0

apps/server/src/modules/management/management.module.ts
fix disallowed global context in console
Because the management module doesn't use a RequestContext all commands are attempted to be called in the MikroORM global context. This results in an error. We can allow usage of the global context here as long each command is run in a seperate process.
=> Bugfix/BC-1458 - fix disallowed global context in console

ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
fix TSP sync cronjobs
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1521
=> BC-1521 - fix TSP sync cronjobs

src/services/fileStorage/model.js
=> BC-1533 - add db index for file anit virus

src/services/user-group/model.js
=> BC-1594 re-add-indexes

package-lock.json, package.json
hpi-schul-cloud/dof_app_deploy#226
hpi-schul-cloud/schulcloud-client#2831
hpi-schul-cloud/nuxt-client#2138
=> version 27.13.0

apps/server/src/shared/domain/entity/account.entity.ts
=> fix set indexes

apps/server/src/shared/domain/entity/task.entity.ts, apps/server/src/shared/testing/factory/task.factory.ts
=> BC-1717 - add missing index

package-lock.json, package.json
=> BC-1250 nestjs rabbitmq update

package-lock.json, package.json
hpi-schul-cloud/dof_app_deploy#247
hpi-schul-cloud/schulcloud-client#2859
hpi-schul-cloud/nuxt-client#2166
=> version 27.16.0

ansible/roles/schulcloud-server-core/tasks/main.yml, package-lock.json, package.json
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3465
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2864
https://github.com/hpi-schul-cloud/nuxt-client/pull/2166
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/259
=> version 27.17.0

apps/server/src/modules/learnroom/controller/dto/course-copy.response.ts, apps/server/src/modules/learnroom/controller/dto/index.ts, apps/server/src/modules/learnroom/controller/rooms.controller.spec.ts, apps/server/src/modules/learnroom/controller/rooms.controller.ts, apps/server/src/modules/learnroom/learnroom.module.ts, apps/server/src/modules/learnroom/mapper/course-copy.mapper.ts, apps/server/src/modules/learnroom/uc/course-copy.uc.spec.ts, apps/server/src/modules/learnroom/uc/course-copy.uc.ts, apps/server/src/modules/task/controller/dto/task-copy.response.ts, apps/server/src/shared/domain/service/course-copy.service.spec.ts, apps/server/src/shared/domain/service/course-copy.service.ts, apps/server/src/shared/domain/types/copy.types.ts, apps/server/test/modules/learnroom/rooms.e2e-spec.ts
As a teacher I want to copy one of my courses so that I can reuse it.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1556
=> BC-1556 - Course copy service (Backend)

apps/server/src/modules/task/uc/task.uc.spec.ts, apps/server/src/modules/task/uc/task.uc.ts, apps/server/src/shared/repo/task/task.repo.integration.spec.ts, apps/server/src/shared/repo/task/task.repo.ts
=> BC-1797 - sort by id and due date

apps/server/src/modules/task/controller/dto/task.response.ts, apps/server/src/modules/task/mapper/task.mapper.spec.ts, apps/server/src/modules/task/mapper/task.mapper.ts, apps/server/src/shared/domain/entity/task.entity.spec.ts, apps/server/src/shared/domain/entity/task.entity.ts
Add courseId to task API response so it can be used by frontend task overview page.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1552
https://github.com/hpi-schul-cloud/nuxt-client/pull/2193
=> BC-1552 - Add courseId to task API response

.github/workflows/test.yml
=> increase timeout of nest tests

package-lock.json, package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/285
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3501
https://github.com/hpi-schul-cloud/nuxt-client/pull/2204
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2901
=> version 28.2.0

apps/server/src/modules/learnroom/learnroom.module.ts, apps/server/src/modules/learnroom/mapper/copy.mapper.ts, apps/server/src/modules/learnroom/uc/course-copy.uc.spec.ts, apps/server/src/modules/learnroom/uc/course-copy.uc.ts, apps/server/src/modules/learnroom/uc/rooms.service.spec.ts, apps/server/src/modules/learnroom/uc/rooms.service.ts, apps/server/src/modules/learnroom/uc/rooms.uc.spec.ts, apps/server/src/modules/learnroom/uc/rooms.uc.ts, apps/server/src/modules/task/uc/task-copy.uc.spec.ts, apps/server/src/modules/task/uc/task-copy.uc.ts, apps/server/src/shared/domain/entity/board.entity.ts, apps/server/src/shared/domain/entity/course.entity.ts, apps/server/src/shared/domain/service/board-copy.service.spec.ts, apps/server/src/shared/domain/service/board-copy.service.ts, apps/server/src/shared/domain/service/course-copy.service.spec.ts, apps/server/src/shared/domain/service/course-copy.service.ts, apps/server/src/shared/domain/service/index.ts, apps/server/src/shared/domain/service/lesson-copy.service.spec.ts, apps/server/src/shared/domain/service/lesson-copy.service.ts, apps/server/src/shared/domain/service/task-copy.service.spec.ts, apps/server/src/shared/domain/service/task-copy.service.ts, apps/server/src/shared/domain/types/copy.types.ts, apps/server/src/shared/repo/board/board.repo.ts, apps/server/test/modules/learnroom/rooms.e2e-spec.ts, config/development.json
- https://ticketsystem.dbildungscloud.de/browse/BC-1820
=> BC-1820 - Board Copy

apps/server/src/main.ts, backup/setup/ltitools.json
https://ticketsystem.dbildungscloud.de/browse/N21-167
=> [N21-167] isHidden to ltitools.json for dev seed

package-lock.json, package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/288
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3508
https://github.com/hpi-schul-cloud/nuxt-client/pull/2212
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2908
=> version 28.3.0

apps/server/doc/testing.md
=> document usage of test mocks

ansible/roles/schulcloud-server-core/tasks/main.yml
apparently sometimes the job is not fully deleted, then we need to wait
to it to be so. otherwise the creation of the job will fail afterwards
=> wait after deletion of migration job

apps/server/src/modules/learnroom/learnroom.module.ts, apps/server/src/shared/domain/service/course-copy.service.spec.ts, apps/server/src/shared/domain/service/course-copy.service.ts, apps/server/src/shared/domain/service/index.ts, apps/server/src/shared/domain/service/name-copy.service.spec.ts, apps/server/src/shared/domain/service/name-copy.service.ts
If a course gets copied the coursename should be extended by a number and if it already contains such a suffix the number should be increased by one in order to make original and copy easily distinguishable  e.g.: 
- "Math" => "Math (1)"
- "Math (12)" => "Math (13)"
https://ticketsystem.dbildungscloud.de/browse/BC-1980
=> BC-1980 - added suffix handling for course copy name

apps/server/src/shared/domain/entity/course.entity.spec.ts, apps/server/src/shared/domain/entity/course.entity.ts
Creating a course with one letter as a name, for example "A", shows "undefined" in the avatar field.
https://ticketsystem.dbildungscloud.de/browse/BC-2058
=> BC-2058 - Creating a course with one-letter name crashes avatar

apps/server/src/shared/domain/service/task-copy.service.spec.ts, apps/server/src/shared/domain/service/task-copy.service.ts
We want to use the function deriveCopyName from the copy-helper-service in the task-copy-service. 
(Already used in lesson-copy-service and course-copy-service)
https://ticketsystem.dbildungscloud.de/browse/BC-2097
=> BC-2097 - use deriveName function in task copy service

apps/server/doc/git.md
https://ticketsystem.dbildungscloud.de/browse/BC-2108
=> add documentation for git conventions

apps/server/src/modules/learnroom/controller/dto/copy.response.ts, apps/server/src/shared/domain/service/course-copy.service.spec.ts, apps/server/src/shared/domain/service/course-copy.service.ts, apps/server/src/shared/domain/service/lesson-copy.service.spec.ts, apps/server/src/shared/domain/service/lesson-copy.service.ts, apps/server/src/shared/domain/service/task-copy.service.spec.ts, apps/server/src/shared/domain/service/task-copy.service.ts, apps/server/src/shared/domain/types/copy.types.ts
- The new scheme of naming group_titles like FILE_GROUP etc. was extended to other group-titles (e.g. LTITOOL_GROUP, SUBMISSION_GROUP)
- title-property was changed to being optional, as it not needed for GROUPs
- some course-status-information was removed from course-copy-copyStatus due to being not appropriate anymore
https://ticketsystem.dbildungscloud.de/browse/BC-2060
Nuxt: https://github.com/hpi-schul-cloud/nuxt-client/pull/2226
=> BC-2060 adjust types for status

apps/server/src/shared/domain/service/copy-helper.service.spec.ts, apps/server/src/shared/domain/service/copy-helper.service.ts
NOT_DOING elementes are things that are intentionally excluded from a copy.
They are thus not to be considered as failing. Instead, we ignore them
when calculating the final state of an element with multiple children.
This means other stati always take precedence, and an element with only
NOT_DOING children will fail
(as there are no children being considered.)
- https://ticketsystem.dbildungscloud.de/browse/BC-2115
=> BC - 2115 ignore NOT_DOING in copy state

ansible/roles/schulcloud-server-core/tasks/main.yml
=> removed duplicate code

package-lock.json, package.json
- https://ticketsystem.dbildungscloud.de/browse/BC-2078
=> remove version from package.json

backup/setup/schools.json
=> seed data fix, every school has an empty features array

backup/setup/migrations.json, backup/setup/roles.json, migrations/1659000228792-conferencePermissionForTeacherAndStudent.js
The teacher role should be able to start and join a videoconference meeting in BBB. 
The student should be able to join a videoconference in BBB.
https://ticketsystem.dbildungscloud.de/browse/N21-250
The START_MEETING permission will be added to the teacher role
and the JOIN_MEETING permission will be added to the student role in database.
=> N21-250-vc permission bug fix

backup/setup/classes.json, backup/setup/schools.json
Adjust seed backup data to new school year 22/23 for server.
BC-2240
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/424
- set currentYear of seed schools to 2022/23
- add new (follow up) class for 2022/23
=> BC-2240 - Adjust seed data to school year 2022/23 for backup in server

apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.integration.spec.ts, apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.ts
Fixed update executions request and changed integration test execution for the KeycloakConfigurationService.
- <https://ticketsystem.dbildungscloud.de/browse/EW-288>
See description and Jira ticket.
Does not apply.
Does not apply.
Does not apply.
=> EW-288 Bug fix for the Keycloak configuration

apps/server/src/shared/domain/entity/user.entity.ts
=> BC-2273 - move indexes to nest entity

src/services/account/services/SupportJWTService.js
The current implementation of the authentication service in nest falsely uses the support JWT. It is missing the systemId, which is required to skip the password step on first login. This fix adds this field to the support JWT as a hotfix for the problem.
https://ticketsystem.dbildungscloud.de/browse/N21-273
=> N21-273 fix iserv first login

apps/server/src/modules/learnroom/uc/course-copy.uc.spec.ts, apps/server/src/modules/learnroom/uc/course-copy.uc.ts, apps/server/src/modules/learnroom/uc/lesson-copy.uc.spec.ts, apps/server/src/modules/learnroom/uc/lesson-copy.uc.ts, apps/server/src/modules/task/uc/task-copy.uc.spec.ts, apps/server/src/modules/task/uc/task-copy.uc.ts, apps/server/test/modules/learnroom/rooms.e2e-spec.ts, apps/server/test/modules/task/task.e2e-spec.ts
As a follow up to BC-2288 we should now implement "FEATURE_COPY_SERVICE_ENABLED" into the backend for copy calls directly to the backend.
BC-2333
- implement `FEATURE_COPY_SERVICE_ENABLED` into each calling of the copy use cases
=> BC-2333 - Implement backend env var for copy service

src/services/system/hooks/index.js
=> BC-2327 - remove secrets from response

apps/server/src/shared/domain/rules/authorisation.utils.ts, apps/server/src/shared/domain/rules/team.rule.spec.ts, apps/server/src/shared/domain/rules/team.rule.ts
=> N21-280 revert changes of team rule

apps/server/README.md, config/Readme.md
More readable version for review:
https://github.com/hpi-schul-cloud/schulcloud-server/tree/BC-2347-add-configuration-documentation/config
=> BC-2347 Add readme.md for configuration documentation.

src/services/authentication/hooks/index.js
=> BC-2390 refactor redis whitelist

apps/server/src/modules/files/repo/embedded-files.repo.ts, apps/server/src/modules/files/uc/sync-embedded-files.uc.ts
=> BC-2136 - run embedded files for lessons

apps/server/src/shared/domain/entity/course.entity.spec.ts, apps/server/src/shared/domain/entity/course.entity.ts
=> BC-2404 - task overview page result error 500

apps/server/src/modules/files/uc/sync-embedded-files.uc.ts
=> BC-2136 - add check of component type

apps/server/src/shared/domain/entity/task.entity.spec.ts, apps/server/src/shared/domain/entity/task.entity.ts
Currently a internal server error blocks the copying of draft tasks as they do not possess a parent.
BC-2392
https://github.com/hpi-schul-cloud/nuxt-client/pull/2275
* get schoolId of task directly from linked school 
=> BC-2392 - Copying a draft task without course assignment does not work

apps/server/src/modules/files-storage-client/uc/copy-files.service.ts, apps/server/src/modules/files/uc/sync-embedded-files.uc.ts, apps/server/src/shared/domain/entity/lesson.entity.ts, apps/server/src/shared/domain/service/file-copy-append.service.ts
check production data for lessons, so that all cases are covered by our lesson entity structure 
BC-2428
* adjust entity data to actual usecases and clean up database
=> BC-2428 - check lesson data and adjust entity

README.md
=> CeEv remove outdated links from github project readme

apps/server/src/modules/oauth/service/iserv-oauth.service.spec.ts, apps/server/src/modules/oauth/service/iserv-oauth.service.ts
=> BC-2480 enhanced logging

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2, backup/setup/accounts.json, backup/setup/users.json
- also fixes issue in initialization per se were mutliple documenty were tried to get inserted but not using an array
=> BC-2481 move max mustermann to dev system initialization

backup/setup/accounts.json, backup/setup/roles.json, backup/setup/schools.json, backup/setup/teams.json, backup/setup/users.json
- https://ticketsystem.dbildungscloud.de/browse/BC-2474
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/350
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3656
=> BC-2474 add expert related seed data

apps/server/src/modules/oauth-provider/service/oauth-provider.login-flow.service.spec.ts, apps/server/src/modules/oauth-provider/service/oauth-provider.login-flow.service.ts
minor bugfix due to merge error
https://ticketsystem.dbildungscloud.de/browse/N21-340
=> N21-340 fix call

.github/workflows/push.yml
=> add trivy vulnerability scanning

apps/server/src/shared/infra/collaborative-storage/strategy/nextcloud/nextcloud.strategy.spec.ts, apps/server/src/shared/infra/collaborative-storage/strategy/nextcloud/nextcloud.strategy.ts, apps/server/src/shared/repo/ltitool/ltitool.repo.spec.ts, apps/server/src/shared/repo/ltitool/ltitool.repo.ts
Extends logging for finding the nextcloud lti tool
https://ticketsystem.dbildungscloud.de/browse/N21-397
=> N21-397 Extended logging

scripts/endLdapSchoolYear.js, scripts/startNewSchoolYear.js
switch off transfer period --> change scripts for consistency with in time changes on production database
BC-2156
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/371
* to avoid thombstone schools being changed, as this might bring problems for deleted user data, the
currentYear is required for non-ldap schools
* set current year data
=> BC-2156 - SJW - Disable Transfer Period in all instances

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
provisioning now needs a provisioning strategy. This field has to be added in the configmap.
=> N21 403 bugfix: add provisioningStrategy to oauth systems in configmap

apps/server/src/modules/tool/service/lti-tool.service.spec.ts, apps/server/src/modules/tool/service/lti-tool.service.ts, apps/server/src/modules/tool/tool.module.ts, apps/server/src/modules/tool/uc/course-lti-tool.uc.spec.ts, apps/server/src/modules/tool/uc/course-lti-tool.uc.ts, apps/server/src/modules/tool/uc/superhero-lti-tool.uc.spec.ts, apps/server/src/modules/tool/uc/superhero-lti-tool.uc.ts, apps/server/src/shared/domain/types/page.ts
Created uc templates and lti tool service with hooks from feathers
https://ticketsystem.dbildungscloud.de/browse/N21-238
=> N21-237 Created base for lti tools in nest

apps/server/src/modules/provisioning/strategy/sanis/sanis-response.mapper.ts, apps/server/src/modules/provisioning/strategy/sanis/sanis.response.ts, apps/server/src/modules/provisioning/strategy/sanis/sanis.strategy.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/service/sanis-school.service.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/service/sanis-user.service.spec.ts
Adds new SANIS roles: LEIT and ORGADMIN and mapps them to the SVS role: Admin. The SYSA role gets removed.
https://ticketsystem.dbildungscloud.de/browse/N21-407
=> N21-407 update sanis roles

.github/workflows/migrations.yml, .github/workflows/publish_pages.yml, .github/workflows/push.yml, .github/workflows/tag.yml, .github/workflows/test.yml, .github/workflows/test_unstable_e2e.yml
updated all github actions, no breaking changes
=> BC-2684 update gh actions

.github/workflows/publish_pages.yml, .github/workflows/push.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2684
=> BC-2684 replace set-output

.github/workflows/publish_pages.yml
=> BC-2684 fix broken deploy pages action

src/services/passwordRecovery/services/GenerateRecoveryPasswordTokenService.js
Once the user enters the correct email address and clicks the "Reset Password" button, an email will be sent with the recovery password.
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3720
- https://ticketsystem.dbildungscloud.de/browse/BC-2699
=> BC-2699 - Fix password recovery mail

package-lock.json
=> BC-2558 - npm audit fix

src/services/passwordRecovery/services/ChangePasswordService.js
=> BC-2699 - fixes double encryption of pass

src/services/account/services/accountApiService.js, src/services/account/services/accountModelService.js
Mark feathers account services or models as deprecated.
https://ticketsystem.dbildungscloud.de/browse/EW-378
See description
NA
NA
NA
=> EW-378 Mark feathers account services as deprecated

apps/server/src/modules/learnroom/service/board-copy.service.spec.ts, apps/server/src/modules/learnroom/service/board-copy.service.ts
If the board of a course contains a broken reference (=a board element does not point to a Lesson or Task) these elements need to be skiped during course copy.
https://ticketsystem.dbildungscloud.de/browse/BC-2837
=> BC-2837 - skip corrupted boardelements

apps/server/src/modules/files-storage/service/files-storage.service.ts
=> BC-2871 improved logging

apps/server/src/modules/tool/service/external-tool-version.service.spec.ts, apps/server/src/modules/tool/service/external-tool-version.service.ts
Fixed version increasement for new optional parameter. There should be no increasement when a optional parameter added
https://ticketsystem.dbildungscloud.de/browse/N21-521
=> N21-521 Fixed version increasement for new optional parameter

apps/server/src/shared/domain/entity/submission.entity.ts, backup/setup/submissions.json
=> BC-2855 - add unique index by student and task

apps/server/src/modules/provisioning/strategy/sanis/sanis-response.mapper.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/sanis-response.mapper.ts, apps/server/src/modules/provisioning/strategy/sanis/sanis.response.ts, apps/server/src/modules/provisioning/strategy/sanis/sanis.strategy.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/service/sanis-school.service.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/service/sanis-user.service.spec.ts, apps/server/src/modules/provisioning/strategy/sanis/service/sanis-user.service.ts
Add Email to SANIS Provisioning 
https://ticketsystem.dbildungscloud.de/browse/N21-518
=> N21-518 add update email policy for sanis

apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.spec.ts, apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-configuration.service.ts
Load issuer details from well-known endpoint.
https://ticketsystem.dbildungscloud.de/browse/EW-429
See description.
NA
NA
NA
=> EW-429 Fix Login via OIDC Mock

apps/server/doc/code-style.md, apps/server/doc/summary.json, backup/setup/submissions.json
=> add docs for class declarations

apps/server/src/modules/files/repo/embedded-files.repo.ts, apps/server/src/modules/files/uc/sync-embedded-files.uc.ts
=> BC-2573 - Migrate embedded grading files

apps/server/src/modules/files/repo/orphaned-files.repo.ts
=> BC-2566 Cleanup orphaned grading files

src/services/teams/index.js, src/services/teams/model.js
Add teammember role to list of valid roles
More information on tickiet  https://ticketsystem.dbildungscloud.de/browse/BC-3093
https://ticketsystem.dbildungscloud.de/browse/BC-3093
=> Fix invite teacher by email

src/services/teams/index.js, src/services/teams/model.js, test/services/teams/index.test.js
this reverts 2 tickets, the original 2909 and its followup 3093
BC-2909 
BC-3093
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3090
=> BC-2909 - BC-3093 revert

apps/server/src/modules/provisioning/strategy/oidc/service/oidc-provisioning.service.spec.ts, apps/server/src/modules/provisioning/strategy/oidc/service/oidc-provisioning.service.ts
- fix sanis provisioning by adding the system to the school
https://ticketsystem.dbildungscloud.de/browse/N21-586
=> N21-586 fix sanis provisioning

apps/server/src/modules/files-storage/entity/filerecord.entity.ts
=> BC-3150 - add indexes to fileStorage entity

src/services/fileStorage/utils/filePermissionHelper.js, src/services/homework/model.js, test/services/fileStorage/utils/filePermissionHelper.test.js
=> BC-3181 remove unnecessary permission checks

apps/server/src/modules/files-storage/entity/filerecord.entity.spec.ts, apps/server/src/modules/files-storage/entity/filerecord.entity.ts
=> BC-3136 - Remove lockedForUserId from filerecord entity

apps/server/src/modules/files-storage/entity/filerecord.entity.spec.ts, apps/server/src/modules/files-storage/entity/filerecord.entity.ts
=> BC-3138 - Add isCopyFrom to filerecord

apps/server/src/modules/learnroom/controller/dashboard.controller.spec.ts, apps/server/src/modules/learnroom/controller/dashboard.controller.ts, apps/server/src/modules/learnroom/controller/dto/dashboard.params.ts, apps/server/src/modules/learnroom/uc/dashboard.uc.ts
- https://ticketsystem.dbildungscloud.de/browse/BC-3167
=> BC-3167-fix-generate-server

.github/workflows/dependabot-to-jira.yml, .github/workflows/push.yml
=> BC-3143 add dependabot-to-jira workflow

ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-3436
=> BC-3436 forbid parallel ldap sync runs

.github/workflows/dependabot-to-jira.yml
=> BC-3561 readd missing pr body for dependabot updates

package-lock.json
=> BC-3724 - Bump cookiejar

.eslintrc.js, apps/server/src/imports-from-feathers.ts, apps/server/src/modules/account/services/account-idm.service.integration.spec.ts, apps/server/src/modules/account/services/account.service.integration.spec.ts, apps/server/src/modules/learnroom/uc/dashboard.uc.spec.ts, apps/server/src/modules/learnroom/uc/lesson-copy.uc.ts, apps/server/src/modules/lesson/service/lesson-copy.service.spec.ts, apps/server/src/modules/task-card/controller/mapper/task-card.mapper.spec.ts, apps/server/src/modules/task-card/uc/task-card.uc.ts, apps/server/src/shared/infra/identity-management/keycloak-administration/keycloak-administration.module.ts, apps/server/src/shared/infra/identity-management/keycloak-administration/service/keycloak-administration.service.ts, apps/server/src/shared/infra/identity-management/keycloak-configuration/service/keycloak-configuration.service.integration.spec.ts, apps/server/src/shared/infra/identity-management/keycloak-configuration/service/keycloak-configuration.service.spec.ts, apps/server/src/shared/infra/identity-management/keycloak-configuration/service/keycloak-seed.service.spec.ts, apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-identity-management.service.integration.spec.ts, apps/server/src/shared/infra/identity-management/keycloak/service/keycloak-identity-management.service.spec.ts, src/services/statistic/index.js
=> Bc 3769 nest lint job is slow

package-lock.json, package.json
Bump webpack and @nestjs/cli in schulcloud-server
https://ticketsystem.dbildungscloud.de/browse/BC-3629
=> BC-3629 - update dev dependency nestjs/cli

src/services/authentication/configuration.js
Fix account property access for JWT creation by feathers authentication library, during TSP login.
https://ticketsystem.dbildungscloud.de/browse/BC-3798
See description
NA
NA
NA
=> BC-3798 Fix TSP account id discovery

.github/workflows/test.yml
This PR contains the required changes in order to update the used NodeJS versions to version 18 (LTS) across all three projects ("schulcloud-server", "schulcloud-client" and "nuxt-client).
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4064
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3169
https://github.com/hpi-schul-cloud/nuxt-client/pull/2492
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/206
https://ticketsystem.dbildungscloud.de/browse/BC-3748
=> BC-3748 NodeJS update (Part 2)

apps/server/src/modules/account/uc/account.uc.ts
https://ticketsystem.dbildungscloud.de/browse/BC-3812
=> BC-3812 Remove wrong check of env variable

package-lock.json, package.json
since it was only used for building docs using npx, so it should download and use that dependency when needed instead of blocking other dependencies from getting updated
it for example gets rid of all the angular dev dependencies too
=> removed the compodoc dependency

src/services/teams/hooks/index.js
There is no response after clicking "Leave team" button on client side. This is caused by problems on server side and not responding to client call.
https://ticketsystem.dbildungscloud.de/browse/BC-3830
=> Bc3830 Fix error while leaving team. Cannot read property of undefined

apps/server/src/modules/files-storage-client/service/files-storage-client.service.spec.ts, apps/server/src/modules/files-storage-client/service/files-storage-client.service.ts, apps/server/src/modules/files-storage-client/service/files-storage.producer.spec.ts, apps/server/src/modules/files-storage-client/service/files-storage.producer.ts, apps/server/src/modules/files-storage/controller/files-storage.consumer.spec.ts, apps/server/src/modules/files-storage/controller/files-storage.consumer.ts, apps/server/src/modules/files-storage/repo/filerecord.repo.integration.spec.ts, apps/server/src/modules/files-storage/repo/filerecord.repo.ts, apps/server/src/modules/files-storage/service/files-storage-delete.service.spec.ts, apps/server/src/modules/files-storage/service/files-storage-get.service.spec.ts, apps/server/src/modules/files-storage/service/files-storage-update.service.spec.ts, apps/server/src/modules/files-storage/service/files-storage-upload.service.spec.ts, apps/server/src/modules/files-storage/service/files-storage.service.ts, apps/server/src/modules/files-storage/uc/files-storage-delete.uc.spec.ts, apps/server/src/modules/files-storage/uc/files-storage-get.uc.spec.ts, apps/server/src/modules/files-storage/uc/files-storage.uc.ts, apps/server/src/modules/lesson/service/lesson.service.spec.ts, apps/server/src/modules/lesson/service/lesson.service.ts, apps/server/src/modules/task/service/submission.service.spec.ts, apps/server/src/modules/task/service/submission.service.ts, apps/server/src/modules/task/service/task.service.spec.ts, apps/server/src/modules/task/service/task.service.ts
=> BC-4141 - Reduce deleteFilesOfParents params

config/development.json
Set "FEATURE_COURSE_SHARE": true 
https://ticketsystem.dbildungscloud.de/browse/BC-4155
=> BC-4155 – Set feature share true

apps/server/src/modules/fwu-learning-contents/fwu-learning-contents.module.ts
On the dev environment (e.g. BRB-Main) the pod of the api-fwu-deployment is no longer restarted correctly when deploying.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-4162
Added FilesStorageAMQPModule to imports of the fwu-learning-contents module.
=> BC-4162-FWU-microservice-dependency-bug

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
Fixes the init job to work again
https://ticketsystem.dbildungscloud.de/browse/BC-4215
=> BC-4215 fixes change from mongodb to mongosh

apps/server/src/modules/authentication/controllers/api-test/login.api.spec.ts, apps/server/src/modules/authentication/strategy/ldap.strategy.spec.ts, apps/server/src/modules/authentication/strategy/ldap.strategy.ts
https://ticketsystem.dbildungscloud.de/browse/BC-4223
=> BC-4223 Fix LDAP Login

package-lock.json, package.json
=> BC-4192 - Bump socket.io-parser in schulcloud-server

apps/server/src/shared/domain/entity/dashboard.model.entity.ts
add missing indizes for dashboard entities
- https://ticketsystem.dbildungscloud.de/browse/BC-4221
=> BC-4221 add missing dashboard indizes

src/services/school/hooks/index.js, test/services/school/index.test.js
- change the school number regex to contain any combination of alphanumerical characters and hyphens
https://ticketsystem.dbildungscloud.de/browse/N21-912
=> N21-912 Change official school number regex

apps/server/src/shared/domain/entity/course.entity.ts, apps/server/src/shared/repo/course/course.repo.integration.spec.ts, src/services/user-group/model.js
https://ticketsystem.dbildungscloud.de/browse/N21-883
=> N21-883 Add videoconference feature to courses

apps/server/src/modules/tool/controller/dto/response/tool-reference.response.ts, apps/server/src/shared/domain/entity/federal-state.entity.ts, apps/server/src/shared/testing/factory/federal-state.factory.ts
Changes api description for generation
https://ticketsystem.dbildungscloud.de/browse/N21-927
https://github.com/hpi-schul-cloud/nuxt-client/pull/2603
=> N21-927 change api property for generation

.github/workflows/push.yml
=> BC-4051 Add cypress tests to push workflow

ansible/roles/schulcloud-server-core/templates/deployment.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-4410
This PR adds info about the metrics server port number of the API container.
=> BC-4410 - add info about the metrics endpoint of the API container

ansible/roles/schulcloud-server-core/tasks/main.yml
=> THR-28 remove ansible service from main

apps/server/src/modules/tool/controller/mapper/external-tool-request.mapper.ts, apps/server/src/modules/tool/controller/mapper/external-tool-response.mapper.ts, apps/server/src/modules/tool/interface/custom-parameter-type.enum.ts, apps/server/src/modules/tool/launch-tool/service/strategy/abstract-launch.strategy.spec.ts, apps/server/src/modules/tool/launch-tool/service/strategy/abstract-launch.strategy.ts, apps/server/src/modules/tool/service/validation/common-tool-validation.service.spec.ts, apps/server/src/modules/tool/service/validation/school-external-tool-validation.service.spec.ts, apps/server/src/modules/tool/service/validation/school-external-tool-validation.service.ts, apps/server/src/shared/domain/entity/tools/external-tool/custom-parameter/custom-parameter-type.enum.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1063
=> N21-1063 - wrong auto parameter

ansible/roles/schulcloud-server-tspsync/tasks/main.yml
fix spelling at ansible task in ansible role to remove an tsp cron job
https://ticketsystem.dbildungscloud.de/browse/BC-4613
=> BC-4613 - fix spelling at ansible task in ansible role to remove an tsp cronjob

apps/server/src/modules/tool/common/common-tool.module.ts, apps/server/src/modules/tool/common/service/common-tool-validation.service.spec.ts, apps/server/src/modules/tool/common/service/common-tool-validation.service.ts, apps/server/src/modules/tool/common/service/index.ts, apps/server/src/modules/tool/context-external-tool/context-external-tool.module.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.spec.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.ts, apps/server/src/modules/tool/external-tool/service/external-tool-validation.service.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool-validation.service.spec.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool-validation.service.ts, backup/setup/external_tools.json, test/services/link/index.test.js
Adds more validation to creation of context external tools
=> N21-906 adds more validation to creation of context external tool

src/services/user/hooks/userService.js
https://ticketsystem.dbildungscloud.de/browse/N21-900
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3249
=> N21-900 Hide outdated users

scripts/copy-legacy-tool-to-ctl.js, scripts/migrate-legacy-bbb.js
To run migration scripts at a later time 2 scripts have been put into the scripts folder
=> N21-1115 migration scripts put into scripts folder

scripts/copy-legacy-tool-to-ctl.js
Bugfix in copy-legacy-tool-to-ctl script
https://ticketsystem.dbildungscloud.de/browse/N21-1147
=> N21-1147 - ctl migration script

package-lock.json, package.json
Dependency update from @types/lodash (4.14.178 to 4.14.196)
PR is based on an automatic generated Pull Request (noted in links section)
BC-4704
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4279
=> BC-4704 - @types/lodash from 4.14.178 to 4.14.196

package-lock.json
Updates Dependency word-wrap
Based on autmatically generated PR 
BC-4706
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4281
=> BC - 4706 word wrap from 1.2.3 to 1.2.5

apps/server/src/modules/tool/context-external-tool/controller/api-test/tool-context.api.spec.ts, apps/server/src/modules/tool/context-external-tool/controller/tool-context.controller.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.spec.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool.service.spec.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool.service.ts, apps/server/src/modules/tool/context-external-tool/uc/context-external-tool.uc.spec.ts, apps/server/src/modules/tool/context-external-tool/uc/context-external-tool.uc.ts, apps/server/src/shared/testing/factory/external-tool-entity.factory.ts
https://ticketsystem.dbildungscloud.de/browse/N21-909
https://github.com/hpi-schul-cloud/nuxt-client/pull/2722
=> N21-909 Update ContextExternalTool

apps/server/src/modules/tool/external-tool/service/external-tool-parameter-validation.service.spec.ts, apps/server/src/modules/tool/external-tool/service/external-tool-parameter-validation.service.ts
Fixes the boolean validation for external tools. It should pass when no parameters are given
https://ticketsystem.dbildungscloud.de/browse/N21-1161
=> N21-1161 fixed boolean validation

apps/server/src/modules/tool/common/service/common-tool-validation.service.spec.ts, apps/server/src/modules/tool/common/service/common-tool-validation.service.ts, apps/server/src/modules/tool/external-tool/service/external-tool-parameter-validation.service.spec.ts, apps/server/src/modules/tool/external-tool/service/external-tool-parameter-validation.service.ts, apps/server/src/shared/testing/factory/domainobject/tool/external-tool.factory.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1155
=> N21-1155 Add validation of default value for external tool custom parameters of all types

apps/server/src/modules/board/repo/board-do.repo.spec.ts, apps/server/src/modules/board/repo/board-do.repo.ts, apps/server/src/modules/board/service/column-board.service.spec.ts, apps/server/src/modules/board/service/column-board.service.ts, apps/server/src/modules/learnroom/service/column-board-target.service.spec.ts, apps/server/src/shared/domain/entity/legacy-board/board.entity.spec.ts
- https://ticketsystem.dbildungscloud.de/browse/BC-4428
=> BC-4428 - fix uncovered board lines

apps/server/src/modules/h5p-editor/controller/api-test/h5p-editor-files.api.spec.ts, apps/server/src/modules/h5p-editor/service/libraryStorage.service.spec.ts, apps/server/src/modules/h5p-editor/service/libraryStorage.service.ts, apps/server/src/modules/h5p-editor/uc/h5p-files.uc.spec.ts, apps/server/src/modules/h5p-editor/uc/h5p.uc.ts
This PR reworks some internals for the H5P Library Storage 
=> THR-42 fixes to library storage

src/services/ltiTool/hooks/index.js
=> BC-4891 - fix delete tool

apps/server/src/modules/account/controller/dto/account.response.ts, apps/server/src/modules/account/mapper/account-response.mapper.spec.ts, apps/server/src/modules/account/mapper/account-response.mapper.ts
The updatedAt value was added to the account response to display it in the Superhero Dashboard.
https://ticketsystem.dbildungscloud.de/browse/EW-547
https://github.com/hpi-schul-cloud/nuxt-client/pull/2770
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/227
=> EW-547 Showing updatedAt information in the SHD

apps/server/src/modules/files-storage/service/preview.service.spec.ts, apps/server/src/modules/files-storage/service/preview.service.ts
=> BC-4975 - Only resize image if original width is bigger than target width

apps/server/src/modules/class/service/class.service.spec.ts, apps/server/src/modules/class/service/class.service.ts
https://ticketsystem.dbildungscloud.de/browse/BC-4971
=> BC-4971 rewrite data retrival for user-group

apps/server/src/modules/learnroom/service/board-copy.service.ts, apps/server/src/modules/learnroom/service/common-cartridge-export.service.spec.ts, apps/server/src/modules/learnroom/service/course.service.ts, apps/server/src/modules/learnroom/service/rooms.service.spec.ts, apps/server/src/modules/learnroom/service/rooms.service.ts, apps/server/src/modules/lesson/service/lesson-copy.service.spec.ts, apps/server/src/modules/sharing/service/share-token.service.spec.ts, apps/server/src/modules/sharing/service/share-token.service.ts, apps/server/src/modules/sharing/uc/share-token.uc.spec.ts, apps/server/src/modules/sharing/uc/share-token.uc.ts, apps/server/src/modules/task/index.ts, apps/server/src/modules/tool/tool-launch/service/strategy/abstract-launch.strategy.spec.ts, apps/server/src/modules/tool/tool-launch/service/strategy/abstract-launch.strategy.ts, apps/server/src/modules/tool/tool-launch/service/strategy/basic-tool-launch.strategy.spec.ts, apps/server/src/modules/tool/tool-launch/service/strategy/lti11-tool-launch.strategy.spec.ts, apps/server/src/modules/tool/tool-launch/service/strategy/lti11-tool-launch.strategy.ts, apps/server/src/modules/tool/tool-launch/service/strategy/oauth2-tool-launch.strategy.spec.ts, apps/server/src/modules/tool/tool-launch/tool-launch.module.ts, apps/server/src/modules/video-conference/service/video-conference.service.spec.ts, apps/server/src/modules/video-conference/service/video-conference.service.ts, apps/server/src/modules/video-conference/uc/video-conference-deprecated.uc.spec.ts, apps/server/src/modules/video-conference/uc/video-conference-deprecated.uc.ts
Refactors the usage of courses in tool module. Uses the course service instead of the course repo. 
https://ticketsystem.dbildungscloud.de/browse/N21-1256
=> N21-1256 use course service in tool

esbuild/esmodules-bundler.js
=> BC-5080 - fix compilation problem on windows

apps/server/src/shared/domain/domainobject/board/file-element.do.ts
=> BC-3475 - fix bug by update of height

apps/server/src/shared/domain/domainobject/board/file-element.do.spec.ts, apps/server/src/shared/domain/domainobject/board/file-element.do.ts
=> BC-3800 - Add caption of file

apps/server/src/modules/board/controller/api-test/content-element-create.api.spec.ts, apps/server/src/modules/board/controller/api-test/content-element-update-content.spec.ts, apps/server/src/modules/board/controller/dto/card/card.response.ts, apps/server/src/modules/board/controller/dto/element/submission-container-element.response.ts, apps/server/src/modules/board/controller/dto/element/update-element-content.body.params.ts, apps/server/src/modules/board/controller/mapper/submission-container-element-response.mapper.ts, apps/server/src/modules/board/repo/board-do.builder-impl.ts, apps/server/src/modules/board/repo/recursive-save.visitor.ts, apps/server/src/modules/board/service/content-element-update.visitor.ts, apps/server/src/shared/domain/domainobject/board/content-element.factory.ts, apps/server/src/shared/domain/domainobject/board/submission-container-element.do.ts, apps/server/src/shared/domain/entity/boardnode/submission-container-element-node.entity.ts, apps/server/src/shared/testing/factory/boardnode/submission-container-element-node.factory.ts
Make the dueDate of a submission container optional so it does not need to be set by the frontend.
BC-4374
https://github.com/hpi-schul-cloud/nuxt-client/pull/2777
=> BC-4374 - make submission due date optional 

package-lock.json, package.json
Bumps [crypto-js](https://github.com/brix/crypto-js) from 4.1.1 to 4.2.0.
- [Commits](https://github.com/brix/crypto-js/compare/4.1.1...4.2.0)
---
updated-dependencies:
- dependency-name: crypto-js dependency-type: direct:production ...
BC-5659
=> BC-5659 - Bump crypto-js from 4.1.1 to 4.2.0 in schulcloud-server

apps/server/src/modules/account/repo/account.repo.ts
1. This PR fixes the call of find function in the keycloak migration job, by adding a sorting option to ensure the same result base where the users are queried from
2. clear the cache for each find call in the keycloak migration job, to avoid a memory leak
=> BC-4887 add sort for users to be migrated and clear cache

apps/server/src/modules/tool/common/service/common-tool-validation.service.spec.ts, apps/server/src/modules/tool/common/service/common-tool-validation.service.ts, apps/server/src/modules/tool/context-external-tool/controller/api-test/tool-context.api.spec.ts, apps/server/src/modules/tool/context-external-tool/mapper/context-external-tool-request.mapper.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool-validation.service.ts, apps/server/src/modules/tool/school-external-tool/controller/api-test/tool-school.api.spec.ts, apps/server/src/modules/tool/school-external-tool/mapper/school-external-tool-request.mapper.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool-validation.service.spec.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool-validation.service.ts, apps/server/src/shared/testing/factory/external-tool-entity.factory.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1488
https://github.com/hpi-schul-cloud/nuxt-client/pull/2914
=> N21-1488 Fix optional external tool parameter with regex

apps/server/src/modules/tool/common/controller/dto/context-external-tool-count-per-context.response.ts, apps/server/src/modules/tool/common/controller/dto/index.ts, apps/server/src/modules/tool/external-tool/controller/dto/response/external-tool-metadata.response.ts, apps/server/src/modules/tool/external-tool/domain/external-tool-metadata.ts, apps/server/src/modules/tool/external-tool/mapper/external-tool-metadata.mapper.ts, apps/server/src/modules/tool/external-tool/service/external-tool-metadata.service.ts, apps/server/src/modules/tool/external-tool/uc/external-tool.uc.spec.ts, apps/server/src/modules/tool/school-external-tool/controller/dto/school-external-tool-metadata.response.ts, apps/server/src/modules/tool/school-external-tool/domain/school-external-tool-metadata.ts, apps/server/src/modules/tool/school-external-tool/mapper/school-external-tool-metadata.mapper.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool-metadata.service.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1512
https://github.com/hpi-schul-cloud/nuxt-client/pull/2925
=> N21-1512 Fix SchoolExternalTool metadata

ansible/roles/schulcloud-server-core/templates/api-files-ingress.yml.j2, ansible/roles/schulcloud-server-core/templates/ingress.yml.j2, ansible/roles/schulcloud-server-core/templates/tldraw-ingress.yml.j2, ansible/roles/schulcloud-server-h5p/templates/api-h5p-ingress.yml.j2
To improve the situation that one nginx ingress class can't handle our ingress definitions in less then 30 seconds.
We prepared to split the ingress to ingress classes for each tenant.
- hpi-schul-cloud/dof_app_deploy#719
- hpi-schul-cloud/superhero-dashboard#236
- hpi-schul-cloud/tldraw-client#26
- https://ticketsystem.dbildungscloud.de/browse/BC-5801
=> BC-5801 - Ingress class configurable

backup/setup/migrations.json, migrations/1701778850147-system-permissions-update.js
Updates systems permissions and adds SYSTEM_CREATE and SYSTEM_EDIT only for nbc
Seed data already has these permissions.
https://ticketsystem.dbildungscloud.de/browse/N21-1561
=> N21-1561 updates systems permissions

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2, src/services/oauth2/hooks/index.js, src/services/oauth2/index.js, test/services/oauth2/mock.js
- https://ticketsystem.dbildungscloud.de/browse/BC-6011
=> BC-6011 - try bettermarks uri config

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
curl did not retry when the host could not be reached, e.g. no route to host / Couldn't connect to server
https://ticketsystem.dbildungscloud.de/browse/BC-6026
=> BC-6026 make data seeding on dev more stable

Dockerfile.filepreview
https://ticketsystem.dbildungscloud.de/browse/BC-6038
=> BC-6038 install webp explicitly

apps/server/src/modules/legacy-school/entity/school-system-options.entity.ts
Sets the provisiong options embeddable to object instead of flatten
https://ticketsystem.dbildungscloud.de/browse/N21-1603
=> N21-1603 provisioning embeddable improvement

.github/workflows/tag.yml
=> BC-5658 - remove duplicate flag

apps/server/src/modules/group/controller/dto/interface/class-request-context.enum.ts, apps/server/src/modules/group/controller/dto/interface/index.ts, apps/server/src/modules/group/controller/dto/request/class-caller-params.ts, apps/server/src/modules/group/controller/dto/request/index.ts, apps/server/src/modules/group/controller/group.controller.ts, apps/server/src/modules/group/group-api.module.ts, apps/server/src/modules/group/uc/group.uc.spec.ts, apps/server/src/modules/group/uc/group.uc.ts, apps/server/src/modules/school/domain/do/school.spec.ts, apps/server/src/modules/school/domain/do/school.ts
when studentVisibility is active teachers could not see all classes of the school. This PR fixes the behaviour so that teachers can see all classes when working in courses and the studentVisibility feature is active.
https://ticketsystem.dbildungscloud.de/browse/N21-1623
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3377
https://github.com/hpi-schul-cloud/nuxt-client/pull/2967
=> N21-1623 fix class visibility for course

src/utils/database.js
=> BC-6101 - fix mongoose connection

apps/server/src/modules/group/controller/api-test/group.api.spec.ts, apps/server/src/modules/legacy-school/repo/schoolyear.repo.integration.spec.ts, apps/server/src/shared/testing/factory/schoolyear.factory.ts
=> BC-6131 - fix test factory for school year

test/services/rocketChat/index.test.js
=> removed unused test code

src/services/lesson/hooks/index.js
Exclude student from topic view on draft mode, only teacher can have access to this specific view.
https://ticketsystem.dbildungscloud.de/browse/BC-5809
I created functionality to dont allow student to have access to topic when they are in draft mode.
=> BC-5809 Exclude student from topic draft mode.

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2, src/services/ldap/strategies/general.js, test/services/ldap/strategies/general.test.js
Adds possibility to have multiple cns for teacher role in systems ldapConfig.providerOptions.roleAttributeNameMapping with separator ";;"
https://ticketsystem.dbildungscloud.de/browse/N21-1563
=> N21-1563 ldap-sync-multi-teacher-cn

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
Fixes seed data
- https://ticketsystem.dbildungscloud.de/browse/N21-1563
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4679
=> N21-1563 fixes seed data

src/services/lesson/hooks/index.js
in a find context there is no specific id thus resolving to undefined and resulting in an feathers mongoose issue
https://ticketsystem.dbildungscloud.de/browse/BC-6200
=> BC-6200 removing suspicious code

src/utils/feathers-mongoose/service.js, test/services/school/index.test.js
=> BC-6231 - fix feathers $limit=false

src/utils/redis.js
https://ticketsystem.dbildungscloud.de/browse/BC-6318
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3391
=> BC-6318 Register error event handler for redis client

apps/server/src/modules/user-login-migration/controller/dto/response/user-login-migration-search-list.response.ts, apps/server/src/modules/user-login-migration/controller/dto/response/user-login-migration.response.ts
Extends swagger docu for user login migration
https://ticketsystem.dbildungscloud.de/browse/N21-1600
=> N21-1600 extends swagger docu

ansible/roles/schulcloud-server-core/templates/preview-generator-scaled-object.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-6445
=> BC-6445 idle replica count must be lower than min

apps/server/src/modules/tool/external-tool/controller/api-test/tool.api.spec.ts, apps/server/src/modules/tool/external-tool/domain/datasheet/external-tool-parameter-datasheet-template-property.ts, apps/server/src/modules/tool/external-tool/mapper/external-tool-datasheet.mapper.spec.ts, apps/server/src/modules/tool/external-tool/mapper/external-tool-datasheet.mapper.ts, apps/server/src/modules/tool/external-tool/service/datasheet-pdf.service.ts, apps/server/src/modules/tool/external-tool/uc/external-tool.uc.spec.ts, apps/server/src/modules/tool/external-tool/uc/external-tool.uc.ts, apps/server/src/shared/testing/factory/domainobject/tool/external-tool-datasheet-template-data.factory.ts
a few adjustments for the creation of the ctl datasheet.
https://ticketsystem.dbildungscloud.de/browse/N21-1733
=> N21-1733 datasheet adjustments

ansible/roles/schulcloud-server-core/templates/preview-generator-scaled-object.yml.j2
see also https://keda.sh/docs/2.13/concepts/scaling-deployments/#idlereplicacount
> If this property is set, KEDA will scale the resource down to this number of replicas.
BC-6503
=> BC-6503 do not scale the preview-generator to 0

ansible/roles/schulcloud-server-core/tasks/main.yml, ansible/roles/schulcloud-server-core/templates/amqp-files-configmap.yml.j2, ansible/roles/schulcloud-server-core/templates/amqp-files-deployment.yml.j2, ansible/roles/schulcloud-server-core/templates/amqp-files-onepassword.yml.j2, ansible/roles/schulcloud-server-core/templates/preview-generator-configmap.yml.j2, apps/server/src/apps/files-storage-consumer.app.ts, apps/server/src/apps/preview-generator-consumer.app.ts, apps/server/src/core/logger/interfaces/logger-config.ts, apps/server/src/core/logger/logger.module.ts, apps/server/src/modules/server/server.config.ts, apps/server/src/shared/repo/types/StorageProviderEncryptedString.type.ts, config/default.schema.json, config/test.json, test/utils/setup.nest.services.js
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/777
https://github.com/hpi-schul-cloud/docker-compose/pull/66
=> Bc 6338 - When rabbitmq restarts the preview service gets stuck

apps/server/src/infra/rabbitmq/exchange/files-storage.ts, apps/server/src/modules/files-storage-client/service/files-storage-client.service.spec.ts, apps/server/src/modules/files-storage-client/service/files-storage-client.service.ts, apps/server/src/modules/files-storage-client/service/files-storage.producer.spec.ts, apps/server/src/modules/files-storage-client/service/files-storage.producer.ts, apps/server/src/modules/files-storage/controller/files-storage.consumer.spec.ts, apps/server/src/modules/files-storage/controller/files-storage.consumer.ts, apps/server/src/modules/tldraw/controller/api-test/tldraw.ws.api.spec.ts, apps/server/src/modules/tldraw/domain/ws-shared-doc.do.ts, apps/server/src/modules/tldraw/repo/tldraw-board.repo.spec.ts, apps/server/src/modules/tldraw/repo/y-mongodb.spec.ts, apps/server/src/modules/tldraw/service/index.ts, apps/server/src/modules/tldraw/service/tldraw-files-storage.service.spec.ts, apps/server/src/modules/tldraw/service/tldraw-files-storage.service.ts, apps/server/src/modules/tldraw/service/tldraw.ws.service.spec.ts, apps/server/src/modules/tldraw/service/tldraw.ws.service.ts, apps/server/src/modules/tldraw/tldraw-ws-test.module.ts, apps/server/src/modules/tldraw/tldraw-ws.module.ts, apps/server/src/modules/tldraw/types/index.ts, apps/server/src/modules/tldraw/types/tldraw-types.ts, apps/server/src/shared/testing/factory/tldraw.ws.factory.ts
QA note:
Change tested on env:
https://bc-6425-fix-assets-undo.nbc.dbildungscloud.dev/
No issues found. Undo works fine, picture shows again.
https://ticketsystem.dbildungscloud.de/browse/BC-6425
https://github.com/hpi-schul-cloud/tldraw-client/pull/50
=> BC-6425 - Fix tldraw assets undo/redo actions

src/services/activation/docs/openapi.yaml, src/services/activation/services/eMailAddress/index.js, test/services/activation/services/eMailAddress/index.test.js
Removal of POST /activation/eMailAddress api as it is not used in our system anymore
QA note:
change tested on env
https://bc-5258-remove-post-activation-email-api.dbc.dbildungscloud.dev/
https://bc-5258-remove-post-activation-email-api.nbc.dbildungscloud.dev/
No isuess found. I have tested by creating many users and tested all registration methods on env nbc and dbc
see : https://ticketsystem.dbildungscloud.de/browse/BC-5258
https://ticketsystem.dbildungscloud.de/browse/BC-5258
=> Remove post activation/eMailAddress api

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
BC-6130
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/789
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4757
https://github.com/hpi-schul-cloud/version-aggregator/pull/17
=> BC-6130 remove namespace activator from schulcloud-server

src/services/system/hooks/index.js, test/services/system/index.test.js
https://ticketsystem.dbildungscloud.de/browse/N21-1763
=> N21-1763 Fix deletion of external id, when removing an ldap system

apps/server/src/modules/tool/school-external-tool/service/school-external-tool.service.spec.ts, apps/server/src/modules/tool/school-external-tool/service/school-external-tool.service.ts
https://ticketsystem.dbildungscloud.de/browse/N21-1775
=> N21-1775 Fix deactivated status of CTL Tool in datasheet 

apps/server/src/modules/school/domain/do/school.ts
=> BC-6449 - switch patch school in client

ansible/roles/schulcloud-server-init/templates/configmap_file_init.yml.j2
The ctl tool name has to be SchulcloudNextcloud otherwise newly created teams has no members in nextcloud because their pseudonym in the externaltools-pseudonyms table cant be found. We look up for the nextcloud ctl tool with the NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME env and compare it with the ctl tool names.
- https://ticketsystem.dbildungscloud.de/browse/N21-1827
=> N21-1827 fixes nextcloud seed data

apps/server/src/migrations/mikro-orm/Migration20240320122229.ts, apps/server/src/modules/board/board.module.ts, apps/server/src/modules/board/service/column-board-copy.service.spec.ts, apps/server/src/modules/board/service/column-board-copy.service.ts, backup/setup/migrations.json
=> BC-6806 - board copy title

apps/server/src/modules/tool/common/common-tool.module.ts, apps/server/src/modules/tool/common/uc/tool-permission-helper.spec.ts, apps/server/src/modules/tool/common/uc/tool-permission-helper.ts, apps/server/src/modules/tool/context-external-tool/uc/context-external-tool.uc.spec.ts, apps/server/src/modules/tool/context-external-tool/uc/context-external-tool.uc.ts, apps/server/src/modules/tool/context-external-tool/uc/tool-reference.uc.spec.ts, apps/server/src/modules/tool/context-external-tool/uc/tool-reference.uc.ts, apps/server/src/modules/tool/external-tool/uc/external-tool-configuration.uc.spec.ts, apps/server/src/modules/tool/external-tool/uc/external-tool-configuration.uc.ts, apps/server/src/modules/tool/school-external-tool/uc/school-external-tool.uc.spec.ts, apps/server/src/modules/tool/school-external-tool/uc/school-external-tool.uc.ts, apps/server/src/modules/tool/tool-launch/uc/tool-launch.uc.spec.ts, apps/server/src/modules/tool/tool-launch/uc/tool-launch.uc.ts
This pr moves the loading of user before permission check to uc. This avoids multiple recursive population of users roles.
- https://ticketsystem.dbildungscloud.de/browse/N21-1839
=> N21-1839 ctl permission checks after update

apps/server/src/modules/learnroom/controller/api-test/course.api.spec.ts, apps/server/src/modules/learnroom/controller/course.controller.ts, apps/server/src/modules/learnroom/controller/dto/course-export.body.params.ts, apps/server/src/modules/learnroom/service/common-cartridge-export.service.spec.ts, apps/server/src/modules/learnroom/service/common-cartridge-export.service.ts, apps/server/src/modules/learnroom/uc/course-export.uc.spec.ts, apps/server/src/modules/learnroom/uc/course-export.uc.ts
User can control exported assignments.
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3162
- https://ticketsystem.dbildungscloud.de/browse/EW-724
=> EW-724: Control over assignments.

ansible/roles/schulcloud-server-init/templates/job_init.yml.j2, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2, ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
Use the infra-tools from quay.io
- https://ticketsystem.dbildungscloud.de/browse/BC-6994
- hpi-schul-cloud/dof_app_deploy#829
=> BC-6994 - infra-tools form quay.io

apps/server/src/modules/user-import/service/user-import.service.spec.ts, apps/server/src/modules/user-import/service/user-import.service.ts
fix migration wizard bug for identical names
- https://ticketsystem.dbildungscloud.de/browse/N21-1848
=> N21-1848 fixes matching of migration wizard

config/default.schema.json
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/55
=> BC-7009 changed default scan_file queue to scan_file_v2

apps/server/src/modules/management/seed-data/schools.ts, apps/server/src/modules/me/domain/school-permission.service.ts, apps/server/src/shared/domain/entity/user.entity.spec.ts, apps/server/src/shared/domain/entity/user.entity.ts
=> BC-7017 - add school-specific permissions to user entity

ansible/roles/schulcloud-server-init/templates/job_init.yml.j2
to avoid getting OOMKilled since k8s 1.28.7
https://ticketsystem.dbildungscloud.de/browse/BC-7037
=> BC-7037 increased init job memory to 2gb

apps/server/src/modules/provisioning/strategy/sanis/sanis-response.mapper.ts, apps/server/src/modules/user-import/mapper/schulconnex-import-user.mapper.ts, apps/server/src/modules/user-import/service/strategy/schulconnex-fetch-import-users.service.spec.ts, apps/server/src/modules/user-import/service/strategy/schulconnex-fetch-import-users.service.ts
Extend data pump by loading the users group-assignments from moin.schule
https://ticketsystem.dbildungscloud.de/browse/N21-1821
https://github.com/hpi-schul-cloud/nuxt-client/pull/3198
=> N21-1821 migration wizard load class assignment

src/services/wopi/hooks/index.js
https://ticketsystem.dbildungscloud.de/projects/PSW/issues/PSW-28
=> PSW-28 Fix XSS exploit on WOPI API

apps/server/src/modules/user-import/loggable/user-login-migration-not-active.loggable-exception.ts, apps/server/src/modules/user-import/loggable/user-login.migration-not-active.loggable-exception.spec.ts, apps/server/src/modules/user-import/uc/user-import.uc.spec.ts, apps/server/src/modules/user-import/uc/user-import.uc.ts
throw loggable exception in migration wizard when user login migration is not active
- https://ticketsystem.dbildungscloud.de/browse/N21-1785
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3215
=> N21-1785 throw loggable in wizard when migration is not active

apps/server/src/shared/domain/entity/boardnode/boardnode.entity.ts
https://github.com/mikro-orm/mikro-orm/issues/5505
https://ticketsystem.dbildungscloud.de/browse/BC-7197
=> BC-7197 remove type index

apps/server/src/modules/management/uc/database-management.uc.ts, apps/server/src/shared/domain/entity/user-source-options-entity.spec.ts, apps/server/src/shared/domain/entity/user-source-options-entity.ts, apps/server/src/shared/domain/entity/user.entity.spec.ts, apps/server/src/shared/domain/entity/user.entity.ts, apps/server/src/shared/repo/user/user.repo.integration.spec.ts
https://ticketsystem.dbildungscloud.de/browse/BC-7098
=> BC-7098 - add index for 'sourceOptions.tspUid' in users collection

apps/server/src/modules/deletion/repo/entity/deletion-request.entity.ts
https://ticketsystem.dbildungscloud.de/browse/BC-7306
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/866
=> BC-7306 add index to deletionrequests.updatedAt

ansible/roles/schulcloud-server-core/templates/amqp-files-deployment.yml.j2, config/default.schema.json
The amqp files deployment is using the api-config map which contains in case of nbc some schulconnex envs.
Because of this it also needs schulconnex__clientId and schulconnex__secret because those are required when some schulconnex env is used.
https://ticketsystem.dbildungscloud.de/browse/N21-1968
=> N21-1968 fixes missing secrets

apps/server/src/shared/domain/entity/user.entity.spec.ts, apps/server/src/shared/domain/entity/user.entity.ts
https://ticketsystem.dbildungscloud.de/browse/BC-7314
=> BC-7314 Fix resolving of LERNSTORE_VIEW permission

apps/server/src/modules/tool/context-external-tool/service/context-external-tool.service.spec.ts, apps/server/src/modules/tool/context-external-tool/service/context-external-tool.service.ts
when copying a course with a ctl tool, the ctl got deleted in the original course before.
=> N21-1885 fix copy course

apps/server/src/modules/tool/external-tool/controller/api-test/tool.api.spec.ts, apps/server/src/modules/tool/external-tool/controller/dto/request/config/basic-tool-config.params.ts, apps/server/src/modules/tool/external-tool/controller/dto/request/config/lti11-tool-config-create.params.ts, apps/server/src/modules/tool/external-tool/controller/dto/request/config/lti11-tool-config-update.params.ts, apps/server/src/modules/tool/external-tool/controller/dto/request/config/oauth2-tool-config-create.params.ts, apps/server/src/modules/tool/external-tool/controller/dto/request/config/oauth2-tool-config-update.params.ts
Validate baseUrl of external tools
https://ticketsystem.dbildungscloud.de/browse/N21-1992
=> N21-1992 Validate baseUrl

apps/server/src/modules/board/gateway/board-collaboration.gateway.ts
=> refactor managing socket channels

apps/server/src/modules/board/service/media-board/media-available-line.service.spec.ts, apps/server/src/modules/board/service/media-board/media-available-line.service.ts
Fixes media board error when a tool was deleted
=> N21-2020 Fixes mediaboard error

apps/server/src/infra/rabbitmq/exchange/files-storage.ts, apps/server/src/modules/board/service/internal/board-node-copy-context.spec.ts, apps/server/src/modules/board/service/internal/board-node-copy-context.ts, apps/server/src/modules/board/service/internal/board-node-copy-general.service.spec.ts, apps/server/src/modules/board/service/internal/board-node-copy-specific.service.spec.ts, apps/server/src/modules/board/service/internal/column-board-copy.service.ts, apps/server/src/modules/files-storage-client/interfaces/file-request-info.ts, apps/server/src/modules/files-storage-client/mapper/copy-files-of-parent-param.builder.spec.ts, apps/server/src/modules/files-storage-client/mapper/files-storage-param.builder.spec.ts, apps/server/src/modules/files-storage-client/mapper/files-storage-param.builder.ts, apps/server/src/modules/files-storage-client/service/copy-files.service.ts, apps/server/src/modules/files-storage-client/service/files-storage-client.service.spec.ts, apps/server/src/modules/files-storage-client/service/files-storage.producer.spec.ts
Amqp Filestorage needs adjustments to work with storageLocationId and storageLocation for copying files.
- https://ticketsystem.dbildungscloud.de/browse/N21-1967
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5051
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3291
=> N21-1967 fix amqp filestorage

apps/server/src/modules/learnroom/service/common-cartridge-import.service.spec.ts
Improve the cc import service test.
https://ticketsystem.dbildungscloud.de/browse/EW-917
=> EW-917: Improve common-cartridge-import-service test.

apps/server/src/modules/tldraw/tldraw-console.module.ts
=> BC-7585 - tldraw-console, Nest can't resolve dependencies

backup/setup/external-tools.json
- https://ticketsystem.dbildungscloud.de/browse/N21-1564
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/210
=> N21-1564 add seed data

apps/server/src/modules/legacy-school/controller/api-test/school.administration.api.spec.ts, apps/server/src/modules/legacy-school/loggable/schoolyear-no-years-left.loggable.ts, apps/server/src/modules/legacy-school/repo/schoolyear.repo.integration.spec.ts, apps/server/src/modules/legacy-school/repo/schoolyear.repo.ts, apps/server/src/modules/legacy-school/service/legacy-school.service.spec.ts, apps/server/src/modules/legacy-school/service/legacy-school.service.ts, apps/server/src/modules/legacy-school/service/school-year.service.spec.ts, apps/server/src/modules/legacy-school/service/school-year.service.ts, apps/server/src/modules/legacy-school/uc/admin-api-schools.uc.ts, apps/server/src/modules/user/uc/admin-api-user.uc.ts, config/development.json
=> BC-7390 - add schoolyears to adminapi created schools

config/default.schema.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/891
[BC-6930](https://ticketsystem.dbildungscloud.de/browse/BC-6930)
https://github.com/hpi-schul-cloud/nuxt-client/pull/3304
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3469
=> BC-6930 - enable new layout by default

ansible/roles/h5p-library-management/templates/api-h5p-library-management-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/api-delete-s3-files-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2, ansible/roles/schulcloud-server-core/templates/tldraw-delete-files-cronjob.yml.j2, ansible/roles/schulcloud-server-init/templates/job_init.yml.j2, ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-7676
=> BC-7676 Updated k8s jobs to run as non-root users

ansible/roles/h5p-library-management/templates/api-h5p-library-management-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/api-delete-s3-files-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob.yml.j2, ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2, ansible/roles/schulcloud-server-core/templates/tldraw-delete-files-cronjob.yml.j2, ansible/roles/schulcloud-server-init/templates/job_init.yml.j2, ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
Reverts hpi-schul-cloud/schulcloud-server#5109
=> Revert "BC-7676 Updated k8s jobs to run as non-root users"

package-lock.json, package.json
This reverts commit ff83cfd2334cbb6f4c187c01531f48be8023891a.
https://ticketsystem.dbildungscloud.de/browse/BC-7783
=> BC-7783 - Revert "Bump jose from 1.28.2 to 5.6.3 (#5097)"

apps/server/src/modules/board/domain/board-node.do.ts
When adding content to a column board (source board) there is an option to add a link element. After sharing/ copying the course a link to a topic or to a task is adjusted when imported/ copied. A link to a second column board (target board) is not. The link still points to the original course and not the course created by importing.
- BC-7367
=> BC-7367 - fix swapped links in board

src/components/helper/repo.helper.js
might actually fix some bug when it comes to user data deletion
https://ticketsystem.dbildungscloud.de/browse/BC-7845
=> BC-7845 fixup false positive exception

package-lock.json, package.json
BC-7842
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3502
=> BC-7842 - downgrade npm

.github/workflows/push.yml, ansible/roles/common-cartridge/tasks/main.yml, ansible/roles/h5p-library-management/tasks/main.yml, ansible/roles/moin-schule-sync/tasks/main.yml, ansible/roles/schulcloud-server-core/tasks/main.yml, ansible/roles/schulcloud-server-h5p/tasks/main.yml, ansible/roles/schulcloud-server-init/tasks/main.yml, ansible/roles/schulcloud-server-ldapsync/tasks/main.yml, ansible/roles/schulcloud-server-migration-system/tasks/main.yml, ansible/roles/schulcloud-server-tspsync/tasks/main.yml
- hpi-schul-cloud/superhero-dashboard#262
- hpi-schul-cloud/dof_app_deploy#936
- hpi-schul-cloud/schulcloud-client#3509
- hpi-schul-cloud/schulcloud-server#5189
- hpi-schul-cloud/nuxt-client#3365
- hpi-schul-cloud/tldraw-client#80
- hpi-schul-cloud/version-aggregator#21
- hpi-schul-cloud/h5p-staticfiles-server#11
- hpi-schul-cloud/schulcloud-calendar#163
- hpi-schul-cloud/antivirus_check_service#58
- hpi-schul-cloud/shd-client#7
- https://ticketsystem.dbildungscloud.de/browse/BC-7854
=> BC-7854 - split Ansible Jobs by Tags

apps/server/src/modules/user-import/controller/dto/import-user.response.ts, apps/server/src/modules/user-import/mapper/import-user.mapper.spec.ts, apps/server/src/modules/user-import/mapper/import-user.mapper.ts, apps/server/src/modules/user-import/mapper/schulconnex-import-user.mapper.ts, apps/server/src/modules/user-import/service/schulconnex-fetch-import-users.service.spec.ts, apps/server/src/shared/domain/entity/import-user.entity.ts, apps/server/src/shared/testing/factory/import-user.factory.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2119
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3364
=> N21-2119 migration assistant external role

package-lock.json, package.json
Update TypeScript from v5.5.3 => v5.5.4
BC-7545
=> BC-7545 - update typescript v5.5.3 => v5.5.4

scripts/copy-legacy-tool-to-ctl.js, scripts/migrate-legacy-bbb.js
just for completes the adopted migration scripts
=> BC-6985/BC-7901 migration aids

ansible/roles/schulcloud-server-core/tasks/main.yml
=> BC-7881 recreate tldraw migration job if necessary

apps/server/src/modules/board/domain/board-node.do.ts, apps/server/src/modules/board/service/board-node.service.spec.ts
We have to remove method "getTrueProps" from the BoardNode domain object which has been added mistakenly in [N21-2031](https://ticketsystem.dbildungscloud.de/browse/N21-2031).
The method has been added in order to be able to copy board nodes in tests. This can be done with the existing code "getProps" plus minor modifications.
BC-8063
=> BC-8063 - Remove excess Method from BoardNode

apps/server/src/modules/group/controller/api-test/group.api.spec.ts, apps/server/src/modules/group/controller/dto/response/group.response.ts, apps/server/src/modules/group/controller/dto/response/period.response.ts, apps/server/src/modules/group/controller/mapper/group-response.mapper.ts, apps/server/src/modules/group/domain/group-period.ts, apps/server/src/modules/group/domain/group.ts, apps/server/src/modules/group/domain/index.ts, apps/server/src/modules/group/repo/group-domain.mapper.ts, apps/server/src/modules/group/repo/group.repo.spec.ts, apps/server/src/modules/group/uc/dto/resolved-group.dto.ts, apps/server/src/modules/group/uc/mapper/group-uc.mapper.ts, apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-course-sync.service.spec.ts, apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-course-sync.service.ts, apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-group-provisioning.service.spec.ts, apps/server/src/modules/provisioning/strategy/oidc/service/schulconnex-group-provisioning.service.ts, apps/server/src/shared/testing/factory/domainobject/groups/group.factory.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2180
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3400
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3524
=> N21-2180 Fix date for synchronized courses

apps/server/src/modules/legacy-school/controller/api-test/school.administration.api.spec.ts, apps/server/src/modules/legacy-school/legacy-school.module.ts, apps/server/src/modules/legacy-school/service/legacy-school.service.spec.ts, apps/server/src/modules/legacy-school/service/legacy-school.service.ts, apps/server/src/modules/school/index.ts, apps/server/src/shared/domain/domainobject/legacy-school.do.ts, apps/server/src/shared/domain/entity/school.entity.ts, apps/server/src/shared/repo/school/legacy-school.repo.ts, config/test.json
- https://ticketsystem.dbildungscloud.de/browse/BC-7414
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/235
=> BC-7414 - add storage provider support to legacy school module

apps/server/src/apps/server.app.ts, apps/server/src/modules/board/domain/board-node.do.spec.ts, apps/server/src/modules/board/domain/board-node.do.ts, apps/server/src/modules/board/domain/types/any-board-node.ts, apps/server/src/modules/board/loggable/media-board/invalid-board-type.loggable-exception.ts, apps/server/src/modules/board/service/column-board.service.ts, apps/server/src/modules/board/service/media-board/media-available-line.service.spec.ts, apps/server/src/modules/board/service/media-board/media-available-line.service.ts, apps/server/src/modules/board/service/media-board/media-board.service.spec.ts, apps/server/src/modules/board/service/media-board/media-board.service.ts, apps/server/src/modules/pseudonym/pseudonym.module.ts, apps/server/src/modules/pseudonym/service/index.ts, apps/server/src/modules/roster/index.ts, apps/server/src/modules/roster/roster.config.ts, apps/server/src/modules/roster/roster.module.ts, apps/server/src/modules/roster/service/feathers-roster.service.spec.ts, apps/server/src/modules/roster/service/feathers-roster.service.ts, apps/server/src/modules/roster/service/index.ts, apps/server/src/modules/server/server.module.ts, apps/server/src/modules/tool/context-external-tool/uc/dto/context-external-tool.types.ts, apps/server/src/shared/domain/types/constructor.ts, apps/server/src/shared/domain/types/index.ts, test/services/roster/index.test.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2175
=> N21-2175 Add course boards to bettermarks

ansible/roles/moin-schule-sync/templates/moin-schule-users-deletion-queueing-cronjob-configmap.yml.j2, ansible/roles/moin-schule-sync/templates/moin-schule-users-sync-cronjob-configmap.yml.j2, ansible/roles/schulcloud-server-core/templates/data-deletion-trigger-cronjob-configmap.yml.j2
- hpi-schul-cloud/dof_app_deploy#975
- https://ticketsystem.dbildungscloud.de/browse/BC-8123
=> BC-8123 - set nest log level error

apps/server/src/modules/group/group.module.ts
- https://ticketsystem.dbildungscloud.de/browse/BC-8311
=> BC-8311 - fix circular dependency between modules

ansible/roles/schulcloud-server-core/tasks/main.yml
- hpi-schul-cloud/tldraw-server#26
- https://ticketsystem.dbildungscloud.de/browse/BC-8312
=> BC-8312 - fix state for External Secret for TLDraw server

apps/server/src/modules/group/entity/group.entity.ts
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1020
=> BC-8401 adding missing indexes to groups

apps/server/src/modules/provisioning/service/tsp-provisioning.service.ts, apps/server/src/modules/provisioning/strategy/tsp/tsp.jwt.payload.ts, apps/server/src/modules/provisioning/strategy/tsp/tsp.strategy.ts
Make ptscListKlasseId Optional so login as Admin on TSC works.
- https://ticketsystem.dbildungscloud.de/browse/EW-1081
=> EW-1081: Make ptscListKlasseId optional in TspJwtPayload.

.eslintrc.js
Adaption to avoid unneccessary public keywords in front of Entity-class properties.
BC-8200
=> BC-8200 - addition: exclude entity-classes from explicit-member-accessibility rule

package-lock.json, package.json
=> quickfix: cleanup dependencies

apps/server/src/modules/user-login-migration/service/school-migration.service.spec.ts, apps/server/src/modules/user-login-migration/service/school-migration.service.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2368
=> N21-2368 Fix unmarking outdated users after restarting a migration

package-lock.json, package.json
=> BC-8861 Revert upgrade of aws dependencies

apps/server/src/modules/video-conference/bbb/bbb.service.spec.ts, apps/server/src/modules/video-conference/bbb/bbb.service.ts
https://ticketsystem.dbildungscloud.de/browse/BC-8877
=> BC-8877 change bbb checksum to sha512

apps/server/src/modules/tool/external-tool/external-tool.module.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2401
=> N21-2401 Fix external tool rule

Dockerfile, Dockerfile.filepreview
https://ticketsystem.dbildungscloud.de/browse/BC-8965
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5509
https://github.com/hpi-schul-cloud/nuxt-client/pull/3551
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/280
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/172
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/71
https://github.com/hpi-schul-cloud/tldraw-client/pull/124
https://github.com/hpi-schul-cloud/tldraw-server/pull/53
=> BC-8965 fix container file warnings

apps/server/src/modules/tool/external-tool/entity/config/oauth2-tool-config.entity.ts, apps/server/src/modules/tool/external-tool/entity/external-tool.entity.ts, backup/setup/external-tools.json
- hpi-schul-cloud/dof_app_deploy#1110
- https://ticketsystem.dbildungscloud.de/browse/BC-8749
=> BC-8749 - added unique index to external-tools.config_clientId

src/services/authentication/strategies/JwtStrategy.js
https://ticketsystem.dbildungscloud.de/browse/BC-8964
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5522
https://github.com/hpi-schul-cloud/nuxt-client/pull/3548
=> BC-8964 allow cookie auth in feathersjs

src/services/calendar/courseCalendar.js
https://ticketsystem.dbildungscloud.de/browse/BC-9104
=> BC-9104 Fix axios options in course calendar service

apps/server/src/modules/lesson/lesson-api.module.ts, apps/server/src/modules/provisioning/schulconnex-group-provisioning-consumer.module.ts, apps/server/src/modules/provisioning/schulconnex-group-removal-consumer.module.ts, apps/server/src/modules/pseudonym/pseudonym.module.ts, apps/server/src/modules/video-conference/video-conference-api.module.ts
=> BC-9007 - Fix imports for app starts

apps/server/src/modules/authorization/feathers/feathers-authorization.service.ts, apps/server/src/modules/news/api/news.uc.ts
JIRA :
- https://ticketsystem.dbildungscloud.de/browse/BC-9363
=> BC-9363 - Fix News Overview throwing a 500

apps/server/src/infra/sync/media-licenses/service/vidis-sync.service.spec.ts, apps/server/src/infra/sync/media-licenses/service/vidis-sync.service.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2483
=> N21-2483 Remove VIDIS school number length restriction

ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2
* https://ticketsystem.dbildungscloud.de/browse/BC-9457
* hpi-schul-cloud/dof_app_deploy#1147
=> BC-9457 - set ttl seconds after finshed for api-migration job

package-lock.json, package.json
- https://ticketsystem.dbildungscloud.de/browse/N21-2503
- https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/19
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3648
=> N21-2503 Update H5P libraries

ansible/roles/schulcloud-server-migration-system/templates/deployment.yml.j2
=> BC-7210 - Add session-valkey-password secret reference to deployment configuration

.github/PULL_REQUEST_TEMPLATE.md, apps/server/src/modules/school/api/school.controller.ts, apps/server/src/modules/school/api/school.uc.ts, apps/server/src/modules/school/api/test/school-users.api.spec.ts
In order to get a list of student names and ids to support the membership-dialog for rooms, we need to add an endpoint.
BC-9080
- implementing endpoint to get students for specific school via `GET school/:schoolId/students`
=> BC-9080 - BE: Endpoint for requesting Students of a school

ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
=> BC-7210 - add session-valkey-password secret reference to LDAP sync cronjob

config/default.schema.json
- https://ticketsystem.dbildungscloud.de/browse/N21-2545
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1168
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3638
=> N21-2545 Create separate H5P feature flag for lessons

apps/server/src/shared/domain/types/image-mime-type.enum.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2549
=> N21-2549 Disable svg support for external tool logos

apps/server/src/modules/room/domain/events/room-deleted.event.ts, apps/server/src/modules/room/domain/service/room-invitation-link.service.spec.ts, apps/server/src/modules/room/domain/service/room-invitation-link.service.ts, apps/server/src/modules/room/domain/service/room.service.spec.ts, apps/server/src/modules/room/domain/service/room.service.ts, apps/server/src/modules/room/room.module.ts
- https://ticketsystem.dbildungscloud.de/browse/BC-9033
=> BC-9033 - Delete room invitation links when room is deleted

.github/workflows/dependency-review.yml
https://ticketsystem.dbildungscloud.de/browse/BC-9800
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5712
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3644
https://github.com/hpi-schul-cloud/nuxt-client/pull/3715
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/308
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/202
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/90
https://github.com/hpi-schul-cloud/tldraw-client/pull/167
https://github.com/hpi-schul-cloud/dependency-review-config/pull/2
=> BC-9800 use dependency-review-action-config

apps/server/src/modules/common-cartridge/service/common-cartridge-export.service.spec.ts, apps/server/src/modules/common-cartridge/service/common-cartridge-export.service.ts, apps/server/src/modules/common-cartridge/testing/common-cartridge-dtos.factory.ts
Sort cards to ensure correct order of cards.
- https://ticketsystem.dbildungscloud.de/browse/EW-1222
=> EW-1222: Sort cards to ensure correct order.

ansible/roles/media-licenses/templates/vidis-sync-cronjob-configmap.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-9917
=> BC-9917 change logging to (back to) info where appropriate

apps/server/src/modules/school/repo/school.entity.ts
=> introduce index for school federal state

apps/server/src/modules/server/api/dto/config.response.ts, apps/server/src/modules/server/api/test/server.api.spec.ts, apps/server/src/modules/server/server.config.ts, config/default.schema.json
- https://ticketsystem.dbildungscloud.de/browse/N21-2579
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1192
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3768
=> N21-2579 Hide link to old school admin page

apps/server/src/modules/video-conference/bbb/bbb.service.spec.ts, apps/server/src/modules/video-conference/bbb/bbb.service.ts
with BBB 3.0 sending the header with empty body leads to error
BC-10285
=> BC-10285 - fix BBB for empty presentation

sonar-project.properties
- hpi-schul-cloud/nuxt-client#3834
- hpi-schul-cloud/file-storage#69
- hpi-schul-cloud/tldraw-server#75
- https://ticketsystem.dbildungscloud.de/browse/BC-10418
=> BC-10418 - deaktivate githubcation scan from sonar

apps/server/src/apps/helpers/metrics/prometheus/handler.ts
https://ticketsystem.dbildungscloud.de/browse/BC-10601
=> BC-10601 set content type for prometheus to text/plain

.github/workflows/test.yml, apps/server/src/modules/h5p-editor/h5p-editor.app.module.ts, apps/server/src/modules/h5p-editor/repo/entity/library.entity.ts, apps/server/src/modules/h5p-editor/repo/h5p-content.repo.ts, apps/server/src/modules/h5p-editor/repo/library.repo.ts
=> BC-10521 - Enhance H5P module: add ensureIndexes option for MongoDB and update InstalledLibrary entity with additional index

ansible/roles/common-cartridge/templates/ingress.yml.j2, ansible/roles/schulcloud-server-core/templates/configmap.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-10615
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5884
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3697
https://github.com/hpi-schul-cloud/nuxt-client/pull/3886
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/325
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1249
=> BC-10615 adopt ansible migration aids
